### ISSUE TITLE
Board Review: Text Analytics

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk#1023]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Azure SDK team
* Link to documentation describing the service: https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics/
* Contact email (if service team, provide PM and Dev Lead): mayurid;annelo

## About this client library

* Name of the client library: azure.ai.textanalytics
* Languages for this review: Python and Java
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:  https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/samples

### Java

* Upload JAR to [apiview](https://apiview.azurewebsites.net).  Link: https://apiview.dev/Assemblies/Review/942b652edaf44b7189f41270cf07e54f
* Link to samples for champion scenarios:  https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/textanalytics/azure-ai-textanalytics/src/samples

### Python

* Upload the api as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-python/pull/9823
* Link to samples for champion scenarios: https://github.com/kristapratico/azure-sdk-for-python/blob/ta-api-listing/sdk/textanalytics/azure-ai-textanalytics/API_LISTING.md

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/textanalytics/ai-text-analytics/review/ai-text-analytics.api.md
* Link to samples for champion scenarios: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/textanalytics/ai-text-analytics/samples/typescript

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Estimate the percentage of developers using the service who would use the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

Examples of good scenarios are technology agnostic (i.e. the customer can do the same thing in multiple ways), and are expected to be used by > 20% of users:

* Upload a file
* Update firmware on the device
* Recognize faces in an uploaded image

Examples of bad scenarios:
* Create a client (it's part of a scenario, and we'll see it often enough in true champion scenarios)
* Send a batch of events (again, part of the scenario)
* Create a page blob (it's not used by enough of the user base)

## Agenda for the review

A board review is generally split into two parts, with additional meetings as required

Part 1 - Introducing the board to the service:
- Review of the service (no more than 10 minutes).
- Review of the champion scenarios.
- Get feedback on the API patterns used in the champion scenarios.

After part 1, you may schedule additional meetings with architects to refine the API and work on implementation.

Part 2 - the "GA" meeting
- Scheduled at least one week after the APIs have been uploaded for review.
- Will go over controversial feedback from the line-by-line API review.
- Exit meeting with concrete changes necessary to meet quality bar.

**Comment by adrianhall** [comment]
Scheduled for 2/24

**Comment by kyle-patterson** [comment]
Link to recording: (MSFT INTERNAL): https://msit.microsoftstream.com/video/9a62edad-82ac-4144-9ff8-9aa4da8f08c5

Follow-ups:
- Discuss with service team on the introduction of Warnings
- Discuss with service team on "confidence_scores" versus "scores" nomenclature
- Office hours on strings and graphemes - scheduled for 2/25
- Schedule part 2 to cover Java revisions and .NET API

Larger conversations that arose centered on 
- "Future-proofing" APIs by accounting for sync/async (possibly with paging)
- Naming conventions in batches/paging

**Comment by maririos** [comment]
>Discuss with service team on the introduction of Warnings

Conversation is currently on-going on email-thread.

>Discuss with service team on "confidence_scores" versus "scores" nomenclature

Service is looking into renaming to `confidence_scores` for sentiment analysis.
no changes on client library side.

> Office hours on strings and graphemes - scheduled for 2/25

Action items for the meeting that affect the client libraries for next preview and GA is to rename length and offset properties to include the word grapheme.
As for the service, they are going to work on a design that will allow for the user to specify the encoding the string is based on and according to that return the respective length and offset values.

**Comment by adrianhall** [comment]
Scheduled Python / JS Review on 3/3

**Comment by mayurid** [comment]
It will be the second wave (continuation) of Java review followed by .Net
Thanks Adrian for updating the meeting.

**Comment by maririos** [comment]
.NET updated API view link in preparation for tomorrow's Arch Board meeting review: https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7

FYI: @mayurid

**Comment by mssfang** [comment]
Java updated API view link: https://apiview.dev/Assemblies/Review/942b652edaf44b7189f41270cf07e54f/68d38ba525e244d9826ec3f0f80fa89b
FYI: @mayurid

**Comment by adrianhall** [comment]
Arch board review notes:

Java API:
- Do we have an overload for analyzeSentimentBatch which doesn't take the options?  Yes, we do, but you need to specify language as well.
**ACTION**:  Add another overload for text/language without options.

- What about renaming language to defaultLanguage?  This is already on the client object.
- The IDs in the list of strings is problematic - converting index to string.  Moving input into the result may assist here.
**ACTION**: Follow up with @JonathanGiles to fix this.  
**ACTION**: Be aware of this issue in other languages.

- Entity categories - should we return something for getSubCategory()?  Don't return something that the server doesn't return.
- What does the service do?  There isn't a difference, but it's optional in the swagger response.
- Is there a difference between absence of a value and the empty string?  Service will not return an empty string.
**ACTION**: Check samples to ensure null+isEmpty() is not being used.

- Do they always iterate over all entities, or do they index into the result?  They may want to filter, bucket, or map.  e.g. just find people.
- We don't have a good story of indexing into the result (e.g. get entity #3), but doesn't seem to be a use case for that.
- Is there a use case for multiple operations for strings?  Yes, coming from the service in June (LRO)
- @KrzysztofCwalina doesn't think the preview can be released as is.  The Unicode standards for Grapheme is too fluid.
  - From the service side: In April, we will return the strings in service API version v3 (won't have a fix for offset - you can get away with not releasing hte offsets).  Caveat around redaction (e.g. PII) - will need to search again. (Find/replace).  Then, in June, to specify the query parameter for encoding of the offsets.
- Can we add a redaction / masking method on the PII results?  Don't think so, since every single language needs an implementation of Grapheme used by the service.
- Can we return the offsets in a stable encoding?  (e.g. UTF-16, etc.)
- How can we ensure we don't ship the grapheme properties?   Can we just remove them from preview-3?  Yes, if we have an alternative.  We don't right now.  Is there an alternative?  Search and replace may or may not be correct.
- Are we sure we are getting the substring back in the same encoding?  If it's different, there is a concern on encoding differences.
**ACTION**: Replace `getGraphemeOffset/Length` with `getOffset/Length` with computed length/offset (and update implementation per April/June service releases) - investigate by language.

- @JonathanGiles didn't like the *Batch - however, offline conversations suggest leaving the naming alone.

**ACTION** Add extra overload on `detectLanguageBatch` (on all endpoints for language/countryHint)
**ACTION** Remove the `PerLabel` from the SentimentAnalysisScorePerLabel.
**ACTION** Do no rename `recognizeCategorizedEntitiesBatch` - other languages should switch to this nomenclature. (Feature crew should decide - it's not a strong signal)

.NET API:
- @KrzysztofCwalina thought Scott wanted the TokenCredential wanted it to be DefaultTokenCredential - don't think this is actually true.
**FOLLOWUP** with Scott.
- Samples - @assafi suggested not doing rounding on the client; There are certain cases because of rounding where the pos+neu+neg does not add up to 1 and they are meant to.  Will check when the service change went/will go live.
**FOLLOWUP** Check on the sample once the service is updated.
- Service might introduce mixed sentence sentiments.
**ACTION** Combine the DocumentSentimentLabel and SentenceSentimentLabel
**ACTION** Samples need to be updated, IReadOnlyList (instead of collection) and use implicit casts

Final points: (see recording at around 1hr40min)
* How do we specify relationships between entities?  (think of a graph)
  - What should the API look like?   We don't want customers to see the relations - we want to know what opinions are linked to an aspect.
  - Option 2 conveys more information.  Also seems to be more efficient (due to path)
  - **Arch board recommendation**:  Use option 2 (JSON pointers)
* What do we need to do for filter presets
  - Doesn't need to have special support in the client library
  - OData has functions that we might be able to use.
  - Really, it's a REST API issue, not a client SDK issue.

**Comment by mssfang** [comment]
@adrianhall 
For this Action:
```
ACTION Remove the PerLabel from the SentimentAnalysisScorePerLabel.
```
I believe all language agreed to stay with `SentimentAnalysisScorePerLabel`.  Is any offline conversation that I missed?

**Comment by adrianhall** [comment]
This might have been a mis-hearing from me.  I thought I heard "DO remove it because the name is too long".  

Please cycle back with the architects to confirm.  No need for another meeting on this.

**Comment by willmtemple** [comment]
Updated API listing PR for JavaScript: https://github.com/Azure/azure-sdk-for-js/pull/7665

FYI @mayurid

**Comment by maririos** [comment]
Latest API listing for .NET: https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7/55a4c2d4e33a4ab795945f161e00c692

**Comment by kyle-patterson** [comment]
Link to recording for JS/.NET (MSFT INTERNAL): https://msit.microsoftstream.com/video/32442448-0fe2-4de0-910f-0c586169f1a7

Notes from the review:
.NET Review:
**Topic**: Grapheme length
An issue has been opened for tracking.

**APPROVED** FOR PREVIEW 3


JavaScript Review:

**Topic**: PII Entities
- Almost same as entity recognition, identical response model
- Question: Are there differences between models JS uses and other languages?
-- Model shape follows pattern of other languages. JS directly uses a lot of code generated by swagger

**Topic**: Language detection
- Returns a tuple of results, iso6391 name, and confidence score
- This is based off the CultureInfo.TwoLetterISOLanguageName
- Question: What do archs think of the Iso6391 name?
-- Docs will have to call it out
-- This is the simplest of language names
-- Since it is searchable online, usability may not be a sticking point.
- Question: In the future, what if we use a different standard (or standard version)?
-- Backwards-compatibility keeps 639-1, and maybe have to add a property for "639-2".
-Question: What if this were more generic-named, and let documentation clarify which standard to use?
--- This may introduce a versioning problem, such as going from a two-digit code to a three-digit code

**APPROVED** FOR PREVIEW 3

**Comment by maririos** [comment]
@kyle-patterson is there more to this issue? or can we close it

**Comment by kyle-patterson** [comment]
Reviews were completed for all four languages, I'll close it out.
