### ISSUE TITLE
Board Review: Storage STG73 design discussion

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#1045]
This is an issue to track the first arch board meeting for adding Storage STG73 features to the storage libraries.  @amishra-dev will do a walk through of QuickQuery and ChangeFeed (including planned strategies with Avro) and @pemari-msft will walk the board through the rest of the STG73 features.

Some [background](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed?tabs=azure-portal) on ChangeFeed provided by @amishra-dev.

[Quick Query REST spec](https://microsoft-my.sharepoint.com/personal/erezvani_microsoft_com/_layouts/15/guestaccess.aspx?e=XXFlE8&share=EUpZyo_GgiZOl5KQFUKNjWcBsKQUO84iKtLITvSt57JduA)

**Comment by adrianhall** [comment]
Scheduled for Mar-5

**Comment by adrianhall** [comment]
Notes from the arch board meeting:  https://msit.microsoftstream.com/video/6417af66-9f5e-46ff-9118-db0c9e5f830e

New features:
- getPageReanges continuation token
- Sealed blobs (write for a time, then seal and they become read only)
- object replication service
- container restore
- versioning (automatic snapshots / AWS: stable versioning)
  - Can I SAS to a specific version?  Yes, you can
- blob tags
  - get / set tags & filter blobs by tag
  - will be used in attribute based access control (sept. timeframe)
- Jumbo blogs (much larger block and blob sizes)

KC - which of these features will result in complex design changes?  Quick Query & Change Feed
BT - concerns about lots of related concepts - automatic snapshots, e.g.
JS - Is the set tags "replace" or "merge" - we think it's merge, but service team will check.
PM - KeyVault moved to soft delete by default.  Is that the plan?  Yes, but there are issues in billing / retention / compliance to resolve.

## Quick Query
- support searching over CSV, JSON (and future AVRO, Parkey)
- data is returned in AVRO formatt
- How many customers?  Unclear
- Can I have errors for data that still gets returned?  (i.e. do I need to correlate)
  - For each row, it's either an error or a result.
- Should this be exposed through Synapse to the exclusion or as well?  (as well)
  - Synapse is building on top of it
- Why CSV instead of JSON (it searches both)
- Would it be 1 or 2 APIs (1 API)
- Should this be part of the core SDK?
  - Thinking different library, but @tg-msft thinks same library
  - Used by blobs, data lake and potentially files
  - There is only really query method (with overloads)
  - BlockBlobClient is already in specialized namespace.
  - New libraries have versioning challenges.
- Do we call it QuickQuery or just Query (just Query - avoid branding)
- AVRO parsing library for JS is 250Kb, which is a problem.

**RECOMMENDATION**: Place query on blob client in same package.

## Change Feed
- Ashish used a presentation and will attach later
- Separate client, or combined with blobs?   Separate client
- Why not a regular blob download - it's not just reading a blob
- We should look at EH EventProcessor class, and Cosmos Change Feed for inspiration

**RECOMMENDATION**: Use a separate client & package

- Should pump to EH be an option?
  - Change Notifications is an existing feature, pumps to EH or EG (not sure which) 
  - Service team will look into it

- Where should the AVRO parser live?
  - It won't be exposed, so internally it's an implementation detail.
  - Probably Azure.Core eventually.
