### ISSUE TITLE
Consider installing docfx from chocolatey

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#1067]
The pinned version of docfx (2.43.4) https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/docindex.yml#L26 

Is available on Chocolatey. Should we be installing from there? https://chocolatey.org/packages/docfx/2.43.4

**Comment by danieljurek** [comment]
Benefits of this approach would include: 

* Fewer steps to install (run `choco install` instead of the script) 
* Keeps docfx out of the working directory
* Chocolatey is already installed on Windows agents (https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#chocolatey)

**Comment by kurtzeborn** [comment]
In the past, chocolatey hasn't been used in our scenarios because we were concerned about how there is no package verification for packages it downloads and installs.  We should investigate whether or not the packages are now signed and verified which come from chocolatey and then make a call on this and other packages we could pick up from there.

How are we getting docfx today?

**Comment by kurtzeborn** [comment]
From the [chocalatey website](https://chocolatey.org/docs/security#rigorous-moderation-process-for-community-packages):
> We don't require cryptographically signing packages yet, that is a future enhancement

**Comment by kurtzeborn** [comment]
Ironically, looking at the [docfx download](https://github.com/dotnet/docfx/releases) on their website, none of the binaries in the zip file are signed, so maybe there's nothing more chocolatey could do here anyway.  We also checked the NUPKG for docfx and while the package is signed, the files it contains are not.

So our concerns about chocolatey are irrelevant when it comes to docfx because they don't sign anyway.

**Comment by kurtzeborn** [comment]
Issue opened on DocFX: https://github.com/dotnet/docfx/issues/5610

Bottom line, it won't make any difference for installing DocFX with chocolatey because DocFX isn't signed anyway.

Regardless, the concern is still there that chocolatey makes no commitment to verify signatures of the things it installs.  So we're concerned about opening up the precident of using chocolatey without any commitment from the tool on these security baselines.

**Comment by danieljurek** [comment]
@vhvb1989 -- We are avoiding chocolatey because it does not verify package signatures. I've opened an issue to move off of that for doxygen.
