### ISSUE TITLE
Change Request: Raise the bar for SDK Previews

### ISSUE THREAD

**Issue by loarabia** [Azure/azure-sdk#1079]
## The Basics

* Which design guideline is affected?
https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md

* Which target languages are affected?
All

* Describe the change:

There are a few changes

### 1. Preview criteria: increase number of languages 

Replace:
Support for at least 2 languages. Preferably, support one statically typed language (such as C# or Java) and one dynamically typed language (such as TypeScript or Python).

with: 
Support all four tier-1 languages in preview form (.NET, Java, Python, TypeScript) unless there is a good (and documented) reason to not include support for one of the languages.

### 2. Strengthen Preview duration guidance
Replace:
"Have a preview release available for at least one month to allow for community feedback."

with:
"Release 2 or more previews for each tier 1 language which are at least one month apart and where the final preview is released one month prior to GA and is code complete."

## Reasoning

For item 1. Part of our goal is for developers from any background to walk up to Azure and feel comfortable. We're risking developers thinking their language is a second class citizen on Azure by not supporting all tier 1 languages at preview. I'd rather start with the bar and then walk back from 4 down to 2 on a case by case basis than to start with a low bar in the first place.

For item 2. We've found it difficult to get meaningful feedback in under 1 month from the larger community. In addition, requiring only 1 preview means that we don't have time to actually show off the final API surface area. Thinking of user studies, we've done multiple user studies on a single library where each time it changed the API shape.

**Comment by Petermarcu** [comment]
>> We're risking developers thinking their language is a second class citizen on Azure by not supporting all tier 1 languages at preview.

Beyond this, doing certain languages later without previews also lowers the quality and increases the frustration during implementation due to time pressures. Getting user feedback is a critical part of the release process of libraries.

**Comment by ChrisHMSFT** [comment]
Hey All,

A couple of additional thoughts here as you consider updates to the requirements. 
- To me, preview is about vetting out a solution to ensure it has good product-market fit, usability and quality. Given the uncertain nature of this early stage development we expect (and have seen) that the product shape will change significantly during preview. 
- A top priority in preview is gathering feedback, talking with early adopters to learn gaps and responding quickly
- We (cognitive services) have seen that many early adopters are willing to use the REST endpoints directly.

Given the above, requiring all 4 SDKs at public preview would mean extra development effort early in the product maturity in order to release and gather public feedback. We'd also expect a lot of changes to the product, so theirs an increased risk that this code will churn if/when we break the design and update. Could this actually further delay our ability to update and release a product by:
1. expanding effort needed to get to preview 
2. expanding the effort needed to re-work the product based on learnings in the preview?

Part of this may be ensuring that there is a common understanding of the goals of a 'preview' product. I've noticed that many teams approach the public preview stage differently.

I do agree that all SDKs should have previews. Could we instead make the requirement something like "by the start of service preview the team must have 2 libraries in preview and an approved timeline for developing (including previews) of all the required libraries?" 

Best,
Chris

**Comment by Petermarcu** [comment]
@ChrisHMSFT, 

The spirit we were trying to get to was that at some point before GA all 4 languages would be available as previews mulitiple times and those previews should have enough time to iterate. I think if there is enough runway before GA, then its possible to have a relaxed count of languages on the first preview. What would you think about something like:

- 2 language are required for any preview.
- Tier 1 languages have to have a minimum of 2 previews prior to GA each with a month of time between them to incorporate feedback. (This means preview in all languages required a minimum of 3 months before GA.

Thoughts?

**Comment by ChrisHMSFT** [comment]
Agreed on the spirit. I like the suggestion. I think as we clarify the requirements for GA, we can make sure teams account for that in their preview planning and ensure they have a realistic work-back schedule. 

Do you have thoughts on which 2 languages are provided?

**Comment by Petermarcu** [comment]
My gut feeling says to be flexible on language and to have guidance on how to pick. For example, before you preview, I would expect that you have at least a few key partners you are working with to use the service and give feedback. The choice on what language to do could be heavily influenced by what helps you get your engaged customers on boarded. For Cognitive services I think the default answer would by Python and .NET unless there is a specific customer need to drive preview adoption.

**Comment by assafi** [comment]
100% supportive (actually thought these changes were already the default). 
But I wouldn't stop here. I also think we should extend this notion to preview service APIs:
- All preview APIs must have SDKs (I assume we can have 2 out of 4 if dev cost is too high)
- Preview APIs must be X amount of time in preview before moving to stable.

The rational is, that if a service does not have an SDK on a preview API the amount of usage and feedback received will be very limited. Than changing a stable API version because of SDK feedback is very difficult. 

I would also consider making the SDK iterations somewhat parallel to the API iterations. So preview SDKs follow a preview API, and the GA version follows the GA API and we do not require additional preview SDK versions on stable API.

**Comment by Petermarcu** [comment]
@assafi I love the direction you are trying to go which is to say that services shouldn't preview without the minimum SDK support we land on because the goal of the preview is to get feedback and you are limiting the quantity and quality of feedback you will get by not offering an SDK. Am I interpreting that correctly?

We've had a tough time figuring out the right way to do service previews and GA's from a library perspective in the past. Complexities around preview features on a  GA service for example. This is something we should dig into more.

**Comment by assafi** [comment]
@Petermarcu exactly. Would love to brainstorm around this. 
@ChrisHMSFT I think that at least for Cognitive Services we should raise this point for discussion on the next API guidelines discussion.

**Comment by kyle-patterson** [comment]
@loarabia and I had a conversation about including telemetry requirements in this bar-raising. Ie:

 "To graduate to GA...
- Support the telemetry policies established under the [General Guidelines](https://github.com/Azure/azure-sdk/blob/master/docs/general/azurecore.md#telemetry-policy)."

I'm working on internal guidance for Azure SDK teams to onboard this data to the pipeline, but given the length of that process I think the minbar is to ensure the SDKs are emitting the User Agent string.

**Comment by kyle-patterson** [comment]
Scheduled for 4/20

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/263ea1ff-0400-86ec-e680-f1ea834ef7f0

Increase number of languages:
- No objections
- Cog Svc is recommending this
- This may delay preview, but if a svc only needs few languages they can seek exception from teh board


Strengthen Preview duration guidance:
- Include something about type of feedback
- Time is a poor proxy for "received feedback"
- Maybe a better measure is that major customers are "happy" with what's delivered

Q: Should this even be in the guidelines?
- Could be in the policy documents
- However, weakening guidelines too much may impact the exception bar

Q: Does this all belong in PLR?
- Yes, this is already in the PLR, both in [azure-sdk](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/200/Azure-SDK-CLI-Product-Launch-Criteria) and [msazure](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/39224/Launch-Criteria)
**ACTION**: @kyle-patterson  to update policy documentation to point internal teams to PLR guidance
