### ISSUE TITLE
Board Review: Discuss Maturity Model around Services

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk#1138]
In our experiences we are quickly learning, some services are still iterating, currently have small usage and may require significant changes based on customer feedback and/or competitive pressure in order to grow and/or stay relevant. 
In the world where we want our libraries to withstand the test of time (not have breaking changes) we need to think of a maturity model around these services and see how we have libraries for them

**Comment by kyle-patterson** [comment]
Scheduled for 3/31

**Comment by kyle-patterson** [comment]
Link to recording (MSFT Internal): https://msit.microsoftstream.com/video/8e53a1ff-0400-86e7-445c-f1ea73a05a75

A number of services are in a space where they've previewed with useful functionality and customers; but they're interested in going GA, and expect a lot of functionality churn as they mature. The release requirements include an SDK at GA, but SDK requirements prohibit breaking changes on GA libraries. This poses a conflict between service and SDK requirements.

- "GA" is a single designation with many meanings, such as "stable" and "no breaking changes"; it also means "support" if using a GA feature, as opposed to lower support bar on preview. Customers are unlikely to adopt new features until we promise support. 

DISCUSSION: Theoretically, customers are willing to accept breaking changes as long as there is support (and security guarantees, etc). Separate "GA" into two concepts:
1. Feature is stable - the team has agreed not to introduce breaking changes
2. Feature is supported - the team has agreed to support customers facing bugs/issues

Note, there are two different definitions of nonbreaking: 
1. A developer writes code that runs for three years without changing anything;
2. A developer writes code that runs after taking the next-version package.

Q: What if the customer has a security bug? Would we provide a patch, or would the customer (possibly) have to accept breaking changes?
- This wasn't explored in-depth, but could start as a basis for investigation

Under this model, a service could GA with supportability, but might not be marked "stable" (no guarantee against breaking changes). Additionally, could confuse customers (among other negatives) who miss the differentiation. This might also be language-specific...

A problem the libraries face is not getting feedback on previews, possibly because of lack of support -- but would promising support before breaking changes impact this for early adopters, who might be looking for new features anyways?

Another problem with early adoption is some industries cannot adopt a service unless it GA's -- are these requirements similar for SDKs? In addition, what is the impact of changing the definition of GA in this case?



DISCUSSION: What about experimental packages? Release previews, review telemetry and customer feedback, before integrating into GA.

What are the practical implications of using up good namespaces early on?
- This is generalized across any language/service; and this will likely come up at some point with some service. Having a third-level namespace helps resolve this.


Part of the problem is that API guidelines and business decisions for GA might not align. How do we standardize a resolution for services that hit this misalignment? Additionally, services themselves are not aligned on nomenclature. 
- Consistency in SDKs might be more important, and that should be called out more clearly somewhere publicly accessible.
- In majority of cases, small inconsistencies between services (but not within languages) may be acceptable; it is only large alignment changes that would merit a major version change.
- Some of the things that have already GA'd may be what other services to align to


Q: When do we try to align with service consistency across libraries, and what heuristic should be used?
- We should be talking about consistency of what's known presently, don't let speculations interfere. Some of the inconsistencies are for the REST API board. 
- API reviews should be held earlier in the service design conversations; there is a larger conversation to be had about this process.

Q: What guidelines could be drafted around understanding the maturity model of a service?
RECOMMENDATION: It is too difficult to write guidelines without prior history; basing guidelines off of a list of known inconsistencies, or case studies, and letting that evolve is a better means

ACTION: Anne to follow up with list of currently known inconsistencies

Q: What about guidelines for namespaces?
- Should be using third-level namespaces, and discuss with the board when inconsistencies or confusing namespaces come up


For an example of evolution, we may come up with a new third-level namespace (or reclaim an old namespace).

Q: What about some heuristic to measure the maturity of a service?
- There may not be such a heuristic for every service; instead, the arch board should consider the maturity state of a service when conducting reviews
