### ISSUE TITLE
Board Review: Register namespace for mgmt-plane

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk#1245]
We are owner of Java management SDK.

Our support for track2 Java management SDK include following services.

### app service / web

`com.azure.management.appservice`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/web/resource-manager

### cdn

`com.azure.management.cdn`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cdn/resource-manager

### compute

`com.azure.management.compute`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager

### container registry

`com.azure.management.containerregistry`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/containerregistry/resource-manager

### container service

`com.azure.management.containerservice`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/containerservice/resource-manager

### cosmos

`com.azure.management.cosmos`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cosmos-db/resource-manager

### dns

`com.azure.management.dns`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/dns/resource-manager

### authorization

`com.azure.management.graphrbac` or `com.azure.management.authorization`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/authorization/resource-manager
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/graphrbac/data-plane

### keyvault

`com.azure.management.keyvault` or `com.azure.management.security.keyvault`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager

### monitor

`com.azure.management.monitor`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager

### managed service identity

`com.azure.management.managedserviceidentity`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/msi/resource-manager

### network

`com.azure.management.network`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager

### resources

`com.azure.management.resources`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager

### sql

`com.azure.management.sql`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/sql/resource-manager

### storage

`com.azure.management.storage`

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager

Finally, `com.azure.management` for shared support/configure/authentication classes for ARM, samples, etc.

Please advice the guideline on namespace for management SDKs. E.g. should we group container related service under a `<group>`?

We probably need to include owner of other SDKs. .NET, python, go, js, etc.

@JonathanGiles @yungezz @ChenTanyi @xccc-msft

**Comment by weidongxu-microsoft** [comment]
@kyle-patterson 

Any update on what is the next step?

**Comment by JonathanGiles** [comment]
We had a discussion on this today in the arch board. The tentative consensus we've reached is to continue to use what we have already specified in our guidelines, where the pattern is `<Azure>.management.<group>.<service>`.

Therefore, we would expect to have, e.g. `com.azure.management.security.keyvault`. In many of the namespaces outlined above, there is no group specified, so we should determine how best to proceed with those. The general consensus is to fit them into appropriate groups equivalent to where they would reside for the data plane client libraries. I'll propose the following (but note that these will change upon further review):

App service / Web: `com.azure.management.appmodel.appservice`
CDN : `com.azure.management.networking.cdn`
Compute: `com.azure.management.compute.compute`      // **ugh**
Container Registry: `com.azure.management.compute.containerregistry`
Container Service: `com.azure.management.compute.containerservice`
Cosmos: `com.azure.management.cosmos`
DNS: `com.azure.management.networking.dns`
Authorization: `com.azure.management.security.authorization`
Key Vault: `com.azure.management.security.keyvault`
Monitor: `com.azure.management.networking.monitor`      // **I'm especially unsure here**
Managed Service Identity: `com.azure.management.security.msi`
Network: `com.azure.management.networking.network`
Resources: `com.azure.management.management.resources`        // **ugh**
SQL: `com.azure.management.data.sql`
Storage: `com.azure.management.storage`

I've thrown these out without much knowledge of some of the services, but with consideration of their role and what our guidelines currently suggest, so these will change (please don't release until they are finalised). I'm pinging @Petermarcu @kyle-patterson @johanste @bterlson @JeffreyRichter @schaabs @KrzysztofCwalina for their feedback.

**Comment by JeffreyRichter** [comment]
I'm OK with all of this. I see the ugh & the unsure but I think the pattern consistency is what's valuable to customers here. They'll accept the ugh/unsure if they can effectively work with the pattern.

**Comment by Petermarcu** [comment]
What happens if we drop compute as a group?

**Comment by JonathanGiles** [comment]
If we drop the 'compute' group, are you suggesting we introduce a different group name in its place for the computer, container registry, and container service services?

**Comment by johanste** [comment]
For whatever it is worth, the name of the management package has *generally* been the second half of the resource provider namespace + name (e.g. Microsoft.Compute -> Compute, Microsoft.AppService -> AppService etc.). There are some services that, for historical reasons, have been bumped together (the resource type moved between namespaces etc.). Container services is one example.

While not front-and-center, the resource provider namespace and name *is* exposed to users in various ways (ranging from error messages, resource provider registration, arm templates, call quotas etc.). 

@JonathanGiles, is the container registry management operations really in the compute package for java? It is not for Python. And it doesn't seem to be for other languages.

**Comment by adrianhall** [comment]
There is a general rule that repeated groups can be collapsed.  i.e. it would be `com.azure.management.compute` not `com.azure.management.compute.compute` - although it would be `com.azure.management.compute.virtualmachines`, for example.

**Comment by JonathanGiles** [comment]
@johanste Container registry for java is under com.microsoft.azure.management.containerregistry. I wasn't trying to match track one so much as I was trying to fit in our guidelines where we have a group before the service. Do you have a suggestion on how this should change to match your expectations?

**Comment by johanste** [comment]
I guess we will always have a naming problem whenever we pick a group name that is equal to a provider name (unless it is a group of one). In this case, the proposed group name 'compute' is the same as the resource provider name in 'microsoft.compute'.

By the way, I assume we are not trying to rejigger/refactor what ships in each package (e.g. split what was previously a single package with vm and vmss (and managed disks and extensions and...) into separate packages, correct?

**Comment by johanste** [comment]
..and to try to actually answer the question, I'd try to find a group name that is not a provider name in order to avoid the naming conflicts. In other words, `compute` would not be the group name.

**Comment by weidongxu-microsoft** [comment]
@JonathanGiles 
Thanks very much for the much improved schema. I think it is great (same uncertainty on compute and monitor). We will not do any release until a consensus is reached.

@johanste
For previous mgmt Java SDK, the namespace mostly follow names in service of [swagger spec](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/).

Currently we do not plan to split those previously in one package to multiple ones. E.g., interface `com.azure.management.compute.VirtualMachine` and `com.azure.management.compute.VirtualMachineScaleSet`.

If we are not certain about compute and container, would we try to ask the opinions of service owners, about how close Compute RP relates to ContainerService RP, and what other services might be grouped into compute namespace?

BTW, would the grouping on portal be a bit of hint?

![image](https://user-images.githubusercontent.com/53292327/80931050-1442b080-8dea-11ea-91e3-21058c0760d1.png)

**Comment by yungezz** [comment]
thanks all for the review comments. We need agree on a general guideline on namespace for mgmt to follow, so in future any new namespace adding will follow same guideline without confusion. Azure services categories are at here https://azure.microsoft.com/en-us/services also, which is aligning with portal showed by @weidongxu-microsoft . I suggest mgmt namespaces use `category`  here as namespace group. For `aks` and `acs` or any container related services such as `spring cloud`, I prefer put them under `container` group for easy discovery. `monitor` is under `devops` and 'management and governance`, I prefer `management and governance since `devops` is mainly related to azure devops related services. @johanste  @JonathanGiles  let us know your feedback.

**Comment by Petermarcu** [comment]
When the groups were initially defined, portal was one of the inputs but if you notice, lots of services show in lots of places and in some cases they were in weird places. Things have changed groups there many times. The goal is to use the groups already defined and agree to add more on a case by case basis but management and data planes shouldn't differ by anything other than the management part of the namespace.

**Comment by JonathanGiles** [comment]
To go back to Johan's comments, more concretely I was trying to find a home for the management libraries such that they would be grouped in one of the pre-defined groups that we put in our guidelines [here](https://azure.github.io/azure-sdk/general_design.html#general-namespaces-mgmt), and reproduced below:

Namespace Group | Functional Area
-- | --
appmodel | Application models, such as Functions or App Frameworks
compute | Virtual machines, containers, and other compute services
integration | Integration services (such as Logic Apps)
management | Management services (such as Cost Analytics)
networking | Services such as VPN, WAN, and Networking

Perhaps we should schedule an arch board topic to discuss the names that we have specified there and do another round of discussion following that?

**Comment by Petermarcu** [comment]
One open conversation is that there appears to be a lot of overlap in "management" operations within the data plane and management planes. Service like SignalR, ServiceBus, and Synapse as examples all have management operations on them. Some are related to ARM resources and some are related to management of workflows and other resources that are not ARM. We should consider  whether the naming for ARM libraries should be grouped into something that clearly scopes it to Azure Resource Management. Azure.Resources.Management or Azure.ARM?

**Comment by kyle-patterson** [comment]
Scheduled a review for 5/20.

**Comment by RodgeFu** [comment]
Would the general guideline on namespace for mgmt apply to all mgmt SDK? like in python SDK, we are using namespace as below. does it mean we also should change to the <Azure>.management.<group>.<service> format in track2 SDK for consistency? thanks.
- azure.mgmt.compute
- azure.mgmt.network
- azure.mgmt.resource
- azure.mgmt.storage
- azure.mgmt.appconfiguration
- azure.mgmt.monitor
- azure.mgmt.eventhub
- azure.mgmt.keyvault

**Comment by yungezz** [comment]
The [guideline](https://azure.github.io/azure-sdk/general_design.html#general-namespaces-mgmt) should be language neutral. hi @johanste could you pls help to look at @RodgeFu 's question above?

**Comment by johanste** [comment]
We always allow per-language override for general guidance. Unless you have a really good reason to change the package names (I'm not aware of any reasons that outweigh the pain of having duplicate packages), we should keep the same names as before.

**Comment by schaabs** [comment]
does it make sense to group the AuthZ / AuthN resources under `identity` rather than `security`?

~~~
com.azure.management.identity.rbac
com.azure.management.identity.msi
com.azure.management.identity.authorization
~~~

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/553aa1ff-0400-96d0-3325-f1ea9aeda3a2

### Notes

Q: Each RP is packaged separately, so the package name and namespace will align. Is this the target design?
- This varies by language, but in general one-to-one is preferred

Q: What about using the categorization available in the portal?
- Problem with this is marketing terms may be under multiple categories, and is not a tree structure
- In addition, these are usually closer to technology names than developer names
- They could be used as inspiration, but not the primary model

Q: Could we think about the group name as 'ARM'?
- Would be very clear that this is the ARM library
- Q: Do people know what ARM means? Does this resonate with users?
  - Yes, it's been ARM, MGMT, Management
  - But ARM is an acronym, and may change
- **Proposal**: ResourceManager as a group, ex. "Azure.ResourceManager.Resources" ?

Q: Could we use version numbers in namespaces?
- This was done explicitly to support multi-cloud versioning

**Topic**: 'Azure' as a root namespace

Q: Should 'azure' be reserved for libraries with SxS compatibility?
- Discoverability is a key issue for client libraries supporting azure services
- What about 'AzureApi' as a root for management plane generated code?

**Topic**: 'Generated' namespace addition
- Every leaf would have .generated, ex. Azure.ResourceManager.Compute.Generated...
- This frees up the 'good' namespace for the convenience layer
- This indicates there is a different fragility with respect to breaking changes
  - This doesn't address the customer problem that there are breaking changes
- This would be very clunky or weird in C++
- What about '.Protocol' instead?

**Topic**: Azure.<>..Management, as a leaf space
- Would discoverability be better?
- Patterns between libraries are so different, this may cause higher confusion (especially with higher discoverability)

**Topic** Semantic versioning in namespaces/package names
- It's important to have this information within the libraries so that users can map versions
- Depending on the package manager, if there's no metadata then the versioning must be incorporated somehow

**Follow-ups**: Final proposal should include:
[Note, this applies to namespaces, not package names. Package names could be kept where best used, ie python and JS could stay unchanged]

- Data plane and management plane should be consistent in usage of groups.

- "management" is too ambiguous. What about "Azure.**ResourceManagement**.<group>..."
  - When there is no corresponding data plane library, place under "Azure.ResourceManagement...", such as Azure.ResourceManagement.CostAnalysis

- Should be something on the leaf of the namespace to denote that the code is generated, such as "Protocol", "Api", "Generated", "Rest", "Direct", "LowLevel", "Base"

- versioning should follow the same guidelines as for data plane APIs (ie, use semantic versioning where we currently use semantic versioning)

**Comment by weidongxu-microsoft** [comment]
Thanks @kyle-patterson for the meeting notes and recording. Very helpful.

The current namespace requested by Java SDK is on Fluent premium, which is hand-written code over generated code.

The hand-written code is meant to mitigate breaking change, as well as providing convenience layer. However it is not likely possible to guarantee no breaking change across versions, even on hand-written code. E.g., compute deprecated Low Priority VM a few months ago, and added Spot VM partly to replace it. When Low Priority VM be eventually removed from RP, this will be a breaking change that not able to be mitigated.
