### ISSUE TITLE
Board Review: SignalR

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#1287]
The Basics

* Service team responsible for the client library: adparch
* Link to documentation describing the service: 
* Contact email (if service team, provide PM and Dev Lead): @bterlson (ADP contact), @davidfowl (PM stand-in), @vicancy (Dev)

## About this client library

* Name of the client library: SignalR (name is presently up for debate)
* Languages for this review: TS, C#, Java, Python
* Link to the service REST APIs: [here](https://github.com/Azure/azure-signalr-vnext-features/blob/master/serverless-websocket/specs/ws.swagger.json)

### .NET
*  [apiview](https://apiview.dev/Assemblies/Review/9870950a3ce7405f98156212e7318419)
* @KrzysztofCwalina  please share champion scenarios

### Java
* [apiview](https://apiview.dev/Assemblies/Review/5f461ab6cd16413bbab70e4138956f8a)

### Python
* TBD (@johanste please share when you get a chance)

### TypeScript

* [api.md](https://github.com/Azure/azure-sdk-for-js/pull/8652/files#diff-62dfd9a31f6e34b54fac79d76e0e24aa)

## Champion Scenarios

| Scenario | C# | JS/TS | Java | Python |
|----------|----|-------|------|--------|
| Broadcast text messages to hubs and groups (Nearly everyone using this library will be doing this) | [C# Link](https://github.com/KrzysztofCwalina/azure-sdk-for-net/blob/signalr/sdk/signalr/Azure.Messaging.SignalR/samples/Sample1_Broadcast.md) | [JS/TS Link](https://github.com/Azure/azure-sdk-for-js/pull/8652/files#diff-419247096c6b1f492e967ce83c62a4e1) | [Java Link](https://github.com/JonathanGiles/azure-sdk-for-java/blob/signalr/sdk/signalr/azure-messaging-signalr/src/samples/java/com/azure/messaging/signalr/BroadcastingSample.java) | Python Link | 
| Broadcast binary messages to hubs and groups (Much less common (maybe < 10%)) | C# Link | [JS/TS Link](https://github.com/Azure/azure-sdk-for-js/pull/8652/files#diff-419247096c6b1f492e967ce83c62a4e1) | [Java Link](https://github.com/JonathanGiles/azure-sdk-for-java/blob/signalr/sdk/signalr/azure-messaging-signalr/src/samples/java/com/azure/messaging/signalr/BroadcastingSample.java) | Python Link | 
| Sending messages to specific users and connections (Maybe 50% of users will do this) | [C# Link](https://github.com/KrzysztofCwalina/azure-sdk-for-net/blob/signalr/sdk/signalr/Azure.Messaging.SignalR/samples/Sample2_SendToUsers.md) | [JS/TS Link](https://github.com/Azure/azure-sdk-for-js/pull/8652/files#diff-646a26f82f3bddf5e4cf2e0f49a3c934) | [Java Link](https://github.com/JonathanGiles/azure-sdk-for-java/blob/signalr/sdk/signalr/azure-messaging-signalr/src/samples/java/com/azure/messaging/signalr/DirectMessageSample.java) | Python Link | 
|  Add and removing users and connections to groups (Maybe 50% of users will do this) | [C# Link](https://github.com/KrzysztofCwalina/azure-sdk-for-net/blob/signalr/sdk/signalr/Azure.Messaging.SignalR/samples/Sample3_ManageUsersAndConnections.md) | [JS/TS Link](https://github.com/Azure/azure-sdk-for-js/pull/8652/files#diff-8fcb6b61014fd2786d003cba3ed7dfbe) | [Java Link](https://github.com/JonathanGiles/azure-sdk-for-java/blob/signalr/sdk/signalr/azure-messaging-signalr/src/samples/java/com/azure/messaging/signalr/ManagingGroupsSample.java) | Python Link |

**Comment by JonathanGiles** [comment]
I've introduced a table into the original issue description and added Java scenarios alongside the TypeScript samples.

**Comment by kyle-patterson** [comment]
Scheduled for 5/11

**Comment by davidfowl** [comment]
The C# link points to this issue.

**Comment by KrzysztofCwalina** [comment]
@davidfowl, which link?

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/6736a1ff-0400-96d0-5767-f1ea93fcbec9

Link to python apiview: https://apiview.dev/Assemblies/Review/1d589913f09d432d8010f6b2848ce4bb

### Namespace:
- SignalR management would be best namespace, but that implies ARM operations (which aren't part of this library)
- From a developer perspective, it needs to be clear where SignalR is meant to be used (server vs client)

Q: Can SignalR dump messages in a serverless way?
- Not today

### Broadcast vs SendToAll:
- Broadcast doesn't fit with "send" commands in intellisense, as SendToAll does
- SignalR currently documents with "broadcast"
- SendToAll could be confusing if it doesn't send to all on the hub client
- **Recommendation**: Use 'SendToAll' on the group client

### GroupClient vs Hub vs Root
- Initial confusion over separation of capabilities and mapping of concepts to use cases

Q: How frequent would the group operations be combined?
- Typical use case is on-demand group control, but it's typically not a cached object

Two-client approach feels more natural to use, although it feels odd making a recommendation based on Intellisense functions
- Potential downside, it may be confusing differentiating common functions (such as send to hub or send to group)
-- SignalR service was designed for this, in the form of message pipelining

**Recommendation**: use the two-client approach

### Client naming
Q: SignalRClient vs HubClient?
- Should we be using service names in the APIs?
- SignalRClient does point to a known azure service, but also conflicts with other signal r clients already available
- HubClient could be confused with other hubs, such as IoT hub
- Additional point of confusion, traditional concept of 'client' doesn't align with SignalR's concept of 'client'

Q: HubClient is the top level, and group can only be retrieved from a HubClient
- If GroupClient cannot be directly instantiated, it shouldn't have 'Client' in the name (per the guidelines)
- python requires child clients to be directly instantiable
- **FOLLOW UP**: Should group client be directly instantiable?

### Client behavior

- HubClient excluded options should be excludedIDs

Q: has vs exists?
- General guidelines expect the suffix 'exists'

Q: hasConnection returns a promise<boolean>, is this the correct approach?
- Javascript works fine returning T if T is an object; but if T is a primitive, it either must be boxed or the response must return the primitive
- A proposed change is to never return Response<T> if T isn't under the library's control
- Precedent from javascript for storage does allow promise<boolean>
- python always returns T and requires users to write code if they need to retrieve the response code

Questions on exposing "resource addressing" properties, such as the hubclient endpoint and name
- Storage does this (exposes in the URI properties), but KeyVault does not
- Does GroupClient even have a URI to give?
-- No, it has an identifier that isn't a URI
- **Recommendation** make Endpoint private, can expose later if feedback requests it

Q: What should TTL be called (they are ints) when adding a user?
- Java uses TimeToLive and uses the Duration type
- Queues called this a VisibilityTimeout; other services use "ExpiresIn"
- Could the service take a UTC timestamp, rather than ints?
-- The service side cannot be specific enough for this
- Be careful not to be affected by retries


Q: Broadcast and similar APIs refer to 'message' for string; in the REST API it's always referred to as 'data'
- The conceptual model is users are sending 'messages,' it is a smaller use case to send binary data
- Does 'data' imply to users that they need encoding (an 'envelope')?
- python uses 'data' as it could be bytes, or streams
- **FOLLOW UP**: look at examples from other services and see if there's already a convention

Q: Is it 'closeConnection' or 'removeConnection'?
- HubClient closes the connection, but GroupClient removes it (and cannot close it)

Q: Do the credentials only take sharedkey or will they take AAD?
- Right now only sharedkey, but take a look at what storage does for credentials
