### ISSUE TITLE
Board Review: DefaultAzureCredential (part of Identity)

### ISSUE THREAD

**Issue by jonathandturner** [Azure/azure-sdk#1307]
## The Basics

* Service team responsible for the client library: Identity
* Link to documentation describing the service: https://gist.github.com/jonathandturner/fa3036000201f445d0a950708d7dd11f
* Contact email (if service team, provide PM and Dev Lead): @schaabs @jonathandturner 

## About this client library

* Name of the client library: DefaultAzureCredential
* Languages for this review: JavaScript, Java, .NET, Python
* Link to the service REST APIs: No REST APIs

## Artifacts required (per language)

No new APIs are added, rather we update the internal logic for how DefaultAzureCredential is ordered and how the user can define a settings file to configure the application and ready it for deployment.

### TypeScript

The settings file shape:

```ts
interface CredentialSettings { 
  [key: string]: any, 
} 

interface EnvironmentSettings { 
  includeTypes?: string[], 
  excludeTypes?: string[],
  includeCredentials?: string[], 
  excludeCredentials?: string[], 

  settings: { 
    [credential: string]: CredentialSettings 
  }, 
} 
interface Settings { 
  development?: EnvironmentSettings 
  testing?: EnvironmentSettings, 
  production?: EnvironmentSettings, 

  //Additional user-defined environments 
  [environment: string]: EnvironmentSettings, 
}
```

## Champion Scenarios

* Champion Scenario 1: Deploying use DefaultAzureCredential
  * User develops app using DefaultAzureCredential
  * User creates (or copies) a project configuration file into project
  * User pushes project to production

Estimated percentage of developers: most (70+%)

Code Sample:

```
# build and run app
> set AZURE_APP_CONFIGURATION = "production"
# build and run app, now uses production settings
```

**Comment by kyle-patterson** [comment]
Scheduled for 5/12

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/b12ca1ff-0400-96d0-b627-f1ea94a497b2

### Notes
Q: Concerns about introducing a settings file - is it heavy-handed for what we're trying to do?
- If there were some standard azure configuration file, this would go there
-- This is a problem for .NET, in which core libraries cannot read from a standard file
- This file could be whatever file is idiomatic to the language (such as ASP.NET configuration file for .NET)
- Semantics would have to be identical
- Could move abstraction to core
- Python doesn't have a default implementation for this; there is a default abstraction that only reads environment variables
- Also consider modes of failure: difficulties opening file, etc

Q: Could we use a design similar to Azure Identity? (ie, base abstraction approach)
- There would need to be a default implementation
- For .NET, the further from idiomatic (ASP.NET) implementation would be more painful for users

Q: What about AppConfig?
- This would require users to put config in two different locations
-- This may not be all that fatal (at least within javascript); it's in the implementation, or how they work together

Q: What in the requirements would actually change the previous work of configuration systems?
- There were concerns about file-based configuration in the past; but we may be past the point where a configuration based on ENV variables may be more complicated than a heirarchy
- There are alternatives to the file approach, which will be discussed below

Q: What about flat environment variables, not demarcating "Production" vs "Staging"
- This avoids configuration files

Q: What if environment variables are the default, and there's an abstraction users could connect to and use a config of some sort?
- python has implementations of the .env like javascript, and plugins for them already. stdlib has a reader, but this doesn't implement a std file.

Q: Are any customers asking for specific configuration files?
- No; but customers don't want to use environment variables or defaultazurecredential, they want confidence in the credential being used. 

Q: Could this be solved with a chained token credential, and a flag to distinguish them?
- We have the ability programmatically, but the default credential chains aren't public so this may be clunky
- This was done because it could clutter the namespace with credential chains that may not be used frequently or explicitly
- Don't forget that mobile/web may not have an env or filesystem in place
- Do customers want to lock down credentials between developer and production credentials?
-- The ExcludeCredentialTypes would cover this scenario

Q: Excluding could be a problem if DefaultAzureCredential is growing, this is no longer a seamless upgrade
- Allow may be easier than Exclusion for this
- Will users want to do more than allow/deny for credentials?

Q: Should credential types be public, and what are these implications?
- It seems strange referencing types that aren't included in the public API/documentation
- There is customer feedback asking for these types to be made public

Q: What about using flags/enums to explicitly allow the desired credentials?
- Would need a new options type of defaultazurecredential, meaning two option types that could modify the default
- 4 architects voted against

Q: What about "DeveloperCredential"
- Don't want to create a "chain of chains"

**Recommendation**: Let internal credentials bake as public in preview
**Recommendation**: Let users create chained credentials using credentials. These could be used as "allow lists"
**Recommendation**: Leave DefaultAzureCredential, continue adding exclude flags when adding to types to DAC, but promote custom chains as recommended pattern
**NOTE**: credentials in preview could go under some "experimental" separation to be clear that they're in preview


Example: 
var cred = new ChainCredential([ new MICred(), new AzureCliCred() ]);
cred = new ChainCred(DefaultAzureCredential.credentials.filter(c => c.name !== 'UnwantedCredential'))
