### ISSUE TITLE
Board Review: Storage STG73 features

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk#1347]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

** Before submitting, ensure you adjust the title of the issue appropriately **

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will generally be reviewed together.  In expansive libraries, we will pair dynamic languages (Python, TypeScript) together, and strongly typed languages (C#, Java) together in separate meetings.

## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service:
* Contact email (if service team, provide PM and Dev Lead):
kasobol@microsoft.com
amishra@microsoft.com

## About this client library

* Name of the client library: Storage
* Languages for this review: .NET
* Link to the service REST APIs: https://github.com/Azure/azure-rest-api-specs/tree/storage-dataplane-preview/specification/storage/data-plane

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

* Upload DLL to [apiview](https://apiview.azurewebsites.net).  Link:
Azure.Storage.Blobs https://apiview.dev/Assemblies/Review/a17b6175b93847db83a99c7fcfeca9ab?diffRevisionId=1a29f4ce0b094e8fb67c48a602d2b4e6
Azure.Storage.Common https://apiview.dev/Assemblies/Review/829214500ec64e57a2a70f862916aa4f?diffRevisionId=6295bfa5fc4c4641819b6f5083073bd3
Azure.Storage.Files.DataLake https://apiview.dev/Assemblies/Review/2cdf1e8e47874f8681106b24a9002bdf?diffRevisionId=2a2d3cd11460478cb21ea91b3f8bd010
Azure.Storage.Files.Shares https://apiview.dev/Assemblies/Review/ba13763bc4ed43a5a49b7a23cb53fc07?diffRevisionId=76a99ed59cb346efac44b072c0394ad6
Azure.Storage.Queues
https://apiview.dev/Assemblies/Review/1f99f1c9c700432c8215bedebce9f1af?diffRevisionId=f490b3284b694f9da149677a8daf6c45

Additionally PR for new package Azure.Storage.Blobs.Changefeed: https://github.com/Azure/azure-sdk-for-net/pull/11692
APIView of changefeed: https://apiview.dev/Assemblies/Review/85046278a8764a02a11d65ab219b91ae

### Java
azure-storage-blob [long running](https://apiview.dev/Assemblies/Review/9486dbfb196740c0a4d810382b78c3ef?diffRevisionId=95c0cc1e7a014e31882f98d87d6954f0), [based on latest GA](https://apiview.dev/Assemblies/Review/78bcb7fc04fc46c79b264b5729da1a6a)
azure-storage-blob-cryptography [long running](https://apiview.dev/Assemblies/Review/01d3e131d9424426aa139badbb1c2117?diffRevisionId=32eca737e5464f22b24824ffec0ed97b), [based on latest GA](https://apiview.dev/Assemblies/Review/8e823951dff14ed49a69717da6b6c1ec)
azure-storage-blob-changefeed
[new package](https://apiview.dev/Assemblies/Review/80ea55df52a641069bebd17a6db585bc)
azure-storage-common [long running](https://apiview.dev/Assemblies/Review/494e9fa148db419ead4f0ee78674d384?diffRevisionId=73d2009825164696a2197b28c6ecf9b8), [based on latest GA](https://apiview.dev/Assemblies/Review/f5a3037e76a04c028187cdcb485f713a)
azure-storage-file-datalake [long running](https://apiview.dev/Assemblies/Review/8783725958ed453383d7a7cebf2fbed9?diffRevisionId=84231436fb104845aedc01f06d97bd27), [based on latest GA](https://apiview.dev/Assemblies/Review/91cdc86f59b2420797f05e33942d7dda)
azure-storage-file-share [long running](https://apiview.dev/Assemblies/Review/c4ca81d4288d46f1b148ae033ddcf9c9?diffRevisionId=909397cce2c44e0d8877eb9bc17fa3a2), [based on latest GA](https://apiview.dev/Assemblies/Review/a4c8c25efc514058afda32158b870cf5)
azure-storage-blob-batch [long running](https://apiview.dev/Assemblies/Review/1c9dc39e36b54243b1010b80c57cad41?diffRevisionId=3c931e288dc646f5a2c7e4bc92c3e649), [based on latest GA](https://apiview.dev/Assemblies/Review/49ab02ea85a84da39ab49f3dda53ce27)

### Python
Stubgen for all features:
https://github.com/xiafu-msft/azure-sdk-for-python/pull/3/files

APIView per package
azure-storage-file-share:
https://apiview.dev/Assemblies/Review/27d251c31d924249a26cb294cc62eb8c?diffRevisionId=48a51f74be7d447f836b42e2f6067e4e#azure.storage.fileshare.ShareClient

azure-storage-blob:
https://apiview.dev/Assemblies/Review/5f53b3f2e2e8453eb4cd81cb48d16620?diffRevisionId=7eeef5934e5e4d2682bf5e180bfc7061

azure-storage-file-datalake:
https://apiview.dev/Assemblies/Review/b09bb14da49e4f9c82787cd62f90fada?diffRevisionId=05426f402f484eb3ac5c0ef7e328e5ff

azure-storage-blob-changefeed:
https://apiview.dev/Assemblies/Review/14368856308144c0a07f79da963aabc7#azure.storage.blob.changefeed.ChangeFeedClient

### JavaScript
per feature:
Blob versioning: https://github.com/Azure/azure-sdk-for-js/pull/7886
Quick Query: https://github.com/Azure/azure-sdk-for-js/pull/9112
Change Feed: https://github.com/Azure/azure-sdk-for-js/pull/9532/files#diff-dd305e6973a778934af8460c60bc7a3a

per pacakage
storage-blob: 
https://github.com/Azure/azure-sdk-for-js/pull/9532/files#diff-676a73311cb02df3d5c777d7e678ddfc

storage-file-datalake: 
https://github.com/Azure/azure-sdk-for-js/pull/9532/files#diff-d11c95aee3e218ade7c296fbc2cbeced

storage-file-share: 
https://github.com/Azure/azure-sdk-for-js/pull/9532/files#diff-b72df24b3c4664e3bd58c593aa3cf7a7

**Comment by amishra-dev** [comment]
@KrzysztofCwalina / @JonathanGiles / @johanste  / @tg-msft / @annatisch Gentle reminder.

**Comment by annatisch** [comment]
Thanks @amishra-dev - I've left some questions/comments, however it seems that the generated API views for Python need updating - as they don't reflect some of the changes we made last week. :)

**Comment by KrzysztofCwalina** [comment]
I reviewed the APIs and added comments.

**Comment by bterlson** [comment]
I have accepted/reviewed everything, though there are some open questions/concerns that need to be worked through as yet.

**Comment by tg-msft** [comment]
I've added comments and they've all either been addressed or are being addressed.  I'm good to ship a Preview for .NET.

**Comment by annatisch** [comment]
Almost all the comments for Python have been/are being addressed. So I'm confident we can get the preview out next week.
One of the areas that we focused on is quick query, and I have a PR open with our proposal that I'm working through reviewing with @xiafu-msft 
https://github.com/Azure/azure-sdk-for-python/pull/11991

In summary we wish to make the query experience align with common patterns used by existing Python CSV tools, to maximize compatibility. The key changes are:
- Input/output serialization.
  I have renamed these parameters to `blob_format` and `output_format` as I felt the concept of "input" was confusing. The types accepted here have been remodeled into two options: CSVDialect (that uses the API of the Python csv.Dialect class) and DelimitedJSON.
- I have moved the headers_present field into a standalone parameter, as it turns out the service only uses it for input formatting anyway. I have renamed to "has_header" to be consistent with Python csv lib.
- I am using the error handling currently used for Python encoding, which means you can specify three options:
  - 'strict' (the default), which raises on any error
  - 'ignore', which ignores non-fatal errors, fatal errors are still raised
  - callable(error) which allows for custom handling, with raising or supressing of any error
- I have added an iterable response function so users can iterate over the records in the streamed response. This behaviour is more consistent with how records are consumed in other Python csv readers.

**Comment by JonathanGiles** [comment]
I completed another pass through the Java API changes and nothing jumps out at me, so for Java I'm ok with this preview going out.

**Comment by annatisch** [comment]
I believe all the comments for Python have now been addressed, so we should be good to go to preview.

**Comment by kasobol-msft** [comment]
The API Views has been updated to reflect latest master (merge of stg73 and few additional features that were contributed after).

@kyle-patterson We'd like to request final review before GA next week. Could you please schedule that?

FYI @kurtzeborn @amishra-dev

**Comment by lilyjma** [comment]
scheduled for 7/27

**Comment by JonathanGiles** [comment]
I've left some minor Java feedback that should be reviewed preferably in advance of this arch board. Thanks!

**Comment by lilyjma** [comment]
[MS Internal Only] [video ](url)

Action Items: @kasobol-msft 

**Java**

`BlobChangefeedClientBuilder`
- reference `BlobBatchBuilder`; okay with current approach if same as `BlobBatchBuilder`

`BlobBeginCopyOptions`
- Java: `setSealDestination`, `isSealDestination`
- C# `shouldSealDestination` (Brian likes this for JS too)

**JS**

`BlobDownloadResponseParsed`, `objectReplicationSourceProperties` type
- okay to leave as is if Storage team thinks it's good 

**C#**

`namespace Azure.Storage.Blobs.ChangeFeed.Models{}`
- put models in same namespace instead of creating new namespace

`DataLakeQueryJsonTextConfiguration: DataLakeQueryTextConfiguration{}`
- adding factory methods and mentioning derived types in doc comments 

`BlobQueryTextConfiguration{}`
- change to Options 

`BlobTagItem{}`
- make it a struct and name it `BlobId` (work on naming further)

`BlobContainerStates{}`
- keep for now since will be adding more later 

`public virtual Response<IDictonary<string,string>> GetTags()`
- sync offline with SDK team 

**Python**

In `start_copy_from_url()`
- use `seal_destination_blob`

`upload_blob()`
- watch for email on `if_tags` naming

datalake: `query_expression` in `query_file()`
- start email thread on this; useful to see it in sample

`DataLikeFileQueryError`
- follow up with Johan: slightly odd to get exception passed in through callback 


**APPROVED for release!**
