### ISSUE TITLE
Spring Samples need to use Spring bom ( Bill of Material) in its pom.

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk#1366]
**Problem Statement**: Current engineering system do not allow bom files to use in our pom but Spring sample application needs it.

**Where is this needed**

Spring sample application is just like a sample in a SDK but it is an application for example it could be a web site. 

We need to document a Spring application from user's point of view i.e. how user would write a spring application.

Following are two example of how  bom files are used in sample application.

1. User's pom.xml : Normally it including spring bom like below 
 
            <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-spring-boot-bom</artifactId>
                <version>2.3.2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

Here is a sample in our repo
https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-samples/pom.xml#L9

2.User's  pom.xml: It also include azure bom like below

            <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-spring-boot-bom</artifactId>
                <version>2.3.2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

Here is a sample in our repo
https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-samples/pom.xml#L67

**Issue at hand** :

1. Currently we do not allow bom to be part of a pom file. 
 This works fine for a SDK point of view. But from Spring sample point of view, it is convention to use spring provided bom files.

**What do we want to achieve** : 
Provide  a common/generic way to write samples which might use bom. 

**Acceptance Criteria** :
This should be generic so that it would provide a way forward for other languages also.

**Comment by hemanttanwar** [comment]
Please provide input @JonathanGiles  @mitchdenny  @JimSuplizio @jialindai @saragluna

**Comment by mitchdenny** [comment]
Jim and I caught up and had a bit more of a conversation about this yesterday and we still aren't even aligned from an EngSys perspective. So what I'm putting out here is really just my own thoughts on this just to try and get the conversation started.

I'll start with a few facts:

1. Samples are just documentation.
2. Samples are a bit different to documentation in that customers "run it".
3. Samples should therefore be validated that they build and run.
4. We already have samples that we build and run in the repo.
5. These are sample applications, so the mechanism we have to day won't work.
6. Samples are similar to smoke tests, not exactly the same.

With those facts in mind, I've got a few questions that might help us zero in on a solution:

1. How do customers find the samples?
2. What are the expectations when find the samples on master? Should they represent samples that work against the current _released_ set of packages, or the set of packages actually in the repository at that point in time.
3. Assuming the answer to (2) is current _released_ set of packages, what do we need to do to validate that they are correct? Is building against the current state of the repository even useful given that it doesn't do anything to prove that they are usable as samples _right now_ by customers.
4. If we decide to build/validate samples against the current released packages what are the risks of a upcoming change breaking the sample and us not detecting it.

I've got my own answers/thoughts around these:

2. If a customer finds a sample on master then they should work against the currently released set of packages.
3 & 4. Given (2) above we don't need to validate against the current packages in the repo, and even after we publish new packages, those samples will continue to work due to versioning. Samples would still be built and run as part of the pipeline, but they are validating that the _sample_ works with the released packages, not the current repo state. Basically the Spring CI pipeline will validate two different artifacts (packages & samples) which move at a separate cadence.

The question then is how would we plug in this sample build/validation process. What does the Azure Spring Boot team do today to validate the samples are correct?

**Comment by jialindai** [comment]
Sorry for the delayed response.

1. How do customers find the samples?

We have reference from spring.io web site to the samples: https://spring.io/projects/spring-cloud-azure#samples
Once we have moving spring modules into sdk repo, we will also update the above reference on spring.io. Because the way we put samples in sdk repo, the reference page may need more change other than reference to a new URL.

2. What are the expectations when find the samples on master? Should they represent samples that work against the current released set of packages, or the set of packages actually in the repository at that point in time.

The samples should reference to the latest release version. (not the snapshot or dev build)

3. Assuming the answer to (2) is current released set of packages, what do we need to do to validate that they are correct? Is building against the current state of the repository even useful given that it doesn't do anything to prove that they are usable as samples right now by customers.

I think the sample is building against with released version instead of current state in master branch.

4. If we decide to build/validate samples against the current released packages what are the risks of a upcoming change breaking the sample and us not detecting it.

Currently we run samples manually during each release. A better approach is introducing automated tests for samples.

**Comment by Petermarcu** [comment]
Is the challenge building it every day or is the harder part running it?
