### ISSUE TITLE
During an attempted readme push, "Patch Does Not Apply" Error is thrown 

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#1399]
[Example Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=411438&view=logs&j=ad162c3a-eba8-5906-ed76-2979db4acf46&t=6c0b4c2a-c945-515e-77d0-465b6d0db7e1)

Error:
```
error: docs-ref-services/core-http-readme.md: patch does not apply
``` 

Need to resolve this. It seems to be coming due to conflicts of some sort? It's definitely not always happening. Need to repro locally to understand what is actually going wrong with the patch.

**Comment by scbedd** [comment]
It's not just readmes! An `increment version` PR actually hit [this issue](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=423197&view=logs&j=54843bda-187f-5bf8-8d32-6590d17c9f86&t=5252b167-66b6-57dd-0bc3-95ff4b3ac3e1&l=225). Thanks @JimSuplizio for raising that:

The proper resolution here is to clone down the `azure-sdk` fork, take action to resolve the conflict, and re-run the patch application.

In the meantime, we should make this a hard error.

**Comment by JimSuplizio** [comment]
@scbedd in the case of Java it was due to the some erroneous versions in a Spring library which ended up getting modified through the version update script for each library that was released as part of the PR. In this case it was Storage releasing X library and while the Spring dependency wasn't Storage, it was incorrect and each diff had the exact same file and exact same line. To be clear, this isn't supposed to happen but a SNAFU from multiple spring PRs going in at the same time caused it and Storage just paid the price.
