### ISSUE TITLE
Replace whitelist term for AllowList in java documentation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk#1443]
This is from a tool although not sure from where
Link in 
```
The definitive source for the dependency versions being used in all client libraries is published in a separate document that is generated from the azure-sdk-for-java code repository.
```
https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/dependency-whitelist.html

**Comment by JonathanGiles** [comment]
This report is generated from a tool called the [Maven Enforcer Whitelist Report Tool](https://github.com/JonathanGiles/whitelistgenerator) that I wrote. The linked HTML file is a file [located in our repository](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/dependency-whitelist.html) that reads in the generated json file, so that HTML file can be edited to correct the phrasing. If the filename is changed, references to it will need to be updated [here](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/index.html#L524) and [here](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/aggregate-reports.yml#L56).

**Comment by maririos** [comment]
Thanks for the information @JonathanGiles . I created issue https://github.com/Azure/azure-sdk-for-java/issues/12182 in Java repo.

**Comment by lfraleigh** [comment]
@JonathanGiles  - the linked issue was closed. Can this be closed too?
