### ISSUE TITLE
Board Review: Azure DigitalTwins for Typescript

### ISSUE THREAD

**Issue by zolvarga** [Azure/azure-sdk#1499]
## The Basics

* Responsible service team: Azure Digital Twins
* Link to documentation describing the service:
https://github.com/Azure/azure-digital-twins/blob/private-preview/Documentation/overview.md
* API surface: https://github.com/zolvarga/azure-sdk-for-js/blob/digitaltwins/sdk/digitaltwins/digitaltwins/review/digitaltwins.api.md
* Product Manager contact email: Elena.Horton@microsoft.com (elhorton)
* Dev Lead contact email: Jelani.Brandon@microsoft.com (jebrando)
 

## About this client library

* Name of the client library: @azure/digitaltwins
* Languages for this review: Typescript
* Link to the service REST APIs: https://msazure.visualstudio.com/One/_git/Azure-IoT-DigitalTwins-Main?path=%2Fproducts%2Fswagger%2Fexternal-data-plane%2Fpreview%2F2020-05-31-preview

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### TypeScript

* Upload output of api-extractor as a Draft PR.  Link to PR:
https://github.com/Azure/azure-sdk-for-js/pull/9787
* Link to samples for champion scenarios:
https://github.com/Azure/azure-sdk-for-js/tree/digitaltwins/sdk/digitaltwins/digitaltwins/samples/Readme.md

### Manage model lifecycle
Models represent some physical or logical entity, such as an IoT device, a room it is in, or a building that room is in. They are the cornerstone of digital twins. Each type of entity should be modeled using the DTDL schema. Once a schema is documented in the service, it can be known to other clients so when a digital twin is loaded, a program unfamiliar with that digital twin could interact with it in a dynamic way (e.g. UI created from a model to enable an operator to interact with the digital twin).

Note: this API is only available for bulk creation at this time. When multiple models are included, the service will validate any internal references and reject the request (think transaction) if the validation fails. Without that validation, one would need to create all the models in a specific order to avoid bad references.

- Create models in bulk
- List models
- Decommission a model
- Delete a model

### Digital twins
Digital Twins are the entities in ADT that represent physical or logical devices. They can be created, updated, read, and deleted.

- CRUD
- Query for digital twins

### Relationships
Based on the models applied to a digital twin, it can have relationships to other digital twins. Those relationships are managed independent of the digital twin (they aren't properties directly on the twin), and are 1-way (that is, a relationship created from A->B only appears on A and not on B).

- Link a digital twins to another via a relationship
- List relationships on a digital twin
- List incoming relationships (made by other digital twins targeting this one)
- Delete a relationship

### Telemetry
Digital twins that aren't physical devices may need telemetry sent on their behalf. The service SDK provides an avenue for that.

- Publish telemetry for a digital twin, or a component on a digital twin

### Event routes
An event route lets you send event data from digital twins in Azure Digital Twins to custom-defined endpoints in your subscriptions. Three Azure services are currently supported for endpoints: Event Hub, Event Grid, and Service Bus. Each of these Azure services can be connected to other services and acts as the middleman, sending data along to final destinations such as TSI or Azure Maps for whatever processing you need.

- CRUD

**Comment by lilyjma** [comment]
1. Context: 
- C# API already released for public preview
- No fundamental diff b/t JS and .Net 
    - C# has a few helper classes for dealing with objects in json 

2. Client has a flat design: separate Client and Twins? 
- .Net has the flat design b/c small surface area
- nearing too many operations for a single client
    - may want to consider how much will be added in future and if need to split 
    - maybe a good idea to try this flat design first and change as feedback comes it

3. `
export interface DigitalTwinModelsAddOptionalParams extends coreHttp.RequestOptionsBase 
`
- prefers extend OperationOptions instead b/c
	- user will see red squiggly if pass in options that haven't been declared 
	- supports more new core HTTP pipeline things
- follow up with Jeff and Brian about this specifically related to AutoRest 


4. ` export type DigitalTwinModelsAddResponse = Array<ModelData> & {
    _response: coreHttp.HttpResponse & {
    }
}
`
- reflect more type info about ModelData 
- one option: if user knows what type should be, can provide optional generic type that user can provide that they expect (David for C# type as reference)
- can follow up with Brian on this
- `_response` can follow Storage pattern 

5. `
export interface DigitalTwinsAddHeaders {
    eTag: string;
}
`
- weak eTag; no support for it in C# yet 

6. `updateComponent(digitalTwinId: string, componentPath: string, componentPatch: any, ifMatch?: string): Promise<DigitalTwinsUpdateComponentResponse>;`
- need more precise type there 
- json patch makes more sense for this API  
- need to see helper for constructing patches in C# 
- follow up with Brian to help on figuring more precise type and a helper 

7. `export interface DigitalTwinsSendComponentTelemetryOptionalParams extends coreHttp.RequestOptionsBase {
    dtTimestamp?: string;
}`
- unclear what this is a timestamp _of_
- will make name more descriptive for GA release 
- in C#, just called timestamp (still unclear what timestamp of) 

8. `listModels(dependeciesFor?: string[], includeModelDefinition?: boolean, maxItemCount?: number): PagedAsyncIterableIterator<ModelData, DigitalTwinModelsListResponse>;`
- optionals could go into options bag 
- move anything ends in optional into options bag (ex: `upsertEventRoute`)

9. Line 45 `(enableUpdate=true)` in lifecycle sample 
- syntax maybe unclear 
    - it's creating a global binding for global update; undeclared variable assignment 
    - fix: extend OperationOptions, make interface, and move to optional 


10. `upsertEventRoute(eventRouteId: string, endpointName: string, filter?: string): Promise<RestResponse>;`
- better response to return? 

11. `updateComponent(digitalTwinId: string, componentPath: string, componentPatch: any, ifMatch?: string): Promise<DigitalTwinsUpdateComponentResponse>;`
- returns string in C#
- maybe add a type that wraps a string because it's hard to add to a string in the future 

12. Plan for java library: haven't begin working on library, on backlog 
- @elhorton Please follow up with us on this; we can't have gap b/t languages for GA
- Peter: we pushed back on exception with Java; allow C# to GA ahead of java, but not without Java having something approved first 

13. Python coming next. 

Action Items:
- Consider future operations to decide if need Client needs to be split
- @zolvarga to follow up on items above
- @KrzysztofCwalina to follow up on eTag support in C#

Nice work!

**Comment by lilyjma** [comment]
@zolvarga: is it okay to close this?

**Comment by zolvarga** [comment]
@lilyjma I think it is OK to close this. I addressed all the comments already.

**Comment by zolvarga** [comment]
All comments have been addressed.
