### ISSUE TITLE
Change Request: Default Values for Extensible Enums in C#

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk#1547]
Right now, we have no clear guidance on what should be the default value of the extensible enum type. For a hypothetical `ExEnum` struct, I see several possible options here:

1. Use `new ExEnum("None")` as a default value.
  - Pros:
    - Closer to the guidelines for regular enums.
    - `ExEnum.ToString()` produces reader-friendly result.
  - Cons:
    - Struct already has a default value, `default(ExEnum)`. It isn't obvious to the user how these two values are relative to each other.
    - During serialization, a field with value equal to `new ExEnum("None")` will not be serialized, but `ExEnum.ToString()` would return "None". This is a potential bug prone. Also, result of explicit cast to string isn't obvious.
    - Requires custom serialization logic.
    - If protocol adds explicit `"None"` value, serialization will be broken.
2. Use `default(ExEnum)` as default value.
  - Pros:
    - 1-1 mapping between `ExEnum` values and serialized JSON.
  - Cons:
    - Requires additional serialization logic so that `default(ExEnum)` value isn’t added to the writer.
    - It isn't expected for `ExEnum.ToString()` to return `null`, so we have to declare that `default(ExEnum).ToString()` returns `string.Empty`, and explicit conversion from `(string)null` will return `default(ExEnum)`
3. Use `Nullable<ExEnum>` as property/parameter type and null as default value.
  - Pros
    - `null` values are automatically handled by serializer
  - Cons
    - Breaking change for existing types
    - We still have to define what is `default(ExEnum)` and how is it different from null.
    - It isn’t clear what `default(ExEnum).ToString()` should return and how explicit conversion from/to string will work.
    - Additional memory consumption
    - Users will have to handle null property values.
4. Make `ExEnum` a class and use null as default value.
  - Pros
    - `null` values are automatically handled by serializer
    - `default(ExEnum)` is null, which resolves several problems of `Nullable<ExEnum>`
    - All pros of a class vs struct
  - Cons
    - Breaking change for existing types
    - Users will have to handle null property values.
    - Additional memory consumption.
    - All cons of a class vs struct.

I personally prefer option 2 over the others. In the email thread, @heaths have suggested option 2 with addition of `HasValue` property.

**Comment by MiYanni** [comment]
So, let's break this down. For any reference type in C#, the default is `null`. Right now, our class-based models have this logical default to them. However, when we make any struct type, how do we determine what is a logical default value? I'd extend this discussion to not be for enums only. Instead, any type (class or struct) should have distinct logical defaults *if it makes sense to*. Instead of simply clear guidance on *defaulting enums*, I'd rather have clear guidance on **defaulting any type**.

**Comment by AlexanderSher** [comment]
For any `struct S` its default value is `default(S)` which is equal to `new S()`. In C#, one can't have parameterless constructor for structs. When `new S()` is called, compiler emits [different IL](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.initobj).

**Comment by heaths** [comment]
But the default value of an initialized struct isn't what's important - what's important is what the server wants. structs and enums are both value types, and in many - but not all - cases, the server probably wants undefined as the default (no value). Nothing you create as the default value for a struct will satisfy that, so the property must be a nullable struct or enum.

This also assumes that the default of an enum (whatever string 0 equates to) is also valid, which in those cases the server wants undefined, it's not.

So you really can't make the claim that extensible enums require some default. Whether using structs or enums, it all comes down to what the service requires.

Extensible enums solve problems enums can't. If .NET supported unions we wouldn't have this problem to discuss.

**Comment by MiYanni** [comment]
@heaths Services can define **server-side** defaults in swagger. It uses the `"default":` key. Here is an example from storage, indicating the server-side default for an enum: https://github.com/Azure/azure-rest-api-specs/blob/b3446f62368c3f4082c59a74fae265f25f851248/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L1879

This has a completely different interpretation for a generator than a client-side default. When that is written in the swagger, what it means is, "If the value isn't sent on the wire, the service will assume this." We currently do not use this value in the new generator, as it doesn't give us something actionable to generate. Other generators in the past may have integrated the information into documentation or used it in some other way.

In this discussion, I believe we are only talking about **client-side** defaults. The difference is, we send client-side defaults 'on the wire'. Server-side defaults, currently, have no functional purpose as it is just information on what 'omitted on the wire' means.

**Comment by AlexanderSher** [comment]
Users don't interact with server directly, they use our API, so how our types are translated into server requests is implementation detail and shouldn't be a user concern. Specifically, if we have a method with optional parameter:
```cs
ValueTask SetSomethingAsync(Model m, ExEnum e = default, CancellationToken ct = default)
```
user shouldn't care about picking up the value for `ExEnum` that server considers default. User should pass `default(ExEnum)`  (or `null` in option 3) and that should be enough.

**Comment by MiYanni** [comment]
@AlexanderSher There are a few non-obvious issues with nullability/defaults. I've documented it here with a proposal on a solution: https://gist.github.com/MiYanni/371a039a5035c43f8d0512b1c12f7449

To summarize, `null` right now represents `omitted` on both requests and responses. This causes issues if `null` has significance to the service. Meaning, it represents a particular state for the entity. Continuing to use `null` (or default for a struct) to be even more 'mysterious' makes it even more confusing for round-tripping. I create an entity, using your example, as `ExEnum e = default`, what is the developer to expect when they do a GET on that entity? Do they care what the value is? To my point in the GIST I linked, I'd rather them be intentional about providing particular values so they get expected outcomes. This can be especially confusing in ARM, as you're literally trying to set up a system. You kinda... sorta... *really* want to make sure it is configured correctly. 😜

**Comment by heaths** [comment]
You're right, they don't interact with the sevice, but in those cases - even if it were an enum - we would use `ExEnun? e = null` or `= default` (same thing compiled), which is what we already do. You're assuming that `default(SomeRealEnum)` is valid for the service (probably isn't), or that the service doesn't have a string value that equates to an actual default value, like `None`. So I don't really see the problem, since even for an optional enum we'd make it nullable, which works for both enums and structs. And allocating a class on the heap is wasteful for a string container.

**Comment by MiYanni** [comment]
> You're assuming that default(SomeRealEnum) is valid for the service (probably isn't)

This isn't an assumption. In swagger, `"x-nullable": true` states that a given value can be null (on the wire). Thus, null has significance in that scenario. Our C# version of `null` literally cannot represent omitted. However, I am assuming that C# `null` and `default(ExEnum)` represent the same thing in our language (independent of them being a reference type or value type). It would be very confusing for everyone to have them mean different things in a nullable value type (meaning in `ExEnum?`, if `null` means something different than `new ExEnum()`, that'd be confusing). This is because there wouldn't be an equivalent mechanism for reference types.

To this discussion about defaults, though, we need to be very aware of the difference between *client-side default*, *server-side default*, *nullability*, and *optionality* as they all cause different interactions for requests and responses. That was my point. To @AlexanderSher's options, you'd need to state when the defaults represent a **client-side default** or **omitted**, as that makes a difference in requests/responses.

**Comment by heaths** [comment]
As for defaults declared in swagger, I don't see what impact that has on parameters. If it has a default, it shouldn't be required and, thus, isn't in a constructor by our guidelines. Even if it was, the fact it has a default doesn't mean it has to be encoded in code:

```c#
public Foo(string key, ExEnum? e)
{
  e ??= ExEnum.Whatever;
}
```

Even if `e` took a value, it would be `default` (same thing as `null` here). But if it did, then, by our rules, it shouldn't be in the constructor.

In what case that follows our guidelines requires coding a default for extensible enums or even regular enums in ways that requires a constant (as the C# compiler does).

**Comment by heaths** [comment]
We probably shouldn't be using client-side defaults, as that trends toward violating guidelines against client-side validation and coupling.

But even if you use a real enum, x-nullable means it has to be a nullable enum. For that reason, you'd use a nullable extensible enum (struct).

**Comment by MiYanni** [comment]
As discussed offline, `default(ExEnum)` wouldn't actually represent any value to the service. Meaning, if that is provided by a user of the SDK, an exception would be thrown. However, the discussion went deeper on how client-side defaults is in the same realm as client-side validation. But, that is still up for discussion.
