### ISSUE TITLE
Board Review: Embedded C Azure::Core

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk#1690]
## The Basics

* Service team responsible for the client library: Azure SDK
* Link to documentation describing the service: https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.4/index.html
* Contact email (if service team, provide PM and Dev Lead): Rick

## About this client library

* Name of the client library: azure-core
* Languages for this review: C
* Link to the service REST APIs: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### C

* Core: https://apiview.dev/Assemblies/Review/2339253c7f1343dabf7d78ee5b4496aa
* Storage: https://apiview.dev/Assemblies/Review/c44cb23859134596b7ebbdc1ff4b74d4

## Champion Scenarios

* Upload a file:
    * An IoT device captures a photo and uploads.
    * Link to the code sample: https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/storage/blobs/src/blobs_client_example.c

**Comment by lilyjma** [comment]
[MS Internal Only][Video](https://msit.microsoftstream.com/video/b14da1ff-0400-96f3-1345-f1eaee3ac9de) 
Notes by Ahson Khan for both issues (the [IoT issue](https://github.com/Azure/azure-sdk/issues/1691))

- Guidelines/convention - uint8 for buffers/bytes/length-based chars and char* for null terminated strings.
- Retry-policy options - make sure it is consistent with other languages.
- Add delete and put blob to storage.
- Update upload option defaults to be consistent with the other languages, fail on overwrite.
- Add a "dependency not found" az_result and use that instead of not implemented.
- Consider adding append blob if customers need it.
- Add documentation around the data format of what device_id is expected to be, in iot hub client init
