### ISSUE TITLE
Change Request: Azure SDK for iOS Guidelines

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk#1844]
## The Basics

* Which design guideline is affected?
General guidelines for mobile

* Which target languages are affected?
iOS - Swift

* Describe the change:
Introducing draft guidelines for iOS

## Reasoning
With the recent preview of Azure Core for Mobile, the mobile team is prepared to introduce the draft guidelines for General and Azure Core

Please provide any additional detail or reasoning for the request. 
Link to iOS draft guidelines: https://azure.github.io/azure-sdk/ios_introduction.html

Mobile team will upload API surfaces to introduce the preview of Azure Core, but the focus will be as examples of the guideline implementations.

Other resources to consider:
1.	[Guided Tour of the Swift Language](https://docs.swift.org/swift-book/GuidedTour/GuidedTour.html)
a.	Optional: [Full details of language features in the Swift Language Guide](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html)
2.	[Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) – these are considered part of our SDK guidelines, SDK authors are expected to follow these standard guidelines in addition to the Azure-specific ones below.

**Comment by bsiegel** [comment]
I have opened a PR that we can use to comment on the public API: https://github.com/Azure/azure-sdk-for-ios/pull/452

**Comment by lilyjma** [comment]
scheduled for 10/1

**Comment by lilyjma** [comment]
moved to 10/5

**Comment by JonathanGiles** [comment]
@bsiegel Where would you like us to leave feedback on the guidelines themselves? Did you want to create something in github so we could comment on specific sections, or just leave comments in here?

**Comment by bsiegel** [comment]
I think we can just leave comments in here if that works for everyone.

**Comment by bsiegel** [comment]
@JonathanGiles asked:

* 'AzureMgmt' does not align with the management team preference of using 'resource manager'
* Only an async client? This was initially my preference for Java but we found developers really needed a sync client too. Are you sure?
* How does iOS support client options parameters that are required or mutually exclusive? Is it different constructors with non-optional parameters?
* Does swift not have a higher-level 'duration' / 'timespan' type that would prevent the need for using 'InMs' and 'InSeconds' prefixes and ints / longs?

**Comment by bsiegel** [comment]
1) We don't currently expect to support management plane scenarios at all currently, though that may change. That said, we can definitely change the prefix in the guidelines. Would `AzureRM` be a good prefix?
2) Yes, but async in iOS is very simple - functions take a callback as their last parameter, and the callback is called when the async operation is complete. This is extremely common in iOS development as most Core Foundation APIs work this way. Swift's [trailing closure](https://docs.swift.org/swift-book/LanguageGuide/Closures.html#ID102) syntax makes this extremely easy to use in practice. I can't say for sure that blocking APIs don't exist in Core Foundation, just that I don't recall coming across any.
3) If a client option is required, I think we expose that as top level parameter. For example `StorageBlobClient.download(blob:fromContainer:toFile:withOptions)` has two required parameters. We should make sure to encode this in the guidelines as I don't see it there today. But generally, `options` should be reserved for parameters that are, well, optional. As for mutually exclusive parameters, I'm not sure exactly - we haven't encountered that yet. Perhaps in that case, the options type would be a protocol, and multiple structs would implement that protocol, one for each mutually-exclusive set of options.
4) I wasn't familiar with it, but Swift does appear to have `TimeInterval` which is merely a type alias for `Double`, however Apple's docs specify that a TimeInterval is interpreted as a number of seconds. We could definitely use that. But for things where milliseconds are expected, we would have to guide the developer to use e.g. `timeout = 0.1` rather than `timeoutInMs = 100`.

**Comment by lilyjma** [comment]
[Video](https://msit.microsoftstream.com/video/eefca0ff-0400-9fb2-6a2b-f1eb125f0325)[MS Only]

**Comment by tjprescott** [comment]
> If a client option is required, I think we expose that as top level parameter. For example StorageBlobClient.download(blob:fromContainer:toFile:withOptions) has two required parameters. We should make sure to encode this in the guidelines as I don't see it there today. But generally, options should be reserved for parameters that are, well, optional. As for mutually exclusive parameters, I'm not sure exactly - we haven't encountered that yet. Perhaps in that case, the options type would be a protocol, and multiple structs would implement that protocol, one for each mutually-exclusive set of options.

This was always an issue with the Python SDK and the CLI, so I would be curious if other languages even attempt to tackle this problem. In the CLI we essentially built utilities to allow the client to do this validation in the cases where the service error was poor, but generally I feel like we left that to the service to return an error and a sufficient description of the mutual exclusivity violation.

**Comment by tjprescott** [comment]
Feel free to leave comments on the interface itself at: https://github.com/Azure/azure-sdk-for-ios/pull/499

**Comment by lilyjma** [comment]
Part 2 scheduled for 11/3

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/0a25a1ff-0400-9fb2-0f53-f1eb1e301d02)[MS INTERNAL ONLY]
