### ISSUE TITLE
Pipelines should be smarter about what they build

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#192]
There are some smart tools to do build selection which we could use, but this is to track at least using some simple selection for CI such that PRs with just documentation changes don't cause a full build to occur.

DevOps Pipelines [natively support path filters on triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml).

At a minimum we should have a filter for *.md files to not trigger a full build and waste resources.  Bonus points if we can accomplish more than that for cheap.

**Comment by mikeharder** [comment]
Both @jeremymeng and I tried prototyping the PR path filters, but neither of us could get them working correctly.  I was seeing incorrect behavior both ways -- in some cases changed files did match the filter but did **not** trigger a build, and in other cases files did **not** match the filter but did trigger a build.  And when this happens (especially for the no-build case), I don't know how to debug in DevOps **why** the build was or wasn't triggered.

**Comment by mikeharder** [comment]
It might be worthwhile testing this with both GitHub repos and DevOps repos.  Maybe the filters work correctly with DevOps repos but have bugs with GitHub?

**Comment by mitchdenny** [comment]
I'm looking into this now. Turns out that path filters might not give us what we are after here. Path filters define IF a particular Pipeline should run, but once it runs the trick is then to determine the specific set of actions that should actually be executed. Path filters are more useful when you have one (repository) to many (pipelines) arrangement or you have parts of your repo that you never want to trigger a build (docs for example).

My initial thinking was perhaps an environment variable is populated that lists the specific path and branch filters that triggered the repo and then just process that to determine what code to run - but I had a quick look at there doesn't seem to be anything.

Another option could be to process the output of this command:

```
$ git diff --name-ony HEAD~1
path/to/clientcode/file.py
path/to/sdkcommon/otherfile.py
```

I'm thinking that we could create some kind of rule-file in the root of the repo like this:

```
rules:
- rule: SHOULD_BUILD_COMPONENT_X
  paths:
    - src/componentx/**/*
- rule: SHOULD_BUILD_COMPONENT_Y
  paths:
    - src/componenty/**/*
```

Then as one of the first things that is done in each job we process that file. It would emit ```##vso``` commands to populate the variables above (so they span task invocations) and then they can be used either declaritively on the task conditions, or within scripts.

**Comment by mitchdenny** [comment]
Assumption for the above comment - we want to have a single pipeline per repo. If that isn't the case then path filters will work with multiple pipelines all with different path filters.

**Comment by mitchdenny** [comment]
I've done some experimentation with both approaches. They both work but I think that having a single pipeline that detects what solution file to build is fairly complex for folks to have to reason about and I think that if we are scoping this to PR scenarios that we could have a pipeline per shippable component.

**Comment by mitchdenny** [comment]
In PR: #6039

**Comment by mitchdenny** [comment]
In terms of pipeline names I'm planning on going with something like:

```[repo name].[component name].[build type]```

Applied to the .NET SDK repo then we might have something like:

```azure-sdk-for-net.servicebus.client.pr```

The name of the default PR build (where we don't have a more optimized version) would be:

```azure-sdk-for-net.client.pr```

And eventually if we use the same convention for CI builds they would become:

```azure-sdk-for-net.client.ci```

**Comment by weshaggard** [comment]
Based on our existing guidelines and plans for the test pipeline naming I'd like to suggest we go with something like:

`[language] - [component/service] - [type]` 

Where type would be something like "tests" or "build" or "client" perhaps. 

Do you envision us having a ci and pr build in our public repo or would we simply have both triggers enabled on definitions? 

cc @danieljurek as he is also looking at how to do this for the tests.

**Comment by mitchdenny** [comment]
Moved this (hopefully short-term) to the blocked folder. The Cosmos team uses an emulator during their PR validation/CI builds. We currently have a ```python - cosmos - ci``` pipeline setup which spins up the emulator and executes the tests directly.

This is a variation on the way that the rest of the SDK is setup. We need to think through how to handle these special case scenarios. I've got some ideas around supporting optional job insertion from the ```ci.yml``` file. Or we could create a special archetype template.
