### ISSUE TITLE
C++ Guidelines - The default stance is to expose data members directly - rewrite to be less ambiguous

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk#2011]
This is ambiguous and difficult to understand.

https://azure.github.io/azure-sdk/cpp_design.html#cpp-design-logical-no-getters-or-setters
> DO define getters and setters for data transfer objects. Expose the members directly to users unless you need to enforce some constraints on the data.

I believe the intent is as follows:
1)	DO expose the members directly to users unless you need to enforce some constraints on the data.
a.	In that case, DO NOT define getters and setters for those members.
2)	If you need to enforce some constraints on the data, only then DO define getters and setters for data transfer objects. 

cc @RickWinter, @CaseyCarter, @tg-msft

**Comment by ahsonkhan** [comment]
Also @BillyONeal to provide additional context on the intent since I believe he originally authored this.

We currently default to having passive data structures for a lot of our model types in C++ that expose the members directly rather than having Get/Set methods.
For example:
https://apiview.dev/Assemblies/Review/a5fe5245690f4fb986d28b4231f96dd1#Azure::Storage::Blobs::BlobContainerItem

Do we actually prefer using the Get/Set model instead of directly exposing members in such cases?

**Comment by tg-msft** [comment]
Do C++ optimizers do a decent job inlining multiple chained getters into just offset math?  Could we default to getters for everything as a rule?  It would be worthwhile to discuss C++ API versioning and what our standards/expectations are around breaks (i.e., since everything's compiled in, would making a getter virtual in a future release be a break?).

**Comment by BillyONeal** [comment]
>Do we actually prefer using the Get/Set model instead of directly exposing members in such cases?

The guidelines recommend against get and set member functions because plan aggregates are easier for users to use (e.g. they're eligible for aggregate initialization) and tend to be friendlier to compiler optimizers.

>Do C++ optimizers do a decent job inlining multiple chained getters into just offset math?

In release mode, sure. But debug mode perf matters too.

>Could we default to getters for everything as a rule?

You could do that but I strongly recommend against it and that's why I wrote it that way in the guidelines.

>would making a getter virtual in a future release be a break?

Making it virtual doesn't do anything for you because things in C++ are passed around by value, which means the concrete type at runtime is always going to be the non-overridden one for most consumers.

(PS: There's no such thing as a "method" in C++; you probably want to use "member function" or "nonmember function" in docs, samples, etc.)
