### ISSUE TITLE
Normalize some of the names in the package index

### ISSUE THREAD

**Issue by kraigb** [Azure/azure-sdk#2191]
@weshaggard There are merge conflict in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1349, which appear to be because the docs links have disappeared for a number of entries. Please review and fix as needed. so we can get these include files updated.

**Comment by weshaggard** [comment]
The merge conflicts came from https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1404 @v-andreaco it looks like you manually edited some links and text in those files. Given they are generated we will need to make those updates into the CSV file or generation process in this repo.

**Comment by v-andreaco** [comment]
@weshaggard 

I edited link text to make the article _javascript-all.md_ Acrolinx compliant (and avoid future blocking issues). I changed only the link text, not the URL in each case. Here are the changes I made:

Power Shell -> PowerShell [Line 72]
Github -> GitHub [Line 202]
Autorest -> AutoRest [Line 486]
Dev Test Labs -> DevTest Labs [Line 549]

Please let me know if there's anything else you need from me.

**Comment by weshaggard** [comment]
Thanks @v-andreaco we will need to make those updates in the underlying data source in order to have them persist during our automated updates. For those we will need to update the csv files https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/js-packages.csv. I will try to make those edits as part of resolving this issue.

**Comment by weshaggard** [comment]
Fixed only remaining issue with https://github.com/Azure/azure-sdk/commit/b371ce274eeb649941cc222be59609f1449a637b.
