### ISSUE TITLE
Storage - Enable HTTPS Bypass for local development with Azurite

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk#2195]
Developers use [Azurite](https://github.com/azure/azurite) for local storage development emulation so they don't have to hit Azure directly when doing development and CI.

Storage libraries currently require storage endpoint be HTTPS.

HTTPS is a pain to setup locally, especially when you consider containerization constraints and difficultly creating certs that work across those boundaries. It's possible by painful.

To lessen the load on local development, it would be great if we could allow developers to bypass the HTTPS requirement for local development.

We can put constraints in the design like:

- Endpoint must start with 127.0.0.1

The default Azurite well known endpoints are: 
```
BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1
QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1
TableEndpoint=http://127.0.0.1:10002/devstoreaccount1
```

The dev can customize the host to something other than 127.0.0.1, but for the sake of this requirement, I'm fine with saying it must be 127.0.0.1 to simplify things.

This is the HTTPS check (for .NET)
```csharp
public static void VerifyHttpsTokenAuth(Uri uri)
{
    if (uri.Scheme != Constants.Https)
    {
        throw new ArgumentException("Cannot use TokenCredential without HTTPS.");
    }
}
```

It could change to something like this:

```csharp
public static void VerifyHttpsTokenAuth(Uri uri)
{
    if (uri.Scheme != Constants.Https && !uri.Scheme.StartsWith("http://127.0.0.1"))
    {
        throw new ArgumentException("Cannot use TokenCredential without HTTPS.");
    }
}
```

azsdke2e
azsdke2e2

@kurtzeborn @joshfree @XiaoningLiu

**Comment by XiaoningLiu** [comment]
Thanks Jon for the proposal!

Azurite now has checks for OAuth requests which must use HTTPS protocol. Because it's a security requirement for OAuth.

Agree that setup HTTPS for Azurite needs many steps.
Besides for SDKs, we can consider introducing a bypass flag for Azurite.
Without this flag, by default, Azurite should keep requiring HTTPS for OAuth requests with bearer token which aligns with Azure cloud.

**Comment by letmaik** [comment]
I switched to connection strings in the meantime since it's virtually impossible to get https running locally with things like Docker Compose. I'd like to add that making the bypass dependent on 127.0.0.1 won't work in all cases, for example Docker Compose exposes each service as a custom host name to the other containers and wouldn't be accessible via 127.0.0.1.

**Comment by berndverst** [comment]
> I switched to connection strings in the meantime since it's virtually impossible to get https running locally with things like Docker Compose. I'd like to add that making the bypass dependent on 127.0.0.1 won't work in all cases, for example Docker Compose exposes each service as a custom host name to the other containers and wouldn't be accessible via 127.0.0.1.

It is possible, but friends don't let their friends mess around with Docker networking :)

**Comment by woeterman94** [comment]
Any update about this? How can we use local urls for azurite without https?

**Comment by wgcostta** [comment]
Any update about this? How can we use local urls for azurite without https?
