### ISSUE TITLE
In the releases doc, navigating to the last 2020 Releases section in the navigation sidebar causes the dropdown to collapse

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk#2219]
1. Go to: https://azure.github.io/azure-sdk/releases/latest/
2. Click on the "2020 Releases" drop down on the sidebar so it expands.
3. Select "December" and observe the dropdown collapses hiding all the 2020 months.

OR

1. Directly go to: https://azure.github.io/azure-sdk/releases/2020-12/index.html
2. Observe the dropdown is collapsed:
![image](https://user-images.githubusercontent.com/6527137/103956926-69179300-50fe-11eb-9812-11078d7727cf.png)

The same is not true when navigating to other months, like:
https://azure.github.io/azure-sdk/releases/2020-11/index.html
Or even for December 2019:
https://azure.github.io/azure-sdk/releases/2019-12/index.html

![image](https://user-images.githubusercontent.com/6527137/103956986-8ba9ac00-50fe-11eb-9235-94cff9d624e2.png)

cc @vhvb1989 in case you have some ideas why this is happening

cc @jongio, @weshaggard

**Comment by vhvb1989** [comment]
Yeah, the issue is with
  `releases/2020-12/index.md`
it is missing the metadata tag:
  `permalink: /releases/2020-12/index.html` 

The sidebar checks the current url address against the generated html and adds the style `active` when the url is the same.
We should not require to set the permlink for each page as it is a redundant info.

the simplest fix is just to add this info and keep adding the permlink metadata to all next release pages in order to keep the sidebar working.

The better fix is to update the sidebar code to find out the url based on something else, and then we don't require the permlink. It would require some more effort :)
