### ISSUE TITLE
js-packages.csv should not list deprecated packages

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#2290]
The https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/js-packages.csv currently lists a whole bunch of "connector" packages that are deprecated as they are no longer deemed necessary by the package owners. Our list should not include them

cc @weshaggard

**Comment by jongio** [comment]
They should all have the Hide=true, which means they won't show up on the package list page.  I personally don't need them in the csv, so if you'd like to go one step further and remove them from the csv, that would be fine with me.

**Comment by ramya-rao-a** [comment]
Thanks @jongio 

@weshaggard You ok with us removing these packages from the csv file? If so, do you want me to send a PR or is there some other automated way you have to generate this?

**Comment by weshaggard** [comment]
Generally we mark things as hide=true because they come back when we query the package manager. However in this case they are deprecated they shouldn't be included in the query, in fact my automation is recommended these could be [removed] (https://dev.azure.com/azure-sdk/internal/_build/results?buildId=703766&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a).  So these could be removed if you would like.

For my curiosity is this causing some issue or is just noise in the CSV that you want to remove?

**Comment by ramya-rao-a** [comment]
> For my curiosity is this causing some issue or is just noise in the CSV that you want to remove?

just noise and also coz I love seeing deleted lines of code :)

**Comment by weshaggard** [comment]
Feel free to do the honors and submit a PR to delete them. You can delete the same connector libraries from dotnet csv as well if you like.
