### ISSUE TITLE
The `Verify site links` steps from the CI pipeline is not efficient. It's taking much time and causing 429 responses from servers

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk#2403]
Can we make the `verify site links` a little smarter and add cache to resolve the links?  

Use a cache to quickly resolve known links instead of trying to fetch it.
Then refresh cache weekly or something.

This way, only new added links would be verified instead of running the entire set all the times on CI.

I noticed nugget.com is returning 429 responses because we are sending too many request over and over.
![image](https://user-images.githubusercontent.com/24213737/107809235-9bc93280-6d1f-11eb-87a1-07c10b729384.png)

Verify step is taking 20min per PR and sometimes the change is not even adding a new link.
![image](https://user-images.githubusercontent.com/24213737/107809389-ddf27400-6d1f-11eb-914f-38aa411db864.png)

**Comment by weshaggard** [comment]
Thanks @vhvb1989 for the suggestion I've definitely thought about this in the past but didn't really take action on it. We do have some caching but it is limited to a single run (i.e. we will not ask more then once for a given link). The trouble with having a cache across runs is we have to persist it and keep it updated as we definitely know things change over time. 

I'm definitely aware of the 429's and a couple months ago I prototyped some [throttling ](https://github.com/weshaggard/azure-sdk-tools/commit/a68c324f496e8b1f3acab9575f8ea1a27aa389c2) which helps but as you can imagine makes the process longer.

@sima-zhu it is worth considering to add some form of caching that we can persist and keep updated overtime. We just need to think about how we would do that.

**Comment by vhvb1989** [comment]
@weshaggard  I could join efforts here

My suggestion would be
- Spin a simple REST server and host it somewhere (similar to the APIview or any other service we might have hosted somewhere)
- Implement two APIs for the server `GET /link_cache?repo=repoName` and `PUT/DELETE /link?repo=repoName`
- The first one would return a json with the list of all the known links for a repo. Verify links would get this list and use it as cache.
- If a link is not in cache, it would means it's a new link, so we verify the link.  If it valid, then we call the PUT to the server to add this link to cache.  If it fail, the CI fails.
- Let a nightly pipeline from the repo to get the cache and validate all links from it. It would call `DELETE /link?repo=repoName` to remove the link from cache and fail the nightly pipeline for people to take action to the link,

I can help creating the server and I would just need EngSys to mention where we can host it and update the verify links steps.

Let me know what you think.

You might wonder about security (people manually adding links to the cache). If that's a concern, the server can take an auth token base on some credential and the pipeline would be the only one with the credential or private key.  But I wouldn't worry to much about this, since it's actually similar to the ignore-list that CI supports.

**Comment by mitchdenny** [comment]
I considered implementing this as a GitHub check. The way it would work is that every time a check-run is requested it would get the commit sha. It would then get the last n commits in that _head_ and check what their status. If their status was good it would then check to see what files where changed in the intervening commits. If any of them where among the set of files we check for links we would read just those files and validate links as appropriate. From PR to PR run it might take a few seconds to do this but should be generally pretty quick.

This doesn't account for link breakages over time. So in addition to doing the broken link evaluation for new links in changed markdown files, and links that had not been checked recently (e.g. in the last X period) would also be checked. This could be performed in the background.

A cheap way to move from what we have to this more efficient (albeit elaborate) solution would be to have a link checker pipeline which we can run against any pipeline/any commit and when we receive a commit that contains an updated file with links in it we run that job. If no link containing files were updated we would just walk back through the commit tree to find a previous run.

Data storage for this could probably be entirely managed within GitHub itself, because the presence of a passing/failing check run attached to a SHA is the actual data we want to store. So the function itself would be stateless.

**Comment by weshaggard** [comment]
Thanks @vhvb1989 and @mitchdenny for the ideas but I kind of feel both of those options are a little more complicated then we need. I suspect we can get away with a simple shared blob storage file that simply contains a list of cached links that we know to be valid.

I'm imagining something simple like:
- Verify links script will pull a single file from blob storage. That file is essentially a list of links we believe are valid and we use that to seed our checked link cache so we don't need to check those in our pipelines.
- We have a nightly pipeline that will run checks across whatever repos we want to include and then it will take the list of valid links and upload it to the blob storage. We already have [this pipeline](https://github.com/Azure/azure-sdk-tools/blob/master/eng/pipelines/githubio-linkcheck.yml) that checks nightly we just need to update it to upload a cache file.

**Comment by sima-zhu** [comment]
@weshaggard 
It generally serves the purpose, but lack of real-time checking. Suppose some of the links valid at night, but failed because of new commits or external changes. We will miss it from PR checking and might catch the issue in an irrelevant PR.

Also applies to other caching approaches, as we have the possibility of caching outdated links. It is a trade-off between accuracy and performance.

**Comment by weshaggard** [comment]
If there are links not in the cache but are in the PR we will check those live still. So we should still catch any new links. We will have a potential broken links for up to a day in cases where they were valid before but now are broken. I think that risk is pretty small and as long as we catch them in a reasonable timeframe (i.e. a couple days) I think we are fine.

**Comment by weshaggard** [comment]
I've got a porotype of the caching working. I currently have the required changes in CachingSupport branch in azure-sdk-tools https://github.com/Azure/azure-sdk-tools/tree/CachingSupport. I've hooked up our tools to that branch with https://github.com/Azure/azure-sdk/commit/2c69592a56587edc5b228e89af75b00c6f740292#diff-8e3e98720358c1ba11ea8e8fefdf79d0cbec85174fa07dea42d34f7c78f6fb08R10 and once I confirm things are working as I'd like then I will move those changes to azure-sdk-tools master and have the other usages outside of this repo also use the cache.

**Comment by weshaggard** [comment]
OK have added this feature and enabled it in our common templates.

For reference the nightly pipeline at https://dev.azure.com/azure-sdk/internal/_build?definitionId=1620&_a=summary is the one responsible for checking and updating the link cache file.
