### ISSUE TITLE
Change Request: short LROs for all languages

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#2638]
The current data plane LRO libraries provide a nice abstraction for operations which may take a very long time to complete. However, for operations that are long-running in the sense that having an http request open for that long, but not so long running that it's not advisable to `await` the result, current LRO patterns are somewhat verbose.

Additionally, there is some prior art to projecting certain LROs as simple awaitable async operations, e.g. in Track 1 JS management plane libraries and some current management plane libraries for Java.

I would like to discuss whether and when it makes sense to provide an LRO abstraction that is directly awaitable in all languages.

**Comment by lilyjma** [comment]
scheduled for 4/6

**Comment by lilyjma** [comment]
[Recording](https://msit.microsoftstream.com/video/12860840-98dc-94b1-8901-f1eb97262df0)[MS INTERNAL ONLY]

**Comment by deyaaeldeen** [comment]
# Plan going forward

## Current Actionable items:
- [ ] Meet with Brian, Krzysztof, and Michael Nash to come up with names for poller-returning and result-returning methods in managmenet-plane packages
- [ ] Consider applying the proposed names to data-plane LROs as well
- [ ] Research services' LRO APIs and determine how many of them should not have a result-returning method (i.e. the ones that take really long on average (> 10 min?)). If the number of those APIs is significant, consider how to identify them in the swagger so we do not generate result-returning methods for them.

## Summary

There are issues with only giving the customers poller-returning methods. On one hand the extra method call needed to await the poller until the request is finished is not a lot of code but on the other hand it is 100% increase in code. Additionally, in many cases, the latency of an API request depends on the input size, and in the average case, the latency is almost instantaneous. Furthermore, there is fundamental disconnect between things that make sense from the API design point of view and from the SDK's programmability model point of view. Having open http connection for so long is a bad pattern but we do not have to push that to the SDK customers. 

So the architects think  providing result-returning (simple) methods to our customers is sensible. Many customers will try to code the simple (and buggy/bad?) methods themselves so it might be best to provide it to them instead in a correct, consistent, and universal way. However, the architects are wary of the scenario where the customer call a simple method for an API that could take too long to finish. Also, there could be latency increase creep in new versions of the API which might render the corresponding simple method not usable in the future. Furthermore, there are concerns implementing it in their respective language due to lack of customers request (Python) or their Track 2 Management-plane packages already GA's (Java but they already have an overload for the result-returning method). 

No concrete proposal was discussed but JS and .Net will meet to come up with one and it is doable for them because they did not GA Track 2 management-plane packages yet.

## Design constraints

- Always provide the poller-returning method
- Allow the customer to control the polling interval in result-returning methods because they are charged for each request in some services (e.g. storage) and also to be able to control latency
- Consider how would the customer get the job id to do rehydration in case of errors/crash/lost connections (inject it into the exception?)
- Really long LROs will be an issue so it might be best to not apply this pattern uniformly
- .NET data-plane's return type `Operation<T>` will make it difficult to apply this pattern in data-plane packages

## Naming suggestions:
- StartDelete, StartDeleteAsync, WaitForDelete, WaitForDeleteAsync
- BeginXAndWait
