### ISSUE TITLE
Live test environment setup scripts

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk#273]
Currently, setup for live tests (https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.ApplicationModel.Configuration.Tests/Readme.md) environments is described in READMEs and is done manually for CI configurations.

I think it would be beneficial if we decide on a set of common patterns that would be used across SDKs and repos to prepare live test environments both for local testing and CI.

For example, we can require live test projects to carry LiveEnvironmentSetup.ps1/sh and LiveEnvironmentTearDown.ps1/sh scripts.

cc @mikeharder

**Comment by mitchdenny** [comment]
One way to do this would be for every test environment to be defined as an ARM template. We would provide a publically accessible endpoint that we upload the ARM template to with the parameters and the service would check to see whether that template was amongst the set of templates that were allowed.

The service would then return a set of service principal credentials that has access to that resource group and the resources contained within it.

The resource group would be time bound, there would be a service that would destroy it automatically after a period of time. Over time we would preprovision these resource groups so that tests wouldn't even need to wait for the environments to be provisioned. Allowing for faster execution times.

When requesting a test environment, the test case would declare whether they can reuse an environment or whether they need a clean environment.

**Comment by kurtzeborn** [comment]
Creating ARM templates is probably an epic unto itself but for now I'm putting it under the live/simulated tests epic for now.

**Comment by mitchdenny** [comment]
@danieljurek is this overlapping with some work that you are already doing?

**Comment by danieljurek** [comment]
This does! Similar work to use ARM templates and time-bound resource groups is tracked here: https://github.com/azure/azure-sdk/issues/597

The pre-warming service that you mentioned has also come up again in separate discussions as well.

**Comment by mitchdenny** [comment]
Should we be closing this one as redundant?

**Comment by danieljurek** [comment]
Seems reasonable to close this work item. The .NET team is working on environment automation that works for both developer onboarding and live testing.

**Comment by pakrym** [comment]
@heaths do we track this work somewhere on our side?

**Comment by heaths** [comment]
Not currently, but we can. I wasn't sure if @AlexGhiondea was planning on opening issues for MQ work. I'll talk to him and react accordingly.

**Comment by mitchdenny** [comment]
My understanding is that we now have ARM scripts in place with ```test-resources.json```.
