### ISSUE TITLE
Create container that handles dependencies/configuration of test-proxy

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk#2779]
- appropriate dotnet
- test-proxy package already installed
- dev certificate configured

**Comment by kurtzeborn** [comment]
@weshaggard had a thought that by doing this, instead of requiring the devs to install the .NET framework, they now have to install Docker instead.  So the concern being raised about JS devs having to install .NET only swaps in Docker for .NET.  All that said, there are many other benefits from running the test proxy in a container.

**Comment by scbedd** [comment]
1) True
2) It gives us another avenue for people who want to remain entirely crossplat without installing and specific dependencies like .NET.
