### ISSUE TITLE
Tracing for messaging systems: add API to extract context

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk#3319]
When app receives a message, messaging SDKs extract context from each message and create a processing span/activity from it. 

In many cases users may want to do it explicitly
- when they use advanced/non-default concurrency such as in-memory queues, background long-running tasks, reactive programming, manually created threads, etc. E.g. https://github.com/Azure/azure-sdk-for-net/issues/23729
- when they receive in batches and want to trace individual messages
- they don't use handlers and use receive API

Track1 EventHubs and ServiceBus .NET SDKs provided [ExtractActivity](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Extensions/MessageDiagnosticsExtensions.cs#L64) API to deal with it, but there is no such method in Track2 (any language).

This should be available in .NET and return [ActivityContext](https://docs.microsoft.com/en-us/dotnet/api/system.activities.activitycontext?view=netframework-4.8), in other languages it should be provided through the OpenTelemetry plugin and return `SpanContext`. As a result, it should work (on par or better than Track1) with existing tracing solutions: Application Insights .NET SDK or OpenTelemetry across all languages.

**Comment by andrejpk** [comment]
I'm thinking about from recent work using the Java EH client SDK. In that case we were using Akka Streams to process each event using [EventProcessorClient](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.eventprocessorclient?view=azure-java-stable)/processEvent for individual messages. But since we were spanning threads, in the `processEvent` callback we called `Span.current()` and pulling the context from that Span to rehydrate that context on the right thread later.

Keeping the current behavior of creating and activating a Processing span around the processEvent callback makes sense for the (I believe) more common use cases where the user does work on the current thread in the callback. 

But for the scenario above, a more efficient approach may be to instead use the more advanced `processEventBatch` and a method like ExtractActivity to have more control over the start and activation of each processing span. 

In my scenario, there was another layer of complexity because we were processing EH messages containing an array of CloudEvents from an [EventGrid->EH Subscription](https://learn.microsoft.com/en-us/azure/event-grid/cloud-event-schema), so we had a loop and another layer of CloudEvent Spans that we wanted to link (not parent) to the EH message processing Span, so this is another case where we had to override the more typical `processEvent` tracing behavior.
