### ISSUE TITLE
Change Request: core package naming conventions for JS/TS

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-sdk#359]
The guidelines presently don't specify how we should name our core packages. Core packages identified for JS include at least:

* configuration
* amqp-common
* ms-rest-js
* aborter

And may include other things like a tracing library and other shared types.

There are actually two sorts of libraries here:

1. libraries we expect users might have to work with directly (aborter, configuration)
2. libraries users won't have to work with directly unless doing super complex things (ms-rest-js, amqp-common).

### Proposal

Core packages for the JS/TS SDK live in the `@azure` scope and are prefixed by `core`. If we do this rename, I also suggest `@azure/ms-rest-js` -> `@azure/core-http` and `@azure/amqp-common`. So for above:

* configuration: @azure/core-configuration
* amqp-common: @azure/core-amqp
* ms-rest-js: @azure/core-http
* aborter: @azure/core-aborter

My only concern about this proposal is that users might not expect to find functionality they need to work with directly, e.g. @azure/core-aborter, prefixed with `core`. Any thoughts on this?

Another alternative is to remove the `core` prefix from shared packages that users may want to use directly, but I worry about the ambiguity this might cause e.g. with `@azure/configuration`.

/cc @jeremymeng @ramya-rao-a

**Comment by christopheranderson** [comment]
Am I correct in thinking there are five types of libraries in @azure?

 - Service data plane libs
 - Service mgmt plane libs
 - Common core libs intended for broad consumption
 - Common core libs intended for mostly internal consumption
 - misc libs that are mostly extensions of the service libs for specific platforms (like angular plugins for stuff)

Assuming data plane get the `<service>` name and mgmt plane libs get `arm-<service>`, you've got those two solved.

IMO, that would mean you shouldn't do `@azure/configuration` because we might one day have an "Azure Configuration Service" or folks might *think* we have that service.

As for should both broadly consumed and mostly internal packages sharing `core`, I don't think there is actually much risk there. I'd wager that folks won't be organically discovering the `core` packages on their own - they will do it based on guides and docs from the core service's quickstarts/etc. Unless you expect that we'll be doing other things to change it such that folks would start with `core` libs, it's probably not an issue.

**Comment by bterlson** [comment]
I think your breakdown is roughly correct.

It's a hard requirement that we not *require* users to do things with core packages to do simple tasks. But as soon as you want to do e.g. cancellation or global runtime configuration for e.g. setting proxy settings, you're going to need a core package. Organic discovery isn't really my concern, I agree that's not necessary. My concern is more that users will be confused by `core` in the package name and think it's not something they should be using directly.

That said I think this is a minor problem (and we can validate with users of course) and lean toward the `core` prefix.

**Comment by jeremymeng** [comment]
@Azure/azure-client-js

**Comment by bterlson** [comment]
The guidelines are up [here](https://azuresdkspecs.z5.web.core.windows.net/TypeScriptSpec.html#ts-core-library-prefix), mostly based on discussions in the team room after filing this issue. The gist: `core-` is potentially confusing for libraries which users will need to import directly (think: AbortController). But it's valuable for things that users should not need to import the vast majority of the time (think: core-http). So, the general guideline is: `core-` for internal implementation detail things, unprefixed for things that users need to import.
