### ISSUE TITLE
Board Review:  .NET/Java Event Hubs Preview (June 2019)

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk#375]
## The Basics

* Service team responsible for the client library:  **Azure Messaging**  

* Link to documentation describing the service: **[Product Documentation](https://docs.microsoft.com/en-us/azure/event-hubs/)**  

* Contacts: 
    * Javier Fernandez (Service PM),  
    * SeongJoon Kwak (Service Dev Lead)
    * Ramya Achutha Rao (Event Hubs SDK All-Up Lead)
    * Connie Yau (Event Hubs Java SDK)
    * Jesse Squire (Event Hubs .NET SDK)  
   

* Expected code complete date: **June 21, 2019**  

* Expected release date: **~June 30, 2019**

## About This Client Library

* Name of the client library: **Event Hubs (June Preview)**  
* Languages for this review: **C# / Java** _(TypeScript and Python scheduled separately)_
* Link to the service REST APIs: [Event Hubs Rest](https://docs.microsoft.com/en-us/rest/api/eventhub/) _(Note: client libraries are built around the AMQP protocol, not the REST API)_

## Review Resources

* [Java Event Hubs Client: Track Two Proposal](https://gist.github.com/conniey/92b087a9b60b44b69fa8ce0cd39a9fbe)
* [.NET Event Hubs Client: Track Two Proposal](https://gist.github.com/jsquire/75b3a3090b6b4553aa8ceb798b6fc87d) 
* [.NET API Surface](https://gist.github.com/jsquire/7aaa2a8d54609452c0a238f10bad137f)
* [.NET API Skeleton Prototype](https://github.com/jsquire/azure-sdk-for-net/tree/eventhubs/track-2/prototype/sdk/eventhub/Azure.Messaging.EventHubs)

## Schedule

The review is scheduled for Tuesday, May, 21 2019 at 9:30am PDT.

## Agenda for the Review

The following agenda will normally be followed:

1. Introduction to the service (10 minutes max)
2. Class Heirarchy (general) and public API surface
    * To ensure consistency, discuss any language then indicate how the other languages are constructed
3. Per-language exceptions and examples
4. Implementation of champion scenarios (top 3-4 only) with code in preferred language
    * Include samples as attachments for other languages - all languages under consideration must be provided

**Comment by adrianhall** [comment]
Comments for .NET submitted on board 5/21:

* Add an exception to be thrown when you pass the options to the client for options validity
* Make retry policy an options bag and make the actual policy internal (table for after preview)
* @KrzysztofCwalina to file issue with proposal for retry policy guidelines changes
* Meet with @KrzysztofCwalina and @conniey to close on whether `ServiceVersion` is required in the client options.
* Certify that you can swap the credential during a retry due to the equivalent of a 401 (Unauthorized) response.
* (JAVA) Add a constructor overload that takes namespace / hubname / credentials / options
* Change the EventHubClient constructor to allow a DNS Name instead of a Uri for the namespace
* Change `CreateEventSender()` to `CreateSender()` (and ditto on the receiver)
* Rename `TimeoutWhenSending` to be Timeout (and ditto on the receiver)
* (JAVA) Add the senderOptions overload for `CreateSender()`
* @conniey to talk to the service team about how consumers use the partition IDs and whether we should expose them.  (Meta problem - be consistent across all languages - python does it differently!)
* Removed the very advanced sender (sized batch) method from the preview.

We will review Java API on 5/22.

**Comment by adrianhall** [comment]
Great job on providing the appropriate context for the review and walking through the scenarios.  We believe we have many issues open right now, but it's going in the right direction.
