### ISSUE TITLE
Move schedule triggers from designer into yaml

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#39]
Our schedule triggers should be moved from the designer into yaml, once they are supported (https://github.com/Microsoft/azure-pipelines-yaml/issues/39).

**Comment by kurtzeborn** [comment]
This is not supported currently, and even if it was, I think we'd want to specify these on a per-pipeline bases, not in the yml.

**Comment by stannynuytkens** [comment]
@kurtzeborn Why do I manually have to set a schedule trigger for each pipeline for each project? The reason I'm using yml is exaclty to avoid this?!

**Comment by dariustehrani** [comment]
@kurtzeborn I think this is an important feature in context of infrastructure as code.
Examples:
Building and maintaining OS Images with a pipeline (e.g. using Packer) 
Building and maintaining Docker Images with a pipeline.

Here a DevOps Teams might want to recurringly build these images against the latest OS Upgrades. If this can not be scheduled recurringly, each time someone has to go in and hit unexpected surprises which can happen proactively when the pipeline runs scheduled.

Thanks,
Darius

**Comment by weshaggard** [comment]
@stannynuytkens @dariustehrani this issue was tracking us using this feature in the devops pipelines we own on the Azure  SDK feature. I think we would agree with you that the feature should be supported by DevOps but that is tracked by https://github.com/Microsoft/azure-pipelines-yaml/issues/39 so if you would like to add more context and upvote the feature requests please use that issue.
