### ISSUE TITLE
Change Request: Virtuals with default parameters for C++

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk#4469]
Thank you for contributing to the design guidelines for Azure SDKs.  We welcome all discussions and contributions.  Since the design guidelines affect the client libraries for all Azure services, we thoroughly discuss and vet any design guideline changes before we incorporate them into the official guidance.  This process can take some time, so your patience is appreciated.

** Before submitting, ensure you adjust the title of the issue appropriately **

## The Basics

* Which design guideline is affected?

* Which target languages are affected?

* Describe the change:

## Reasoning

Please provide any additional detail or reasoning for the request.

**Comment by antkmsft** [comment]
I think the guideline should be:
Do not introduce virtual functions with default parameters.

I don't think there should be an exception for `final`, because it practically makes it impossible to remove `final` in the future versions, plus then the non-final virtual overload suddenly breaks the guideline.

I would like to say, that don't sacrifice ease of use for the customer either. If the default parameter would be really useful for the customer, write the class in either of two ways:

```cpp
class C
{
public:
    void f() { vf(1); } // does not have to be inline
    void f(int n) { vf(n); }  // does not have to be inline
    virtual void vf();
};
```

or,

```cpp
class C
{
public:
    // defaulted parameter could look better for intellisense/doxygen,
    // but I would not mandate either option at this point - overload or the default.
    void f(int n = 1) { vf(n); }  // does not have to be inline
    virtual void vf();
};
```.

In rare case you want the derived (including final) class to have the "default", then do the same - introduce `f()` the same as in example for `class C` above.
