### ISSUE TITLE
Board Review: Azure Communication Services (SPOOL) [Rooms] (Java, TS, Python & .NET)

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-sdk#4494]
**Team responsible:** **_Rooms_** by ACS

**Team members:**
radubulboaca@microsoft.com
elavarasid@microsoft.com
anujissar@microsoft.com
calvintang@microsoft.com
shirleyqin@microsoft.com

## Rooms overview 
 Azure Communication Services (ACS) Rooms is a set of APIs, used by Contoso server applications to create a server-managed conversation space with fixed set of lifetime and participants, pre-defining rules from server-tier both who and when can communicate (like scheduled meeting creation).
  
With the Public Preview release of ACS Rooms, Contoso will be able to:
1) create a meeting space with known time coordinates (start/end time), 
2) join voice/video calls within that meeting space using the ACS web calling SDK or native mobile calling SDKs, 
3) add participants to a room, 
4) assign pre-defined roles to room participants, 
5) set rooms call join policies (e.g., open or closed room),  and 
6) consume Event Grid notifications for calling events. 

The server-side functionalities can be accessed via a [refreshed API](https://global.rooms.prod.communication.microsoft.com/swagger/index.html?urls.primaryName=Azure%20Communication%20Room%20Service%20(2022-02-01)) and a full set of SDKs (.NET, Java, Python, JavaScript/TypeScript).

 The main scenarios where Rooms can best be used:
 - Virtual Visits (e.g., telemedicine, remote financial advisor, virtual classroom, etc...)
 - Virtual Events (e.g., live event, company all-hands, live concert, etc...)

## Champion scenarios

**Contoso College** is a fictional educational institution that provides both on-campus and online programs. Contoso College administrator would like to create a virtual space/room for each offered course where course owner can hold virtual meetings and exchange messages with students. Only registered students should have access to associated room.

Detailed champion scenario: [Rooms Azure Board Review - Champion Scenarios - Overview (visualstudio.com)](https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/24003/Rooms-Azure-Board-Review-Champion-Scenarios)

## Rooms Architecture specification

Rooms service builds on top of existing IC3 calling services. The service acts as abstraction and coordinating layer between public APIs and IC3 services. It is compute-only service at first, all storage being handled by IC3 Scheduling Service.

Room service itself will NOT be on active calling path. Call operations (e.g., join call) do not go via Rooms server API, except for roster-management. Rooms API is service-to-service, with no user-level actions.

Rooms service main responsibilities:
 - API and Server SDK for Room CRUD operations
 - API and Server SDK for Room Participant operations
 - ACS server authentication, resolve ACS resource ID metadata
 - Coordinate with Scheduling Service to create Room

![Rooms Architecture](https://user-images.githubusercontent.com/91082555/181369987-33dd0d21-3a19-4f85-8aef-243f8b2babb3.png)

Detailed [rooms architecture document](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EdKPi7ILwUJBvRc3-SILN1cB2F4kdlMbuIlsSqtTxdCO8Q?e=DI8Y7V)

## Rooms Concept

Here are the main scenarios where rooms are useful:

- **Rooms enable scheduled communication experience.** Rooms help service platforms deliver meeting-style experiences while still being suitably generic for a wide variety of industry applications. Services can schedule and manage rooms for patients seeking medical advice, financial planners working with clients, and lawyers providing legal services.
- **Rooms enable invite-only experience.** Rooms allow your services to control which users can join the Room for a virtual appointment with doctors or financial consultants. Developers can use the "Join Policy" for a Room, to either let all or a subset of Azure Communication Services users to join a Rooms meeting.
- **Rooms enable structured communications through roles and permissions.** Rooms allow developers to assign predefined roles to users to exercise a higher degree of control and structure in communication. e.g., Only presenters can speak and share content in a large meeting or in a virtual conference.

When to use rooms:
![acs-rooms-decisiontree](https://user-images.githubusercontent.com/91082555/181372571-10ced2e3-fa7f-42ac-8c79-4a17cc8e1945.png)

Details: [Azure Communication Services Rooms overview - An Azure Communication Services concept document | Microsoft Docs](https://review.docs.microsoft.com/en-us/azure/communication-services/concepts/rooms/room-concept?branch=pr-en-us-204669)

### .NET

[Azure.Communication.Rooms](https://apiview.dev/Assemblies/Review/23e9598914834349aaa58095e697ca88#)
 
### Java

[azure-communication-rooms (version 1.0.0-alpha.1) - 2020-02-01 - apiview.dev](https://apiview.dev/Assemblies/Review/c914953e6bf146538f7936468adc9973#)

### Python
[azure-communication-rooms - apiview.dev](https://apiview.dev/Assemblies/Review/db89acb9b7dc45dd80ab63a798662d7a?revisionId=223b9c93432e46b8ae7a92a996cb126e&doc=False)
 
### JavaScript/TypeScript
[@azure/communication-rooms - apiview.dev](https://apiview.dev/Assemblies/Review/e3adb5b0be6c4b60b7e977bd75c606e2#@azure/communication-rooms!GetParticipiantsResult:interface)

**Comment by kyle-patterson** [comment]
Scheduled for 7/28 9a-11a PDT

**Comment by tg-msft** [comment]
[Recording](https://msit.microsoftstream.com/video/6a8b0840-98dc-ae81-f802-f1ed0eabcd96) (MS INTERNAL ONLY)

**Comment by radubulboaca** [comment]
Saving notes captured in the Teams chat on this forum for transparency & completeness:

# Across all SDKs:
- Package names are consistent and valid across all SDKs; No further actions
- Participants: participant collections should be separate from the room.
    Next steps:
        - An API/SDK refresh will separate participants into a separate collection
        - Participants collection will include pagination support
        - Return values for actions on participant collections will be 'participantChangeResult', initialy an empty class (main purpose is future proofing)
- Update room options bag: the number of parameters for room update operations is getting to the point where the service would benefit from a dedicated options bag
    Next steps: the SDK refresh will include options bags for all languages
- roomJoinPolicy: getting feedback from multiple sources that the naming of room join policy and the two options may cause confusion or is not sufficiently intuitive
    Next steps: the API/SDK refresh will revisit naming for this room property and its values
- Dedicated clients per room: roomIds get passed as a parameter for all methods; consider creating dedicated client per room. may provide better developer experience in cases where some application is managing multiple rooms. Examples: chat vs chatThread
    Next steps: rooms team will analyze usage data and make a decision on whether to implement room clients
- multi-version support: .NET and Java SDKs list support for both 2021 and 2022 API versions. This may be either inaccurate or superfuous.
    Next steps: rooms team will validate that both versions are supported in the SDK. Azure Board recommended to drop support for 2021 version.
- rename RoleType to ParticipantRole: having explicit names improves developer experience by reducing autocompletion conflicts
    Next steps: Including this change in the API refresh
    
# .NET/C#
- CommunicationIdentifier should not be settable
    Next steps: will remove setter in the next iteration
    
# Java
- dependencies should be in 'provided' scope (https://github.com/Azure/azure-sdk-for-java/blob/1ba598781001540c57febb0df1f60955836ac4c4/sdk/textanalytics/azure-ai-textanalytics/pom.xml#L63)
    Next steps: will correct before preview
- client classes should be marked as 'final'
    Next steps: will correct before preview
- We should have a deleteRoom method that returns Mono<Void> too.
     Next steps: will correct before preview
- Client builders should implement *Trait interfaces.
    Next steps: rooms team will implement trait interfaces in the SDK refresh
- Remove "class RoomModel"
    Next steps: will correct before preview

# Python
- regenerate SDK without models
    Next steps: continue the conversation at an azure board/ACS level for plan on migrating SDKs to be fully generated
- valid_from, valid_until and other room parameters should be keywords
     Next steps: will correct before preview
- There seems to be some issue with this signature - the participants parameter is included twice. Likely due to Python 2.7 compatibility layer
     Next steps: will correct before preview

# TypeScript
- nullable properties
    Next steps: addressed before public preview
