### ISSUE TITLE
Change Request: Abstractions for all languages

### ISSUE THREAD

**Issue by LarsKemmann** [Azure/azure-sdk#546]
## The Basics

* Which design guideline is affected?
From [the .NET commonly-overlooked guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-appendix-overlookedguidelines):
> ⛔️ DO NOT use abstractions unless the Azure SDK both returns and consumes the abstraction. An abstraction is either an interface or abstract class.
> ⛔️ DO NOT use interfaces if you can use abstract classes. The only reasons to use an interface are: a) you need to “multiple-inherit”, b) you want structs to implement an abstraction.

* Which target languages are affected?
.NET, Java, basically every language that supports interfaces

* Describe the change:
**An abstract class is not an abstraction that can be _implemented_.** It is simply a shared implementation subset that can (must) be _extended._ Therefore, I propose that these guidelines should read something along the lines of:

> ⛔️ DO NOT use abstractions unless the Azure SDK both returns and consumes the abstraction. An abstraction is either an interface or abstract class.
> ✅ **DO expose service functionality via interfaces. Interfaces allow for mocking in unit testing scenarios.**
> <s>⛔️ DO NOT use interfaces if you can use abstract classes. The only reasons to use an interface are: a) you need to “multiple-inherit”, b) you want structs to implement an abstraction.</s>

## Reasoning

I saw this line in the Commonly Overlooked .NET API Design Guidelines and I was shocked/hopeful-that-I-simply-misunderstood:
> DO NOT use interfaces if you can use abstract classes. The only reasons to use an interface are: a) you need to “multiple-inherit”, b) you want structs to implement an abstraction.

This is either misleadingly worded (assuming that the reader is experienced enough to know all the cases when you can't use abstract classes, in which case that's a poor premise for writing guidelines) or just plain wrong. To start with:
- Interfaces are essential for unit testing/mocking
- Interfaces are essential for dependency injection
- Interfaces are essential for multiple OO patterns

[This interview on the subject](https://www.youtube.com/watch?v=X6-CIlMJR94) is an old one but should still be required viewing, IMO. Several of the .NET Azure SDKs in the past few years have suffered from improper use of abstract classes and it causes a _lot_ of pain.

**Comment by adrianhall** [comment]
Thank you for your change request.   I will get an architect to review and you can have a dialog about this topic.

**Comment by KrzysztofCwalina** [comment]
The guideline is a .NET specific guideline. It's not "... Java, [and] basically every language that supports interfaces is affected."

Secondly, @LarsKemmann, could you explain why you think interfaces are "essential for unit testing/mocking"? [Here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.ApplicationModel.Configuration/samples/Sample8_MockClient.cs) you can see a sample showing how to mock one of our SDK clients without the client library exposing any interfaces.

Lastly,

> Several of the .NET Azure SDKs in the past few years have suffered from improper use of abstract classes and it causes a lot of pain.

@LarsKemmann, can you give us details on the pain-points you encountered?

As to why we (both .NET Framework/Core and Azure SDK) prefer abstract classes over interfaces: the reason is that interfaces cannot be evolved without causing breaking changed, i.e. we cannot add new members to interfaces without breaking existing code. Yet our libraries will have to evolve over time by adding new members to existing types.

**Comment by SeanFeldman** [comment]
A concern I have with what @KrzysiekKnigawka is suggesting is that it will require library creators to mark every method as `virtual` to be able to test those methods. It's not something that developers are used to. , and that's what @LarsKemmann is 

> As to why we (both .NET Framework/Core and Azure SDK) prefer abstract classes over interfaces: the reason is that interfaces cannot be evolved without causing breaking changed, i.e. we cannot add new members to interfaces without breaking existing code. Yet our libraries will have to evolve over time by adding new members to existing types.

There are multiple ways to handle changing APIs. Some do not require abstract classes for everything. For example, if there's a method that takes parameters, rather than passing multiple parameters, have a context object. The context object can change w/o breaking method signature.

**Comment by KrzysztofCwalina** [comment]
@SeanFeldman, the whole .NET framework is designed this way, i.e. preferring abstract classes over interfaces. .NET developers are probably used to how the .NET Framework is designed.

> There are multiple ways to handle changing APIs. Some do not require abstract classes for everything. For example, if there's a method that takes parameters, rather than passing multiple parameters, have a context object. The context object can change w/o breaking method signature.

I was talking about adding completely new members to existing types. Yes, there are many changes API designers want to make and some don't have anything to do with the abstract class vs interface debate, but if the API designer wants to add a new member, abstract classes allow it and interfaces don't. Framework Design Guidelines book talks about this extensively in the "Choosing Between Class and Interface" section.
