### ISSUE TITLE
Board Review: Distributed tracing for AMQP, preview 3

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk#595]
Thank you for starting the process for approval of the client library for your Azure service.  Thorough review of your client library ensures that your APIs are consistent with the guidelines and the consumers of your client library have a consistently good experience when using Azure. 

## The Basics

Describe mechanism by which context is propagated when using AMQP, what spans are created and how they are to be linked.

* Team: ADP (all languages)
* Contacts: lmolkova@microsoft.com, johanste@microsoft.com

## About this client library
The scope and technical details of the proposal are here: 
https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#file-minimal_instrumentation-md

**Comment by adrianhall** [comment]
Notes from meeting:

* This will apply to Event Hubs, Service bus, and more than likely Queues
* Does it support MQTT?  No - there are no headers in MQTT.  IoT does some stuff here, and they are looking to improve the story
* We will use Diagnostic-Id header instead of traceParent until the new spec is ready
* Isn't link expensive?  In batches, links make sense and are useful, despite the expense.  We should measure and determine if it becomes a problem.
* In fire-and-forget callback situations, it seems like a recipe to have a lot of small spans.  Might be better to leave this for await situations with back-pressure.
* For the processing part, there is very little control over it.  We can just give the user some context.
* Can you send to close-span?  No
* Is receiving spans useful?  Probably not due to sampling - a metric would be better to expose.

Actions:
* @johanste will produce PR for distributed tracing in AMQP / Messaging.
