### ISSUE TITLE
Board Review: Storage ADLS

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk#629]
## The Basics

* Service team responsible for the client library: Storage
* Link to documentation describing the service: @seanmcc-msft to provide a link
* Contact email (if service team, provide PM and Dev Lead): Sean McCullough and Peter Marino

## About this client library

* Name of the client library: Storage ADLS
* Languages for this review: .Net first, then map to other languages
* Link to the service REST APIs: Storage ADLS
* Link to the reference documentation: https://microsoft-my.sharepoint.com/:w:/p/seanmcc/ESIRXEIpSDRPsksvzL2usTEB-PoeNzqopWoTMAQTWRczjA?e=8zZGc3
* Link to several samples: Samples in the document

To ensure consistency, all Tier-1 languages (C#, TypeScript, Java, Python) will be reviewed together.  Other languages may be included as required.

## Champion Scenarios

A champion scenario is a use case that the consumer of the client library is commonly expected to perform.  Examples might be "Update Firmware", "Download a file", "Recognize faces in a list of pictures".  Champion scenarios are used to ensure the developer experience is exemplary for the common cases.  You need to show the entire code sample (including error handling, as an example) for the champion scenarios.

* Champion Scenario 1:
    * Describe the champion scenario
    * Link to the code sample

_ Repeat for each champion scenario _

## Agenda for the review

The following agenda will normally be followed:

1. Introduction to the service (10 minutes max)
2. Class Heirarchy (general) and public API surface - https://microsoft-my.sharepoint.com/:u:/p/seanmcc/EV6Ss_sxgOVGkyn0uXU8wkIBdA2Mb8pI6SHkCm1baGjeKg?e=9jdSfH
    * To ensure consistency, discuss any language then indicate how the other languages are constructed
3. Per-language exceptions and examples
4. Implementation of champion scenarios (top 3-4 only) with code in preferred language
    * Include samples as attachments for other languages - all languages under consideration must be provided

**Comment by adrianhall** [comment]
Before the end of the week, can you provide to the arch board:
 
1. A presentation that goes over the service.  Specifically:
  * Who is the feature for?  (Primarily services, primarily clients, experienced azure devs, beginners, how big is the audience, etc.)
  * What problem is the feature solving
  * How does the feature solve that problem conceptually
  Add the presentation to the issue so we keep track of it.
 
2. Upload a definition of the API somewhere where we can comment on it.  Ideally, apiview.azurewebsites.net (since KC likes that for .NET reviews and you’ve picked .NET as the initial review).  Add a link to the apiview review within the issue.
 
3. Provide sample code on how a customer would use the API to solve the problem that it is purported to solve within the issue.

**Comment by adrianhall** [comment]
Scheduled 9/19

**Comment by adrianhall** [comment]
Link to notes: (MICROSOFT INTERNAL): https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FGeneral%2FAzure%20SDK%20-%20General&wd=target%28Board%20Meetings.one%7C19375C24-42BA-455A-A479-8E59FBB01EF3%2FStorage%20ADLS%20-%209%5C%2F19%5C%2F2019%7C2B0B83AD-6E35-472A-A9A4-00CCDB6085B1%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/General/Azure%20SDK%20-%20General/Board%20Meetings.one#Storage%20ADLS%20-%209/19/2019&section-id={19375C24-42BA-455A-A479-8E59FBB01EF3}&page-id={2B0B83AD-6E35-472A-A9A4-00CCDB6085B1}&end
