### ISSUE TITLE
New environment variables for Azure Search

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk#640]
Per [the config section of the general API guidelines](https://azure.github.io/azure-sdk/general_implementation.html#service-specific-environment-variables), I'd like to propose the following new environment variables specific to Azure Search:

- **AZURE_SEARCH_SERVICE_NAME** - Sets the name of the search service for both `SearchServiceClient` and `SearchIndexClient`
- **AZURE_SEARCH_DNS_SUFFIX** - Sets the DNS suffix to use for both `SearchServiceClient` and `SearchIndexClient`. Required to support alternate cloud environments (like government/sovereign cloud environments).
- **AZURE_SEARCH_SERVICE_CLIENT_API_KEY** - Sets the api-key to use for `SearchServiceClient` only. This must be an admin key.
- **AZURE_SEARCH_INDEX_CLIENT_API_KEY** - Sets the api-key to use for `SearchIndexClient` only. Can be an admin key (for indexing/modifying data) or a query key (for any query operation). This needs to be a separate config setting because otherwise it encourages the use of admin keys for query scenarios (escalation of privilege vulnerability). Note that since many applications use multiple indexes and create/obtain index clients at runtime, this is unlikely to be used often.
- **AZURE_SEARCH_INDEX_NAME** - Used to configure the index name for `SearchIndexClient`. Since many applications use multiple indexes and create/obtain index clients at runtime, this is unlikely to be used often.

Some background to help understand the above:

- Azure Search customers create a "search service" that has a dedicated API endpoint. The service name forms the host name, and the DNS suffix depends on the cloud (.search.windows.net for Public cloud, for example; govt. cloud will have a different suffix).
- AuthN/authZ is accomplished today with API keys. Every request must have an api-key header with a valid key. There are two types of keys -- admin (read/write + admin operations) and query (read only for queries only).
- `SearchServiceClient` provides access to all the "management-like" capabilities of the customer's service (managing indexes and their schemas, synonyms, indexers, etc.). All requests sent by this client require an admin key.
- `SearchIndexClient` provides data plane access to a specific index. Write operations require an admin key; read/query operations require either an admin key or a query key (but we strongly recommend query keys in keeping with the Principle of Least Privilege).

We need to close on these to unblock implementing the config-by-environment-variable scenario in the new [Azure Search Java client library](https://github.com/Azure/azure-sdk/issues/625).

FYI @navalev @tamirkamara @jongio @millerna26 @CodeRunRepeat @ruiqiding @arv100kri

**Comment by adrianhall** [comment]
@johanste @bterlson @JeffreyRichter @JonathanGiles @KrzysztofCwalina

**Comment by JeffreyRichter** [comment]
Should the env vars be of the form "AZURE_<GroupName>_<ServiceName>_<FEATURE>"  where SEARCH is the group name and I'm not sure what the service name is for this search service?

Can an env var refer to the entire endpoint instead of just the DNS suffix? In the past constructing endpoints in code has caused problem. For example, for Storage, the endpoints can use IP addresses or CNAMEs and the construction algorithm falls apart in these cases. In addition, the construction is "magic" and reduces the ability to diagnose connection issues.

For the API key; I can live with this but it does discourage the better pattern where the app can roll over credentials in a running service. So, this encourages an anti-pattern.

If AZURE_SEARCH_INDEX_CLIENT_API_KEY and AZURE_SEARCH_INDEX_NAME are not expected to be used often, perhaps it's better not to have them at all and just set the customer up on the correct/better trajectory.

**Comment by brjohnstmsft** [comment]
@JeffreyRichter The service is just "Azure Search", and per our recent discussion with @adrianhall, the namespace is just `Azure.Search` (otherwise it would be `Azure.Search.Search`, which is redundant). I assume the same logic applies to environment variable prefixes.

We could just take the endpoint as an environment variable. Would that necessarily require doing the same in client constructors? That would be a big change from how our Track 1 SDK works, and will likely confuse our existing customers when they upgrade to our eventual Track 2 SDK. We don't support IP addresses as service names, and our construction logic is a simple string append, so I don't foresee the same issues as Storage.

I only suggested the api-key variables because there seem to be similar equivalent examples in the guidelines. If this is an anti-pattern, let's not do it.

I agree re: the index-specific variables.

**Comment by adrianhall** [comment]
These environment variables meet the guidelines as they are written today.  My concern (before I register them) was with the API_KEY requirement.

Questions from my arena:

1) Is there any reason why the DNS suffix and service name can't be combined into one?  What does the portal provide the user? (i.e. are they two separate fields?)

Perhaps (both being fully qualified names...):

* `AZURE_SEARCH_SERVICE_ENDPOINT`
* `AZURE_SEARCH_INDEX_ENDPOINT`

Also, can we combine the index name into the fully qualified name somehow (again - what does the portal provide?)

**Comment by JeffreyRichter** [comment]
Our Track2 SDKs all take the full endpoint in ctors to avoid the construction/diagnosing issues I mention. So, full endpoint is better and will be consistent with all Track 2 SDKs.
There are many things that can fail for customers building distributed applications: bad endpoints and bad authentication are 2 of the biggest potential issues. So, reducing “magic” here helps customers diagnose problems.

If the API-keys are forever static (never change), then it’s OK to have them. If they have some kind of “password” like thing in them, then it’s not OK because customers should roll-over passwords periodically.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C948cf3366acf45f6ef8d08d62e3b3b00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636747229263047172&sdata=sg%2FtzHWpscWQDr7foOSsaNrKDP5vNSHE3b72HJG8swU%3D&reserved=0>)

**Comment by brjohnstmsft** [comment]
Thanks for the questions and clarifications.

Regarding api-key, they are indeed secrets that can be rolled over, so I can see how that would be problematic. However, without them, you can't create a working client. Should this instead be a kind of pointer to an api-key stored in KeyVault? What's the story here for other services? For example, wouldn't these environment variables mentioned in the [guidelines](https://azure.github.io/azure-sdk/general_implementation.html#service-specific-environment-variables) also contain secrets?
- AZURE_SERVICEBUS_CONNECTION_STRING
- AZURE_SERVICEBUS_ACCESS_KEY
- AZURE_STORAGE_ACCESS_KEY
- AZURE_STORAGE_CONNECTION_STRING

Regarding service endpoint, good to know that it's standardized now. Our portal experience provides the endpoint as one value, so that aligns well. However, our management plane API only provides the name and not the DNS suffix. That's a gap we need to fill; I'll follow up on that with my team.

@adrianhall Regarding index endpoint, that's really just the service endpoint with a specific path appended that includes the index name. It isn't exposed directly in our portal experience, and not at all in our service API. That also seems like a gap we need to fill. That said, per @JeffreyRichter's feedback, since index clients are typically created dynamically, we could just omit this from the list of environment variables.

**Comment by adrianhall** [comment]
I agree the design guidelines around environment variables are bad examples.

Based on this, it sounds like:

* `AZURE_SEARCH_ENDPOINT`

would be enough, since that is all that is provided by the portal?   This can then provide the default endpoint for SearchServiceClient.  The question is how the customer would be able to construct the required endpoint for the SearchIndexClient.  If it can be divined from the search endpoint, then we can add an `AZURE_SEARCH_INDEX_NAME` so that it can be constucted, or it can be a different endpoint (does that even make sense in the context of what the customer is doing?)

**Comment by brjohnstmsft** [comment]
If we only have `AZURE_SEARCH_ENDPOINT`, how does the `SearchServiceClient` get its api-key?

The index endpoint can always be determined from the service endpoint plus index name, like this:

`$AZURE_SEARCH_ENDPOINT/indexes('$AZURE_SEARCH_INDEX_NAME')`

or

`$AZURE_SEARCH_ENDPOINT/indexes/$AZURE_SEARCH_INDEX_NAME`

if you don't like OData.

Regarding `SearchIndexClient`, there are two scenarios:

1. The app does only index-level operations. In this case, the expectation is that it will create a `SearchIndexClient` for each index that it uses (perhaps pooling them if there are many indexes). Which reminds me -- The reason index name is a separate constructor parameter and property of `SearchIndexClient` in our Track 1 SDK is precisely to support this pooling scenario.
2. The app does both index-level and service-level operations (typical for a demo app or sample app, or an app that handles provisioning of indexes as part of its startup logic). For this scenario, we provide a helper method in our Track 1 SDK to create the `SearchIndexClient` from the `SearchServiceClient`, which has the added benefit that we can pass along some HTTP configs like timeouts, along with the message handler chain. Here it is for reference: https://github.com/Azure/azure-sdk-for-net/blob/e47e0952855c84c7a2eae9f141a6282091fcebc8/sdk/search/Microsoft.Azure.Search/src/IndexesGetClientExtensions.cs#L26

**Comment by JeffreyRichter** [comment]
Let me give some background/thinking...

Connections strings are a good way for customers to get started using/learning about a service. But, they are not a good way for customers to work with a service in the long run. The problem is that connections strings typically conflate multiple unrelated concepts together such as an endpoint and some credential information and some services’ connection strings also include configuration settings (like # of retries). This is bad design but offer a convenient way to get started.

Ideally, connection strings would never have existed and there would be a clean separation of the concepts. For a client of a service, the endpoint and options are typically static and the secrets are not as they should be rolled over periodically. Our team must support scenarios where customers do no use connection strings as this is the more proper way for customers to work with a service and this allows secret rollover. We have decided that our Track 2 libraries CAN also support connection strings to assist customers with “quick start” scenarios. For the record, the client libraries ONLY support connection strings if the Azure portal exposes them for a given service. If the portal doesn’t expose a connection string for some service, then that client library will not support connection strings either.

So, you should think about the customers of your service, how you think they’re going to use your service, and how it is for a customer to get credentials to talk to your service. Many Azure services are supported Azure Active Directory now and there is no way to put these credentials into a connection string at all and this also makes connection strings almost useless going forward – another reason to start weening customers off of them.

For example, if you think your service is mostly accessed by command line tools (as opposed to a long-running service), then a connection string might make more sense and the tool starts, uses the connection string, and then the tool terminates. In this scenario, the tool doesn’t run long enough to want to roll over secrets.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C948cf3366acf45f6ef8d08d62e3b3b00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636747229263047172&sdata=sg%2FtzHWpscWQDr7foOSsaNrKDP5vNSHE3b72HJG8swU%3D&reserved=0>)

**Comment by brjohnstmsft** [comment]
@JeffreyRichter Thanks for the background. We have never supported connection strings and don't intend to start. Our customers typically use Azure Search from web or mobile applications. Credential management is a problem for our customers. Since our api-keys are secrets, we basically put all the complexity of managing and rolling them on our customers, which is less than ideal. In the future, we will likely address this by adding support for AAD and MSI, but in the meantime we need to support the current key-based authentication scheme.

I imagine that our customers rollover secrets the way that we do. Being a cloud app itself, Azure Search has enough redundancy that we can restart processes with new configs that contain updated secrets -- no need to rollover in a running process.

This leaves me with a few questions before we can close on this:

1. Should we even have api-key environment variables?
1. If not, what happens if a customer sets the endpoint variable and then tries to create a `SearchServiceClient`? Do we have a constructor that just takes the api-key? Or do we not bother having environment variables at all?

**Comment by JeffreyRichter** [comment]
Environment variables should enable a convenience only; they must not be the only way to accomplish a task.

In other words, your client type must have a constructor that takes an endpoint and credentials. We offer an EnvironmentCredential type that the customer can choose to use and, if they do, it can read environment variables to populate the credentials. So, the customer explicitly chooses to use environment variables in their source code. This makes things debuggable as the customer opts into the"magic". They can also see how the environment variables populated the EnvironmentCredential object in a debugger if they need to verify that this worked correctly.

Maybe you want to abandon the environment variables path (for now) as this can't be the main way to initialize a client object. Then, if customers demand it, you can always add it later.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C82df4ff9e5ae46a5095908d7345e957b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637035453166233741&sdata=4GnkpFUKxlZXGXFr6oQo5GB%2FFNIbDXIZDXUij0q4AEE%3D&reserved=0>)

________________________________

**Comment by brjohnstmsft** [comment]
@JeffreyRichter So far there's been no customer demand for this, and I see it's a "MAY" in the guidelines, so let's drop this for now. Closing the issue.
