### ISSUE TITLE
Board Review: Event Hubs 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk#747]
## The Basics

* Service team responsible for the client library:   Azure Event Hubs
* Link to documentation describing the service:    
  - [Azure Event Hubs in general](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about)
  - [Azure Event Processor Track 1](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-event-processor-host)
* Contact (if service team, provide PM and Dev Lead): SeongJoon Kwak, Javier Fernandez & Shubha Vijayasarathy

## About this client library

* Name of the client library: Event Hubs
* Languages for this review: C#, TypeScript, Java, Python
* Link to the service REST APIs: None

## Artifacts required (per language)

We use an API review tool ([apiview](https://apiview.azurewebsites.net)) to support .NET and Java API reviews.  For Python and TypeScript, use the API extractor tool, then submit the output as a Draft PR to the relevant repository (azure-sdk-for-python or azure-sdk-for-js).

### .NET

The .NET implementation is in-process at the time of submission, with some details continuing to be tweaked as part of the development process.  As a result, the product code does not yet match the intended final shape of the proposed API surface.

As a reference for review and for development, a skeleton of types has been prepared with their intended API has been prepared and should be considered a living document and the most up to date source of truth for the intent.  

To assist with this review, the skeleton was converted into a stub library and has been uploaded to API View, with the contents representing the known API surface as of Wednesday, November 13 at 11am EST.

**Resources:**

- [Target Customer Segments](https://gist.github.com/jsquire/36c0198e0898f203168e70bc15816d2c#target-customer-segments)
- [Champion Scenarios](https://gist.github.com/jsquire/36c0198e0898f203168e70bc15816d2c)
- [API Skeleton](https://gist.github.com/jsquire/3fadc1ea57594c31f1c39366c0d7b530)
- [API View](https://apiview.azurewebsites.net/Assemblies/Review/8dad92de21454b448f0cd26ace097106)

### Java

* Upload JAR to API View.  [Link](https://apiview.azurewebsites.net/Assemblies/Review/f198dbfb5e9e46c48ab1a1aa8cf633fe)
* [Link to samples](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs) for champion scenarios:

### Python 

* Upload the api as a Draft PR.  Link to PR: https://github.com/Azure/azure-sdk-for-python/pull/8595
* Link to [samples](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhubs/samples) for champion scenarios:

### TypeScript 

* Upload output of api-extractor as a Draft PR.  Link to PR:
https://github.com/Azure/azure-sdk-for-js/pull/6165 
* Link to [samples](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/eventhub/event-hubs/samples) for champion scenarios:

**Comment by adrianhall** [comment]
@ramya-rao-a - what are we reviewing here?  It isn't clear.  I get event hubs processor.  Are we reviewing a design proposal (if so, what is it?), or an API (if so, where are they?)

**Comment by ramya-rao-a** [comment]
cc @jsquire,  @srnagar

**Comment by ramya-rao-a** [comment]
@adrianhall We are reviewing the API for the entire Event Hubs library as the whole thing is undergoing a massive change. It is not a proposal. The proposal has already been made and individual architects and the service team are onboard with it.

**Comment by mayurid** [comment]
@YijunXieMS and @yunhaoling

**Comment by richardpark-msft** [comment]
Javascript: API review PR with our .md file
https://github.com/Azure/azure-sdk-for-js/pull/6165/files

**Comment by adrianhall** [comment]
Link to recording (MS Only): https://web.microsoftstream.com/video/50b1a5cd-7899-455b-abc2-8d97ab4be873

JavaScript Review:
* Why couldn't we use a default consumer group name.  
    * It's integral to the event hubs philosophy - service group strongly believes it should not be hidden
* What is the behavior of the system when rate of events exceeds the processing time?  
    * It depends on whether you are awaiting or not.  The next event is received when the function completes.
    * Throttling concerns around this - could use a 3P library, multiple partition IDs.
    * There should be a sample on how to do with this.
* Concern that the .NET API has the consumer group at the client level vs. the subscriber - this is a consistency issue.
    * This has been requested by the service team.  On the connection level, we want to load balance across the service nodes.
    * (JS) It feels like a reasonable conceptual model.
    * Should we rename this to EventHubConsumerGroupClient - not a good reception.
    * **CONSENSUS**: Move consumer group name to the client constructor  
* Should `ownerLevel` also be placed on the client constructor?
    * No - it should not.  `ownerLevel` will remain in the options bag for `subscribe()`
    * .NET/Java currently sets it at the client constructor, needs to move. (PARK FOR NOW for JAVA & .NET)
* There is a potential pit of failure in the checkpointing, where the checkpoint is done after every event, which isn't probably what is needed.
    * Possible docs and/or samples use.  It's really about the customers needs.
    * Is time based more appropriate?  Potentially, but the displayed is the most common way.
    * If we are thinking time-based is appropriate, there may be complications. (need customers)
    * We might need out-of-context checkpointing.  Context is partition specific.
*  Merits of event vs. batch of events in the processEvent?  Is this is a good or bad thing?
    * This really needs to be customer focused, however Brian prefers batching; Johan thinks batching is a way of simplifying checkpointing, so it needs a lot more control for the developer.
    * There is a concurrency problem really - that's possibly the canonical issue
    * A lot of customer scenarios have ordering issues.  The unit of concurrency is the partition.
    * Batching provides a lot of nuance that we have to expose.
* Do we move the partition manager to the client constructor? (Used for checkpointing, etc.)
    * Load balancing happens inside the consumer group, so they should be paired.
    * **CONSENSUS**: Move partitionManager to the consumer client constructor as an overload with a positional parameter.
* Should the InMemoryPartitionManager be public?  No.  But what about testing?  Hide for now.
    * Don't publish samples with InMemoryPartitionManager.
    * Re-visit after GA
* Sending batches - we need a sample that demonstrates streaming sender
* Sending individual event - JS would like a buffered sender.  service teams wants to discourage sending individual names.
* What is the encoding on a send?  body is just a bunch of bytes.

JS API Review:
* `consumerGroupName` -> `consumerGroup`
* Combine the websocket related options; grouping for corner cases is a good thing.
* Discuss internal constructor on EventPosition (potentially with Python) - offset vs. sequenceNumber
* isInclusive is only needed for fromSequenceNumber - remove in fromOffset
* On updateCheckpoint - make sequenceNumber optional. (Restructure so offset is first)
* PartitionManager - should we rename it?  Yes - to `CheckpointStore` (align on other languages)
* `eTag` -> `etag`
* Don't export `TokenType` (Richard to confirm)

Python Review:
* A lot of JS review comments are applied to Python
* `event_hub_path` -> `event_hub_name`
* create_batch takes a list of events.  Should the other languages support this?
    * this seems strange to BT, since it doesn't always work.
    * Option to return a batch + extra items might work.
    * Return a list of batches (not good because the last batch might be sub-optimal)
    * Remove option to create batch with events - deal with it post-GA
* In receive, keept initial position, and make it a potential dictionary
   * Take conversation offline with service team.  If dynamic case is needed, have customer validation.
* batching try_add -> may replace name with append since there is a good idiomatic usage point
* Remove the EventPosition, pending the offset/sequence number interop discussion
* EventHubSharedKeyCredential -> EventHubsSharedKeyCredential (check for consistency)

**Comment by adrianhall** [comment]
Recording: (MSONLY): https://msit.microsoftstream.com/video/868ad84c-ca32-4ef2-aa24-f014ac6f77cd

Java review:

* Add comments in synchronous classes about using synchronous clients.
* Make sure there are samples for async and synchronous.
* How many samples should we have?
    * Which high-level scenarios?
    * Add printing out of event body in samples.

* Change from receive(string, eventposition) to receiveFromPartition(string, eventposition)
* Can processError be optional? Doesn't seem so.
    * What happens if an error occurs on that EventProcessorClient that is fatal? Do we keep looping and trying forever?
    * Add a production end-to-end sample so we can conpare or have a reference to it. Like what we expect users to do in this error handler.

* Consider adding synchronous receiver that receives from all partitions
* If a receiver crashed, we can restart it from where we had before before it crashed?

* SharedCredential checked exceptions and remove token validity

**Comment by adrianhall** [comment]
Note: .NET is different from Java, which in turn is different from JS and Python

.NET Review:
- The extensibility model has not been designed, thus the event hub processor is linked to blobs.
- Should we propagate errors from the `ProcessErrorAsync` to the top level?
    -  For discussion details, review the video as the discussion was wide-ranging
    - `StartProcessingEventsAsync` only blocks for long enough to get started.
    - no change to design is required as a result of the discussion
- We need a good E2E sample that shows off best practices for error handling
- `cancellationToken.Cancel()` seems weird to KC.  This design has come full-circle.
    - If start is blocking, cancel applies.
- Float idea: ProcessEventsAsync that blocks with a cancellation, so we can surface the exceptions
    - KC - there are cons to this approach as well.  Stick with what we have.
    - Keep cancellation source, but it just applies to just the start process.
    - StopProcessingAsync() should take a cancellation token.
- Rename consumerOptions -> clientOptions
- Up to developer on whether to delete constructor 3 
- Remove the `Close` method.
- KC - Review the guidelines for Dispose/Close.
- `ReadEventsAsync()` - can it take a map?  Like the idea, but not for GA.
    - Java and .NET should discuss offline to be consistent 
- `ClosingPArtitionAsync` property - as is, this is ok, but needs to deal with cancellation token.
    - Prefer to close with the BCL team.
- `args` -> `eventArgs`
- Generally, async methods should take cancellation token.
- Rename `TransportType` type to `EventHubTransportType`
- Rename `ReadOptions` type to `ReadEventsOptions`
- Remove Processor prefix from `ProcessorIdentifier`
- Rename `RetryOptions` to `EventHubsRetryOptions` if you can't use the same type in Azure Core
- Remove `SharedAccessKeyName` from the `EventHubSharedKeyCredential`
    - Can we punt for all languages?  Let's review it offline, with look to internalize it.
- Rename `RetryMode` to `EventHubsRetryMode`

More stuff that will be handled offline.
