### ISSUE TITLE
Change Request: Non-Seekable Streams

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk#759]
## The Basics

* Which design guideline is affected?

https://azure.github.io/azure-sdk/general_azurecore.html#retry-policy

* Which target languages are affected?

All

* Describe the change:

Our APIs, across all languages, should support both seekable and non-seekable streams.

## Reasoning

Currently, most APIs which execute HTTP operations require seekable streams.  If a caller has a non-seekable stream, they are responsible for buffering it into a seekable stream before calling our API.

Instead, I believe our APIs should support both seekable and non-seekable streams.
If the stream is seekable we disable internal buffering for the best performance, and if the stream is non-seekable we internally buffer as necessary.  I think this provides the best of both worlds.

If we cannot determine if a stream is seekable (as may be the case in Java Flux<ByteBuffer>), we should default to assuming the stream is not seekable, and add a parameter for the caller to assert the stream is seekable.  Similarly, if we want to allow a non-seekable stream without internal buffering, we should add a parameter to disable buffering (and retries).

**Comment by JeffreyRichter** [comment]
Let me add something for I forget: [PUT BLOB](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) and [PUT BLOCK](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) require the Content-Length header. If the stream is seekable, then the customer doesn't have to pass the length to the method; instead, the method can ask the stream for its length and use that for the Content-Length header. This simplifies the method's signature and customer experience. Accepting a non-seekable stream will require this additional parameter and trusts that the stream has at least as much content as the customer passed into the method.

**Comment by adrianhall** [comment]
- This is a problem for what the customer feed us - most calls that do uplaods require a seekable stream.
- Seekable streams are files and memory blocks.  Non-seekable streams are network streams.
- Some APIs (e.g. keyvault) buffer the stream and give back a seekable stream.

Either:
a) Always assume it is not seekable, and we do the buffering.
b) Always assume it is seekable, and make the user do the buffering.
    - There are standard libraries for doing this
c) Document what we do and let the user deal with it.
d) Use a stream factory to deal with restartable but not seekable streams.

Based on arch board discussions, .NET, Python, and JavaScript may not have an issue - all three have a way to deal with this (even if suboptimal in some cases).  It's a case of how big an issue this problem is and is it worth solving?

However, Java has an issue. @JeffreyRichter and @JonathanGiles will discuss with the Java team to design a solution that works for this situation to avoid data corruption.

Can we give guidance in documentation now on how customers should use our API in these cases?

We need to document what happens when an API that produces or consumes a stream.  In particular, we should describe what sort of stream is expected or produced.

**Comment by JeffreyRichter** [comment]
FYI: I discussed with people in the room and the checksum idea is no good – my mistake.
So, we have no good solution for java. If anyone wants to try to brain storm some up, I’m happy to be involved. But right now, I got nothing that can be done efficiently enough to make it palatable.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Ftraining%2Fdistributed-cloud-apps%2F&data=02%7C01%7Cjeffreyr%40microsoft.com%7C948cf3366acf45f6ef8d08d62e3b3b00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636747229263047172&sdata=sg%2FtzHWpscWQDr7foOSsaNrKDP5vNSHE3b72HJG8swU%3D&reserved=0>)

**Comment by adrianhall** [comment]
Can you add this comment to the issue.  We will leave this in Jonathan’s hands

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JeffreyRichter** [comment]
FYI: I discussed with people in the room and the checksum idea is no good – my mistake.
So, we have no good solution for java. If anyone wants to try to brain storm some up, I’m happy to be involved. But right now, I got nothing that can be done efficiently enough to make it palatable.

**Comment by annelo-msft** [comment]
Sharing recap to document the outcome in this issue:


The board had a lively discussion on the topic.  Thanks to @mikeharder for introducing the topic and providing the input.

In the end, we decided that Java was the only language that had immediate needs here.  For the other languages, we will take a wait-and-see approach.  For Java, @JonathanGiles  will work with @JeffreyRichter  and the Java feature team to come up with potential solutions to avoid data corruption.

@lmolkova FYI
