### ISSUE TITLE
Consider office hours for architects

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk#863]
We've had several requests for 1:1 consultations, so I think it's a good idea to discuss an office hours arrangement or similar consulting request.

Copying @petermarcu for input on what he thinks of the idea, since it requires taking more of the architects time.

**Comment by JonathanGiles** [comment]
I'm not against this, but I don't understand where it fits in either. Maybe it is because I'm remote, but everyone knows very well that I'm always available, and a very large chunk of each day is dealing with these kind of enquiries. I can't imagine additional 'office hours' time will do much more to help here, but perhaps I'm overlooking something...

**Comment by adrianhall** [comment]
The idea is that we have posted a "need help?  Join our office hours, where an architect is available to answer your questions".  You may be dealing with these enquiries on a daily basis for service teams that are working with us, but we need to respond to service teams that are not working with us yet as well.

**Comment by JonathanGiles** [comment]
Got it - sounds reasonable.

**Comment by adrianhall** [comment]
Arch Board:

- Worry is that teams will overwhelm the architects, because it's not a single question - it's a full review.
- Book a weekly meeting @ 12 or 1pm, architects bring lunch.
- Advertise on adparch-interest on a regular basis.
- Happy for anyone to come to the office hours.
