### ISSUE TITLE
Automate Azure Service Fabric testing

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#901]
Tracking issue for step-by-step instructions for how to manually run e2e tests for Azure Service Fabric hosted environments for each of the azure-sdk-for-* languages.  This issue will be used by our Vendor team for manually running tests in this scenario, and will be tracked on the EngSys backlog for eventual automation.

Assigning to @mccoyp who will create the initial instructions.  Other SDK languages will be appended to this issue as further comments.

**Comment by joshfree** [comment]
Reactivating test enhancement issue and assigning to @mccoyp who is driving the service fabric work in Azure.Identity

**Comment by mccoyp** [comment]
I have a [personal repository](https://github.com/mccoyp/service-fabric-managed-identity-test) with a sample for running manual tests on this. It's still under development but the sample should hopefully be complete by early next week.

It currently uses applications that request tokens using REST, but I'm in the process of updating the sample to

1. Sort out bugs with having both applications deployed concurrently
2. Use Azure.Identity's new ServiceFabricCredential to request these tokens instead

**Comment by mccoyp** [comment]
The sample now references the correct `ManagedIdentityCredential` (and underlying `ServiceFabricCredential`) to verify the Service Fabric managed identity app behavior. It should be sufficient as a manual test for Python's implementation.

The remaining work would be to:

1. Reference the main [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python) repository once the new credential is merged. The sample currently points at my personal fork.
2. Use the team's existing [Dockerfile](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/managed-identity-live/Dockerfile) for live managed identity tests instead of manually verifying with a Flask app. This would make the tests more easily translatable into other languages, but I'm not yet sure how to access the test output from the deployed SF app to make this possible.

**Comment by mccoyp** [comment]
# Manual Testing for Service Fabric Applications using Managed Identity with Azure.Identity

Setup for a Service Fabric cluster and two apps, used for testing managed identity using Azure.Identity.

`sfmitestsystem` and `sfmitestuser` are mock applications that use Azure.Identity's `ServiceFabricCredential` to request and verify Key Vault access tokens. The former application uses a system-assigned managed identity to do so, and the latter application uses a user-assigned managed identity.

The `ResourceManagement` directory contains Azure resource templates for creating a Service Fabric cluster to host these applications as well as the application templates.

## Environment Requirements

> **Note:** All Azure resources used in the sample should be in the same region & resource group. This includes a managed identity, Key Vault, Service Fabric cluster, Azure Container Registry, and storage account.

- This sample assumes that Visual Studio 2019 is being used in a Windows environment.
- This sample requires access to an Azure subscription and required privileges to create resources.
- [Powershell and the Az library are needed to run the deployments in the sample.](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps)
- [Azure CLI is used to deploy some resources.](https://docs.microsoft.com/cli/azure/install-azure-cli?view=azure-cli-latest)
- Docker is needed to build and push the sample containerized service. Docker should be using Linux containers for building the application images, but it should be using Windows containers when packaging the Service Fabric applications in Visual Studio.

## Setting up Prerequisite Resources

### Create a resource group

From a command prompt window, run
```
az group create -n $RESOURCE_GROUP --location $LOCATION
```

### Create a user-assigned managed identity

From your command prompt window, run
```
az identity create -g $RESOURCE_GROUP -n AdminUser
```

Make note of the identity's principal ID, to use in the next step. Also make note of its client ID for a later step.

### Create a key vault, certificate, and secret

Create your key vault:
```
az keyvault create -g $RESOURCE_GROUP -n $KEY_VAULT_NAME --sku standard
```

After creating the vault, create a self-signed certificate in it using the [Azure Portal](https://azure.portal.com/). You'll need to insert some of this certificate's properties into the cluster template later on.

Finally, create a secret in the key vault. It can have any name (e.g. "TestSecret") and any value (e.g. "TestValue"). This secret will just be accessed by the Service Fabric applications to verify that they can access a resource and read contents using their identities.

### Create an Azure Container Registry

From your command prompt window, run
```
az acr create -g $RESOURCE_GROUP -n $ACR_NAME --admin-enabled --sku basic
```

## Walkthrough

### Clone this repository

From a command prompt window, run
```
git clone https://github.com/mccoyp/service-fabric-managed-identity-test.git
cd service-fabric-managed-identity-test
```

### Create and publish a Docker image for each application

For this manual test, each application will use a Docker image to run managed identity tests. To make these images available to Service Fabric, you need to build and publish them by using the Dockerfiles in this sample.

First, you'll need to update the applications to target the correct resources.

1. Open `sfmitestsystem/sfmitestsystem-app/Dockerfile`.
2. Replace `<your vault URL>` with the vault URI of the key vault you created.
```Dockerfile
ENV AZURE_IDENTITY_TEST_VAULT_URL=<your vault URL>  # looks like https://<vault name>.vault.azure.net/
```
3. Open `sfmitestuser/sfmitestuser-app/Dockerfile`.
4. Replace `<your vault URL>` with the vault URI of the key vault you created, and replace `<AdminUser client ID>` with the client ID of the managed identity your created earlier.
```Dockerfile
ENV AZURE_IDENTITY_TEST_VAULT_URL=<your vault URL>  # looks like https://<vault name>.vault.azure.net/
ENV AZURE_IDENTITY_TEST_MANAGED_IDENTITY_CLIENT_ID=<AdminUser client ID>  # found in the managed identity overview
```

Now, build the images and push them to Azure Container Registry.

1. Ensure Docker is running and is using Linux containers.
2. Authenticate to ACR:
```
az acr login -n $ACR_NAME
```
3. Build the images:
```
docker build --no-cache -t $ACR_NAME.azurecr.io/sfmitestsystem sfmitestsystem/sfmitestsystem-app
docker build --no-cache -t $ACR_NAME.azurecr.io/sfmitestuser sfmitestuser/sfmitestuser-app
```
4. Publish the images:
```
docker push $ACR_NAME.azurecr.io/sfmitestsystem
docker push $ACR_NAME.azurecr.io/sfmitestuser
```

### Package each application

Your Service Fabric cluster will target each application by referencing a `.sfpkg` in a storage account you will create in the next section. First, we need to create these packages using the Visual Studio solutions provided in `sfmitestsystem` and `sfmitestuser`.

1. Open `sfmitestsystem/sfmitestsystem.sln` in Visual Studio 2019.
2. In `sfmitestsystem/ApplicationPackageRoot/sfmitestsystemfrontPkg/ApplicationManifest.xml`, fill in the values for your Azure Container Registry name and password in
```xml
<RepositoryCredentials AccountName="<ACR_NAME>" Password="<found in Access keys page of registry in Portal>" PasswordEncrypted="false"/>
```
3. In `sfmitestsystem/ApplicationPackageRoot/sfmitestsystemfrontPkg/ServiceManifest.xml`, replace `{ACR_NAME}` with your Azure Container Registry name in
```xml
<ImageName>{ACR_NAME}.azurecr.io/sfmitestsystem</ImageName>
```
4. [Build a package for the application](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-package-apps#configure).
5. Go to the location of the package in File Explorer, select all items in the Debug folder, and compress them into a zip file.
6. Rename the zip file `sfmitestsystem.sfpkg`.
7. Repeat the above steps for `sfmitestuser`, replacing all instances of "system" in the instructions with "user".

### Deploy a managed identity-enabled cluster

At the time of writing, Service Fabric clusters must be deployed using the Azure Resource Manager in order to enable managed identity. Provided is a cluster ARM template that can be used to create a managed identity-enabled cluster once some required fields are completed. The template uses the cluster certificate provided by your key vault, creates a system-assigned identity, and enables the managed identity token service so deployed applications can access their identities.

To use the provided template:

1. Open `ResourceManagement/cluster.parameters.json` and complete the fields `clusterLocation`, `adminUserName`, `adminPassword`, `sourceVaultValue`, `certificateUrlValue`, and `certificateThumbprint`. Field descriptions will describe how they should be completed.
2. In `ResourceManagement/cluster.parameters.json`, change all instancse of `sfmi-test` to a unique name, like `<myusername>-sfmi-test`. Also, change the values of `applicationDiagnosticsStorageAccountName` and `supportLogStorageAccountName` to be similarly unique, but without hyphens. This will help ensure the deployment resource names do not conflict with the names of other public resources.
3. Start the deployment by running from your Powershell window in the `ResourceManagement` directory:
```powershell
Connect-AzAccount
Select-AzSubscription -Subscription $Subscription
New-AzResourceGroupDeployment -TemplateParameterFile ".\cluster.parameters.json" -TemplateFile ".\cluster.template.json" -ResourceGroupName $ResourceGroupName
```

This will begin deployment of a Service Fabric cluster, as well as other necessary resources: a load balancer, public IP address, virtual machine scale set, storage account, and virtual network.

### Upload the application packages to a storage account

Two storage accounts were actually created in the previous step, but only one needs to store the `.sfpkg` files for the applications. Go to your resource group in the [Azure Portal](https://azure.portal.com) and open the storage account with the name corresponding to `applicationDiagnosticsStorageAccountName` from the previous step. Go to the "Containers" page and create a new container named "apps" -- be sure the set the public access level to Blob.

Open the apps container and upload the `.sfpkg` files you created earlier in the walkthrough. The container should now contain `sfmitestsystem.sfpkg` and `sfmitestuser.sfpkg`. Keep this page open to complete the next step.

### Deploy the applications

This sample also provides templates for deploying Service Fabric applications with Powershell.

To use the provided templates:

1. Open `ResourceManagement/sfmitestsystem.parameters.json` and complete the fields `clusterName`, `clusterLocation`, and `applicationPackageUrl`. `clusterName` and `clusterLocation` should match the name and location of the cluster you deployed earlier in the walkthrough. `applicationPackageUrl` is the URL of the `.sfpkg` you uploaded to a storage account in the previous step. To find the URL, click on `sfmitestsystem.sfpkg` in the Portal to view its properties.
2. Open `ResourceManagement/sfmitestuser.parameters.json` and complete the same fields, using the URL of `sfmitestuser.sfpkg` for `applicationPackageUrl`.
3. Start the deployment by running from your Powershell window in the `ResourceManagement` directory:
```powershell
New-AzResourceGroupDeployment -TemplateParameterFile ".\sfmitestsystem.parameters.json" -TemplateFile ".\sfmitestsystem.template.json" -ResourceGroupName $ResourceGroupName
New-AzResourceGroupDeployment -TemplateParameterFile ".\sfmitestuser.parameters.json" -TemplateFile ".\sfmitestuser.template.json" -ResourceGroupName $ResourceGroupName
```

### Give the applications access to your key vault

If the applications were accessed now, they would report an error. This is because their managed identities don't have permission to access secrets in the key vault you created. 

To grant them access:

1. Go to your key vault in the [Azure Portal](https://azure.portal.com).
2. Go to the "Access Policies" tab and click the "Add Access Policy" button. Select the secret management access template.
3. Click "None selected" to select a principal. Search for the name of your cluster, and an `sfmitestsystem` entry should appear in the list -- select this principal to give `sfmitestsystem`'s system-assigned managed identity access to your vault.
4. Click "Add" to add the access policy, and repeat steps 2 and 3. This time, search for the name of the user-assigned identity you created (`AdminUser`) for your principal. This will give `sfmitestuser`'s user-assigned managed identity access to your vault.
5. Remember to click "Save" at the top of the access policies page to submit these changes.

### Verify that the applications work

Once running on your cluster, the applications should each perform the same task: using a `ManagedIdentityCredential` to view the properties of your key vault's secret. One uses a system-assigned managed identity to do so, while the other uses a user-assigned managed identity. To verify that they have each done their job correctly, you can access the application logs in your cluster's Service Fabric Explorer page.

Verify in a browser:

1. Navigate to `http://<cluster name>.<location>.cloudapp.azure.com:19080/Explorer` (e.g. `http://sfmi-test.westus2.cloudapp.azure.com:19080/Explorer`).
2. Present the certificate you created in your key vault. You'll need to download the certificate from the [Azure Portal](https://portal.azure.com/) from your vault's Certificates page and [import it into your web browser](https://docs.digicert.com/manage-certificates/client-certificates-guide/manage-your-personal-id-certificate/windows-import-your-personal-id-certificate/google-chrome-import-your-personal-id/).
3. In the Explorer, you should see the applications running under the Applications tab. Otherwise, you may need to double check your deployment process.
4. Under the Nodes tab, expand each node tab to see if it hosts an application ("fabric:/sfmitestsystem" or "fabric:/sfmitestuser").
5. When you find an application entry, click the +-sign by the name to expand it. There should be a "code" entry -- click on that to bring up a page that has a "Container Logs" tab.
6. Go to the "Container Logs" tab to see the test output. The tests will re-run every so often, so you may have to watch the page for a short while to see the output. Verify that `test_managed_identity_live` shows `PASSED`.

**Comment by mccoyp** [comment]
The instructions above still reference my personal repository for now, but they should be more translatable to other languages since a web app is no longer necessary. The tests are run using an adaptation of the Python team's [Docker image](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/managed-identity-live/Dockerfile) for live managed identity testing -- other languages should have an analog of this to reference.

**Comment by JosueJoshua** [comment]
Hi @mccoyp ,it would be fail when `Deploy a managed identity-enabled cluster`, because the file arm-templates/cluster.template.json use passwords to deployment.
It will be work when I try to update ARM templates with SSH.

Error message:
![image](https://user-images.githubusercontent.com/24564161/105826491-c4e98380-5ffb-11eb-9ba4-e7c67f901480.png)

**Comment by mccoyp** [comment]
That's interesting -- I don't remember ever needing an SSH key to deploy the ARM template. I'll look into this and try to track down the issue. Thank you for bringing this up!

**Comment by mccoyp** [comment]
The testing instructions above have been updated to describe how to provide a public SSH key when deploying the cluster template. It turns out that this requirement is new for security reasons, but is currently only enforced on Microsoft-internal subscriptions. This is easy to accommodate though, and this sample will likely only be used internally, so I've updated the sample to make providing an SSH key the default.
Until the PR is merged, the (relatively few) changes can be implemented locally after cloning the repository to resolve the issue.

**Comment by KarishmaGhiya** [comment]
@mccoyp How did you generate the public SSH key to put in the `arm-templates/cluster.parameters.json` The instructions only state to find the key from the .pub file. But doesn't state where.

**Comment by mccoyp** [comment]
@KarishmaGhiya generating an SSH key will depend on the environment, so I didn't include any specific steps for doing so in the sample. For Windows 10, I followed the instructions [here](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#user-key-generation) -- using the `ssh-keygen` command in the command prompt will create an `[ssh-key]` file and `[ssh-key].pub` file in the user's .ssh directory.

**Comment by catalinaperalta** [comment]
For testing Go follow all the same instructions as mentioned above for Python and simply replace the dockerfiles with the below:

```
FROM alpine/git as clone
RUN git clone https://github.com/Azure/azure-sdk-for-go.git --single-branch --branch main --depth 1 /azure-sdk-for-go

FROM golang:1.13-alpine
COPY --from=clone /azure-sdk-for-go /azure-sdk-for-go
WORKDIR /azure-sdk-for-go/sdk/samples/azidentity/manual-tests/managed-identity/service-fabric

RUN go get -u github.com/Azure/azure-sdk-for-go/sdk/azidentity
RUN go get -u github.com/Azure/azure-sdk-for-go/sdk/azcore

CMD [ "go", "build", "./main.go" ]

CMD [ "go", "run", "./main.go" ]
```

**Comment by Menghua1** [comment]
@mccoyp, @joshfree  For python, after executing all the steps according to the above [python instructions](https://github.com/Azure/azure-sdk/issues/901#issuecomment-715604282), the test `test_managed_identity_live` shows `FAILED`. Please help check this error. The error details are as follows:
![image](https://github.com/Azure/azure-sdk/assets/111940661/ef8fc6f4-cf85-4e46-929b-b922e5d3d764)

**Comment by mccoyp** [comment]
@pvaneck @xiangyan99 would you be able to take a look? We should probably enable verbose logging for these tests since reading the output can be difficult.

@Menghua1, was that the only output you were able to see? Does the page load a specific error response further down in the test summary?

**Comment by joshfree** [comment]
Filed this python specific issue in the python repo here: https://github.com/Azure/azure-sdk-for-python/issues/31789

**Comment by v-jiaodi** [comment]
>@Menghua1, was that the only output you were able to see? Does the page load a specific error response further down in the test summary?

@mccoyp  More error messages are as follows：

![image](https://github.com/Azure/azure-sdk/assets/80496810/35adab69-6713-4a22-bf1a-7f4beb0e2614)


In addition, according to the [python instructions](https://github.com/Azure/azure-sdk/issues/901#issuecomment-715604282), 
![image](https://github.com/Azure/azure-sdk/assets/80496810/ee844c81-2460-4aed-8378-685dec28b274)

When the above command is executed, no value regarding `objectId` is obtained.

Is the [python instructions](https://github.com/Azure/azure-sdk/issues/901#issuecomment-715604282) outdated？

**Comment by v-xuto** [comment]
@joshfree This issue has been closed. Do we need to continue testing this `Automate Azure Service Fabric testing`?
