### ISSUE TITLE
Automate Azure WebJobs testing

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk#902]
Tracking issue for step-by-step instructions for how to manually run e2e tests for Azure WebJobs hosted environments for each of the azure-sdk-for-* languages.  This issue will be used by our Vendor team for manually running tests in this scenario, and will be tracked on the EngSys backlog for eventual automation.

Assigning to @g2vinay who will create the initial instructions specific to Java Azure SDKs.  Other SDK languages will be appended to this issue as further comments.

**Comment by g2vinay** [comment]
We need to automate the way we run tests. The steps to run MSI tests in Azure Web Jobs for the identity component are as follows:

# prerequisite tools
- Azure CLI
- Powershell

# Azure resources
This test requires instances of these Azure resources:
- Azure Key Vault
- Azure App Service
  - with system assigned identity

# Initial Setup:
PLEASE NOTE: This setup is Java specific since it installs the Java & Maven environments. Other languages will have a different set up.

## Set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'identity-test-rg'
- PLAN_NAME
  - name of the app service plan
  - must be unique in the resource group
  - e.g. 'identity-test-app-service-plan'
- PLAN_SKU
  - the type of the plan
  - Choose 'S1', # Allowed values are  B1, B2, B3, D1, F1, FREE, P1, P1V2, P2, P2V2, P3, P3V2, S1, S2, S3, SHARED.
- LOCATION
  - location of the resources
  - e.g. "West US 2"
- APP_NAME_SYSTEM_ASSIGNED
  - name of an Azure App Service
  - must be unique in the resource group
  - e.g. 'identity-test-vm-system'
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique
- WEB_JOB_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique


## Create resources
1. In a terminal with Azure CLI, create the resource group
```bash
az group create \
  -n $RESOURCE_GROUP \
  -l $LOCATION
```
2.  Create the app service plan
```bash
az appservice plan create \
  -n $PLAN_NAME \
  -g $RESOURCE_GROUP \
  -l westus2 \
  --sku $PLAN_SKU
```

3. Create a web app
```powershell
az webapp create -n $APP_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --plan $PLAN_NAME
```

4. Enable System assigned identity on the web app.
```powershell
az webapp identity assign --name $APP_NAME_SYSTEM_ASSIGNED --resource-group $RESOURCE_GROUP
```

3. Create a Key Vault:
```powershell
az keyvault create  -n $KEY_VAULT_NAME -g $RESOURCE_GROUP
```

Get the principal ID for the Web app with system assigned identity:
```powershell
$principalId=az webapp show -n $APP_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --query "identity.principalId"
$principalId=$principalId.Replace('"', '')
```

Allow the Web app with system assigned identity to access the key vault secrets:
```powershell
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $principalId --secret-permissions get list
```

Add a secret called "secret":
```powershell
az keyvault secret set --vault-name $KEY_VAULT_NAME -n secret --value "Secret value"
```

4. Build the executable
# clone azure-sdk-for-java-repo
```bash
mvn clean package -f sdk\e2e\pom.xml
```
Copy executable jar with dependencies from sdk\e2e\target and run.bat script from sdk\e2e\src\main\resources\

Place them in a folder.


# Package, Deploy and run tests
5. Build user credentials for deployment
# get the credentials for deployment
```powershell
$user = az webapp deployment list-publishing-profiles -n $appName -g $resourceGroup `
    --query "[?publishMethod=='MSDeploy'].userName" -o tsv
```

```powershell
$pass = az webapp deployment list-publishing-profiles -n $appName -g $resourceGroup `
    --query "[?publishMethod=='MSDeploy'].userPWD" -o tsv
```

Create web jobs deployment file
```powershell
$webjobzip = "webjob.zip"
if(Test-path $webjobzip) {Remove-item $webjobzip}
[io.compression.zipfile]::CreateFromDirectory("<path-to-folder--from-step-4-containing-executable-and-run-srcipt>", $webjobzip)
```

Deploy the web job
```powershell
$ZipHeaders = @{
    Authorization = $basicAuthValue
    "Content-Disposition" = "attachment; filename=run.cmd"
}

# upload the job using the Kudu WebJobs API
Invoke-WebRequest -Uri https://$APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/$WEB_JOB_NAME -Headers $ZipHeaders `
    -InFile $webjobzip -ContentType "application/zip" -Method Put
```

6. Run the Web Job Test::
```powershell
$resp = Invoke-WebRequest -Uri "https://$APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/$WEB_JOB_NAME/run?arguments=eggs bacon" -Headers $Headers `
    -Method Post -ContentType "multipart/form-data"
```

**Comment by XuGuang-Yao** [comment]
Hi @g2vinay ,

I am following above steps to do java E2E test. My suggestion as below. Please correct me if I miss anything.

1.Since the /keyvault /pom.service.xml file has been deleted by this [PR](https://github.com/Azure/azure-sdk-for-java/pull/8242/files#diff-382249f241a371dc85c8c58be1aaa211), we need change sdk /keyvault/pom.service.xml to sdk/keyvault /pom.xml in Build the executable jar step.

`mvn clean install -Dgpg.skip -Dcheckstyle.skip -Dspotbugs.skip -Drevapi.skip -Dmaven.javadoc.skip=true -DskipTests -f sdk/keyvault/pom.xml`

2.Commands with -Dgpg.skip fails with below error.
![image](https://user-images.githubusercontent.com/53599438/79430883-2e178180-7ffc-11ea-900a-61a12d81d112.png)


So we need to inclose Dgpg.skip with quotation marks.
```
mvn clean install -"Dgpg.skip"  -f eng\code-quality-reports\pom.xml
mvn clean install -"Dgpg.skip" -"Dcheckstyle.skip" -"Dspotbugs.skip" -"Drevapi.skip" -"Dmaven.javadoc.skip=true" -DskipTests -f sdk/keyvault/pom.xml
```

**Comment by jonathandturner** [comment]
For JavaScript:

## Instructions

Follow these instructions using PowerShell.

### set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'pod-identity-test'
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique
- MANAGED_IDENTITY_NAME
  - 3-128 alphanumeric characters
  - must be unique in the resource group
- WEB_APP_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
- PLAN_NAME
  - name of the app service plan
  - must be unique in the resource group
  - e.g. 'identity-test-app-service-plan'
- PLAN_SKU
  - the type of the plan
  - Choose 'S1', # Allowed values are B1, B2, B3, D1, F1, FREE, P1, P1V2, P2, P2V2, P3, P3V2, S1, S2, S3, SHARED.
- LOCATION
  - location of the resources
  - e.g. "West US 2"
- APP_NAME_SYSTEM_ASSIGNED
  - name of an Azure App Service
  - must be unique in the resource group
  - e.g. 'identity-test-app-system'
- APP_NAME_USER_ASSIGNED
  - name of an Azure App Service
  - must be unique in the resource group
  - e.g. 'identity-test-app-user'

## App Service

Create the app service plan
```
az appservice plan create -n $PLAN_NAME -g $RESOURCE_GROUP -l $LOCATION --sku $PLAN_SKU
```

Create a web app
```
az webapp create -n $APP_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --plan $PLAN_NAME -r '"node|10.15"'
```

Enable System assigned identity on the web app.
```
az webapp identity assign --name $APP_NAME_SYSTEM_ASSIGNED --resource-group $RESOURCE_GROUP
```

### Resource Group
```sh
az group create -n $RESOURCE_GROUP --location westus2
```

### Managed Identity
Create the managed identity:
```sh
az identity create -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME
```

Save its `clientId`, `id` (ARM URI), and `principalId` (object ID) for later:
```sh
$MANAGED_IDENTITY_PRINCIPAL_ID=az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME --query principalId -o tsv
```

### Key Vault
Create the Vault:
```sh
az keyvault create -g $RESOURCE_GROUP -n $KEY_VAULT_NAME --sku standard
```

Add an access policy for the managed identity:
```sh
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $MANAGED_IDENTITY_PRINCIPAL_ID --secret-permissions set delete
```

### Web App
```
az webapp config appsettings set -g $RESOURCE_GROUP -n $APP_NAME_SYSTEM_ASSIGNED --settings KEY_VAULT_NAME=$KEY_VAULT_NAME
```

### Build the webapp
```
git clone https://github.com/azure/azure-sdk-for-js --single-branch --branch master --depth 1
```

```
cd azure-sdk-for-js\sdk\identity\identity\test\manual-integration\webjobs\App_Data
```

Install the requirements:
```
node install
```

Build the job:
```
tsc -p .
```

Zip the App_Data directory, and all its contents, into "AzureTestJob.zip"


### Upload the job
```
$user = az webapp deployment list-publishing-profiles -n $APP_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP `
    --query "[?publishMethod=='MSDeploy'].userName" -o tsv

$pass = az webapp deployment list-publishing-profiles -n $APP_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP `
    --query "[?publishMethod=='MSDeploy'].userPWD" -o tsv

$creds = "$($user):$($pass)"
$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($creds))
$basicAuthValue = "Basic $encodedCreds"
$Headers = @{
    Authorization = $basicAuthValue
}

Invoke-WebRequest -Uri https://$APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/zipdeploy -Headers $Headers -InFile .\AzureTestJob.zip -ContentType "multipart/form-data" -Method Post

```

### Trigger the job

```
az webapp webjob triggered run -w AzureTestJob -g $RESOURCE_GROUP -n $APP_NAME_SYSTEM_ASSIGNED
```

### Test the job completed successfully

```
az keyvault secret show -n "secret-name" --vault-name "$($KEY_VAULT_NAME)"
```

# Delete Azure resources
After running tests, delete the resources provisioned earlier:
```sh
az group delete -n $RESOURCE_GROUP -y --no-wait
```

**Comment by XuGuang-Yao** [comment]
Hi @jonathandturner,

I am following above steps to do JS E2E test. My suggestion as below. Please correct me if I miss anything.

If I run `node install` , below error will occur. Do you mean `npm install `?

![image](https://user-images.githubusercontent.com/53599438/80327070-6d03cd80-886d-11ea-9224-a91a91e9c1d3.png)

Anyway, I tried to run the `npm install` instead of `node install ` but another error occured.

![image](https://user-images.githubusercontent.com/53599438/80327089-7d1bad00-886d-11ea-99c9-3a6bdf410e01.png)

Could you please help to check the test steps and update them?

**Comment by jonathandturner** [comment]
@XuGuang-Yao - apologies, yes, it should be `npm install`.  That was a typo.

I've updated the instructions, please try again.

**Comment by XuGuang-Yao** [comment]
@jonathandturner , -Thanks you for your quick reply. 

As I mentioned before, I have tried to run the `npm install` instead of `node install` . Please refer to my previous comment for result. I believe the command won't work until we figure out how to install libsecret in this test scenario. (related to [keytar issue](https://github.com/atom/node-keytar#on-linux))

**Comment by XuGuang-Yao** [comment]
@jonathandturner ,

I am following the JS instrucation step by step to do E2E test against May release.

After exexuting all commands, I got the below result.
![image](https://user-images.githubusercontent.com/53599438/81796819-8af55180-9540-11ea-9edf-ac40cf440676.png)

It looks like the test code didn't run since there is no a secret named 'secret-name'.I tried to repeat the steps 3,4 times but getting the same result.

Did I miss anything?

**Comment by kurtzeborn** [comment]
As @joshfree said in the initial description, this issue is being used by the vendors to track running the tests manually, so putting "Client" label back on this issue.  I've opened https://github.com/Azure/azure-sdk/issues/1539 to track adding WebJob support on the EngSys backlog.

**Comment by joshfree** [comment]
Closing since #1539 is tracking the EngSys work separately.  There's no remaining work here, until #1539 is complete.

**Comment by joshfree** [comment]
Re-opening issue; @danieljurek will handle #1539 and once #1539 is resolved then @g2vinay can help onboard #902 with Java first, and the rest of the languages next.

**Comment by catalinaperalta** [comment]
Steps to test for Golang:
## Prerequisites
- Azure CLI
- Powershell (We will run all the commands mentioned in powershell)
- Golang version 1.14 or above installed

## Azure resources
This test requires instances of these Azure resources:

- Azure Managed Identity
- Azure App Service with system assigned identity and user assigned identity

## Initial Setup

*Set the following environment variables to simplify copy-pasting*

- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'identity-test-rg'
- PLAN_NAME
  - name of the app service plan
  - must be unique in the resource group
  - e.g. 'identity-test-app-service-plan'
- PLAN_SKU
  - the type of the plan
  - Choose 'S1', # Allowed values are B1, B2, B3, D1, F1, FREE, P1, P1V2, P2, P2V2, P3, P3V2, S1, S2, S3, SHARED.
- LOCATION
  - location of the resources
  - e.g. "West US 2"
- APP_NAME_SYSTEM_ASSIGNED
  - name of an Azure App Service
  - must be unique in the resource group
  - e.g. 'identity-test-app-system'
- APP_NAME_USER_ASSIGNED
  - name of an Azure App Service
  - must be unique in the resource group
  - e.g. 'identity-test-app-user'
- MANAGED_IDENTITY_NAME
  - 3-128 alphanumeric characters
  - must be unique in the resource group

In a powershell with Azure CLI, create the resource group. This step is optional, skip if resource group already exists.
```
az group create -n $RESOURCE_GROUP -l $LOCATION
```

Create the app service plan
```
az appservice plan create -n $PLAN_NAME -g $RESOURCE_GROUP -l $LOCATION --sku $PLAN_SKU
```

Create a web app
```
az webapp create -n $APP_NAME_SYSTEM_ASSIGNED -g $RESOURCE_GROUP --plan $PLAN_NAME
```

Enable System assigned identity on the web app.
```
az webapp identity assign --name $APP_NAME_SYSTEM_ASSIGNED --resource-group $RESOURCE_GROUP
```

Create a user identity for the second web app:
```
az identity create -n $MANAGED_IDENTITY_NAME -g $RESOURCE_GROUP -l $LOCATION
```

Create the second web app:
```
az webapp create -n $APP_NAME_USER_ASSIGNED -g $RESOURCE_GROUP --plan $PLAN_NAME
```

Assign the user Identity from Step 5 to the second web app.
1. Login to portal
2. Go to the second web app resource
3. Select the Identity tab under Settings,
4. Click on User assigned
5. Click on Add
6. Select your subscription
7. Search for the user Identity with name $MANAGED_IDENTITY_NAME and select it from the list.

## Build the webapp

Download the Go SDK:
```
git clone https://github.com/Azure/azure-sdk-for-go.git
```

Go to the samples folder
```
cd azure-sdk-for-go/sdk/samples/azidentity/manual-tests/managed_identity
```

Build the project
```
go build
```

This should generate a `main.exe` which should be compressed into a .zip file. The following commands assume that the compressed folder is called `main.zip`.

Execute the following commands to set up for the headers that will be sent with the requests
```
$user = az webapp deployment list-publishing-profiles -n $env:APP_NAME_SYSTEM_ASSIGNED -g $env:RESOURCE_GROUP --query "[?publishMethod=='MSDeploy'].userName" -o tsv
```

```
$pass = az webapp deployment list-publishing-profiles -n $env:APP_NAME_SYSTEM_ASSIGNED -g $env:RESOURCE_GROUP --query "[?publishMethod=='MSDeploy'].userPWD" -o tsv
```

```
$creds = "$($user):$($pass)" 
```

```
$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($creds))
```

```
$basicAuthValue = "Basic $encodedCreds" 
```

Set the header variables that will be used when uploading and triggering the jobs
```
 $Headers = @{
     Authorization = $basicAuthValue
}
```

```
$ZipHeaders = @{
     Authorization = $basicAuthValue
     "Content-Disposition" = "attachment; filename=main.exe"
}
```

### Upload the job
```
Invoke-WebRequest -Uri https://$env:APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/WebJob1 -Headers $ZipHeaders -InFile main.zip -ContentType "application/zip" -Method Put -UseBasicParsing
```

### Trigger the job
```
$resp = Invoke-WebRequest -Uri "https://$env:APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/Webjob1/run?arguments=eggs bacon" -Headers $Headers  -Method Post -ContentType "multipart/form-data" -UseBasicParsing
```

You can run `echo $resp` to see if the webjob was accepted with a `202` status. 

### Check the results
To get information about the webjob that was triggered run the following command until you see that it changes status from `Running` to `Success`.
```
$resp = Invoke-WebRequest -Uri "https://$env:APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/WebJob1" -Headers $Headers  -Method Get -ContentType "multipart/form-data" -UseBasicParsing
```

To see the response run `echo $resp`

Once you see that the request was successful, run the following command:
```
echo $resp.Content
```

Copy the url under `output_url` and paste it in the browser. Successful output should look similar to:
```
[10/22/2020 21:27:14 > 636b58: SYS INFO] Status changed to Initializing
[10/22/2020 21:27:14 > 636b58: SYS INFO] Job directory change detected: Job file 'main.exe' timestamp differs between source and working directories.
[10/22/2020 21:27:15 > 636b58: SYS INFO] Run script 'main.exe' with script host - 'WindowsScriptHost'
[10/22/2020 21:27:15 > 636b58: SYS INFO] Status changed to Running
[10/22/2020 21:27:17 > 636b58: INFO] Calling GetToken()...
[10/22/2020 21:27:17 > 636b58: INFO] Success! Token received.
[10/22/2020 21:27:17 > 636b58: SYS INFO] Status changed to Success
```

**Comment by Menghua1** [comment]
Hi @g2vinay Following above steps, when run system Assigned Web job Test about **java E2E**, we encountered an error after executing the following command: 
```
$resp = Invoke-WebRequest -Uri "https://$APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/Systemassignedjob/run?arguments=eggs bacon" -Headers $Headers -Method Post -ContentType "multipart/form-data"

if ($resp.RawContent -match "\nLocation\: (.+)\n")
{
    $historyLocation = $matches[1]
    $hist = Invoke-RestMethod -Uri $historyLocation -Headers $Headers -Method Get
    # $hist has status, start_time, end_time, duration, error_url etc
    # get the logs from output_url
    Invoke-RestMethod -Uri $hist.output_url -Headers $Headers -Method Get
}
```
The detailed error information is as follows:
![image](https://user-images.githubusercontent.com/111940661/222678373-0c7ea7b5-92cf-46a5-9ecf-e7b98fad76ec.png)


Could you help to check and resolve the error?

**Comment by v-jiaodi** [comment]
@catalinaperalta @chlowell Following above steps, encountered some issues about **Golang E2E Test**. Firstly, the following command, `managed_identity` does not exist and should be updated to `managed-identity`.
![image](https://github.com/Azure/azure-sdk/assets/80496810/154b047b-e1e3-4ea9-97b8-36b071067f7f)



Then, when run `go build` get error message as follow:
![image](https://github.com/Azure/azure-sdk/assets/80496810/eeb2afb1-a03c-46ca-8ef6-46323d6b8d54)

Could you help to check and resolve the error?

**Comment by Menghua1** [comment]
Hi @g2vinay,@jntrnr Following above steps, encountered some issues about **java and JavaScript E2E Test**. we encountered an error after executing the command: 
```
Invoke-WebRequest -Uri [https://$APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/triggeredwebjobs/Systemassignedjob](https://%24app_name_system_assigned.scm.azurewebsites.net/api/triggeredwebjobs/Systemassignedjob) -Headers $ZipHeaders -InFile $systemAssignedWebJobzip -ContentType "application/zip" -Method Put
```
or 
```
Invoke-WebRequest -Uri "[https://$APP_NAME_SYSTEM_ASSIGNED.scm.azurewebsites.net/api/zipdeploy](https://%24app_name_system_assigned.scm.azurewebsites.net/api/zipdeploy)" -Headers $Headers -InFile .\AzureTestJob.zip -ContentType "multipart/form-data" -Method Post
```
The error messages of java and JavaScript are the same, and the detailed error messages are as follows:
![image](https://github.com/Azure/azure-sdk/assets/111940661/d4ff5dfa-a5ad-4853-b972-dbc308dddfdb)

Could you help to check and resolve the error?

**Comment by v-xuto** [comment]
@joshfree This issue has been closed. Do we need to continue testing this `Automate Azure WebJobs testing`?
