### ISSUE TITLE
Keep dynamic resource allocation/deallocation scripts up to date

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk#934]
Changes to the resource allocation/deallocation scripts should be reflected in all repos and those scripts should be consistent. 

Ideas discussed so far: 
* Scripts reach up to a public location and validate a hash of the contents, erroring if the has does not match their hash -- if we did this we'd need to determine how to do alerting (do all pipelines break when the hash changes meaning that the current executing script is outdated?) 

* Submodules 

* Scripts bootstrap from a well known public location -- this would mean that the script in the repo may not be what is executed and that would create confusion. Recommend against this approach.

**Comment by weshaggard** [comment]
A couple other options that I think I prefer a little more:

- Write the scripts in tools package we publish and restore during our builds. 
- Have automation that will keep a set of scripts in a common eng directly in-sync across our different repos. This is similar to how some of the .NET team common infrastructure works.
- Use yml template to pull in the steps. This has the drawback of not being available for local devs which probably rules this out.

No matter what we end up doing we need to be sure that the scripts and/or tools are versioned so that servicing release can use the exact version they used when we do older builds. It should not depend on pulling the latest because that is almost guaranteed to break.

**Comment by kurtzeborn** [comment]
You mentioned that this will be solved by the changes you're making to mirror in scripts and tools from azure-sdk-tools.

**Comment by weshaggard** [comment]
@heaths @danieljurek we now have the infra in place to sync the shared script files. So you guys should be good to move your ARM scripts into the eng/common directory in the azure-sdk-tools repo to have it sync to the other repos.

**Comment by heaths** [comment]
That is tracked in azure/azure-sdk-tools#358

**Comment by weshaggard** [comment]
Closing this issue as dup of Azure/azure-sdk-tools#358
