### ISSUE TITLE
Change Request: Clarify AZURE_NO_PROXY formate for all languages

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk#978]
## The Basics

* Which design guideline is affected?

https://azure.github.io/azure-sdk/general_azurecore.html#environment-variables

* Which target languages are affected?

All languages

* Describe the change:

Clarify the expected format for `NO_PROXY`.

## Reasoning

Please provide any additional detail or reasoning for the request. 

Currently, `NO_PROXY` only states that CIDR annotation must be supported, it doesn't clarify an expected format for the value stored in the environment variable. 

Should this be a language specific format? For example Java has a corresponding `http.nonProxyHosts` [(documentation)](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html) environment variable which is expected to be a `|` delimited list of host string, which may be a regex string.

**Comment by kyle-patterson** [comment]
Scheduled for 4/12

**Comment by kyle-patterson** [comment]
Link to recording (MSFT INTERNAL): https://msit.microsoftstream.com/video/2240a1ff-0400-86e9-7be5-f1ea7e981f89

AZURE_NO_PROXY format:
- MUST be comma-separated
- MUST support IP addresses, CIDR ranges and hostnames
-- Do hostnames typically support wildcards? (This could be fairly common)
-- Domain extensions are supported by wget, which are similar to wildcards
- For idiomacy, restrict to what the language supports

Q: Support for NO_PROXY or not, or support for varying levels of NO_PROXY?
- Java example: Azure-specified NO_PROXY takes precendence over Java's NO_PROXY. Proxy selector could parse out and handle Azure-specified NO_PROXY. This wouldn't be considered lowest common denominator.
- JS/TS core doesn't support NO_PROXY yet because the transport doesn't support it

Q: What does partial support look like? Ie, you have NO_PROXY variable under our guidelines, but there is a proxy available?
- Best effort to support the max level, and otherwise document lack of support.

**ACTION** @kyle-patterson to submit PR updating general guidelines
