### ISSUE TITLE
Board Review: Custom User Schemas (dynamic and static)

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk#997]
As a follow up to the [Querying review](https://github.com/Azure/azure-sdk/issues/979), we want to continue the discussion on how to deal with custom user schemas.

For services like Azure Cognitive Search where users can [create custom schemas](https://docs.microsoft.com/en-us/azure/search/search-get-started-dotnet#1---create-index) for their data and then [execute queries over it](https://docs.microsoft.com/en-us/azure/search/search-get-started-dotnet#3---search-an-index), there are three options for query return types that we want to consider: low level, dynamic, and static.  All languages should provide low-level and dynamic options.  C# and Java should provide static options and we should have a reasonable story for TypeScript as well.

### Low Level
Return a `string` or `Stream` and allow users to handle ALL processing on their own.  This doesn't deserialize the response.

```C#
public class SearchIndexClient
{
    public Task<Stream> SearchRawAsync(...) { } // No idea what we call this
}
```

### Dynamic
Return a `Dictionary<string, object>`, `JsonElement`, C# `dynamic` object, etc.  This deserializes the response for the user.

```C#
public class SearchIndexClient
{
    public Task<SearchResult<Document>> SearchAsync(...) { }
}

public abstract class Document
{
    public object this[string key] => ...;
}
```

### Static
Return a strongly typed model `T` that the user knows corresponds to their custom schema.

```C#
public class SearchIndexClient
{
    public Task<SearchResult<T>> SearchAsync<T>(...) { }
}
```

**Comment by adrianhall** [comment]
Scheduled for 10-Feb-2020

**Comment by tg-msft** [comment]
### Preliminary decisions for .NET

I'd appreciate if @KrzysztofCwalina and @JeffreyRichter could weigh in as well, but we're going to start with this approach.

We'll have two methods for accessing dynamic or static models:
   - `Response<Document> doc = await client.GetFooAsync(...);`
   - `Response<Bar> bar = await client.GetFooAsync<Bar>(...);`

We'll support the three different scenarios via:

- **Low Level:**  We will figure out the right way to expose the raw stream via `Response.ContentStream` or similar from the dynamic model overload.
- **Dynamic:** Wrap `JsonElement` in a `Document` class.  I'm currently thinking about:
    ```C#
    public class Document : IReadOnlyDictionary<string, object>
    {
        public JsonElement RawDocument { get; } // Escape hatch
    
        public Document(JsonElement rawDocument) =>
           RawDocument = rawDocument ?? throw new ArgNullEx();
    
        // Untyped wrapper around RawDocument that's slightly
        // nicer to use than JsonElement
        public object this[string key] { get; }
    
        // Maybe:
        // Strongly typed accessor to turn "Number" to "Int32",
        // "date string" to "DateTimeOffset", etc., specialized to
        // a variety of Ts
        public T Get<T>(string key, string format = null);
    
        // Other IReadOnlyDictionary members...
        // (some may be implemented explicitly)
    }
    ```
- **Static:** Use [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)'s attributes and serializer.  If you had models designed for different Track 1 serialization library (like Newtonsoft), you should be able to access the raw `Stream` from the Low Level scenario and pass it along.

**Comment by JeffreyRichter** [comment]
I like this. Some comments:

1. Calling the class "Document" works well for Search but is not good for Azure Tables (which has rows, not documents). I don't know if your intent is to establish a guideline that works for all services or not.

2. For Get<T>, I think you'll support a severe subset of Ts here representing the EDM data types: byte[], bool, UInt8, DateTime, Decimal, Double, Single, Guid, Int16, Int32, Int64, SByte, String, (Time), & TimeSpan. Or maybe somehow complex types consisting of only these EDM types. Maybe for Search, the document is just a string that contains JSON text?


See https://www.odata.org/documentation/odata-version-2-0/overview/, section 6.

**Comment by ctstone** [comment]
One consideration with Cognitive Search (and Form Recognizer) is that a result often has a set of common/known properties along with the user-defined/typed values.

E.g. in search, each [search document] can have a `double Score` and `Dictionary<string, string[]> Highlights` property. In Form Recognizer, a recognized form field will have a dynamic `Value` as well as known fields for `Text`, `BoundingBox`, and `Confidence`.

For search, would it make sense to wrap the user's `Foo` document type in a generic `Document<Foo>` so that both `doc.Score` and `doc.Value.MyCustomField` can be accessed?

For Form Recognizer SDK (unreleased) we have taken a [split approach], since the metadata is available per field, not per record. When you strongly type your custom form, we only map the dynamic values onto your type. In order to get the field metadata, you have to access a Dictionary using the field name. The alternative would be to require users to define a custom type where each property has some type relationship (either generic or derived) to a type provided by the SDK, which makes the object less portal.

[search document]: https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents#response
[split approach]: https://github.com/ctstone/azure-sdk-for-net/blob/form-recognizer-v2.0-GA/sdk/formrecognizer/samples/11-Analyze-File-With-Labeled-Custom-Model-Generic.md

**Comment by kyle-patterson** [comment]
Link to recording (MSFT Internal): https://msit.microsoftstream.com/video/f8415eb1-3b90-492d-85b3-d14a4a9ce7ef

**Comment by tg-msft** [comment]
@JeffreyRichter:
We'd have to come up with a much blander name if we want to put this type in Azure.Core.  I wasn't planning on that for the short term, but we should revisit when Search and Form Recognizer are a little further along.

Yes, we'd only add `Get<T>` overloads for [the limited EDM types supported by Search](https://docs.microsoft.com/en-us/rest/api/searchservice/supported-data-types#edm-data-types-used-in-azure-cognitive-search-indexes-and-documents).  It just seemed nicer to overload `Get<int>("key")` and `Get<DateTimeOffset>("key")` than fill up intellisense with `GetInt32("key")` and `GetDateTimeOffset("key")`.  I could be talked out of that pretty easily if folks think it'll be harder for customers to understand.

@cstone:
We're looking at putting the generic on the outside so it works the same for `Document` and your own model types `T`.  For Search we'll have
- `Response<SearchResult<Document>> SearchAsync(...)` and 
- `Response<SearchResult<T>> SearchAsync<T>(...)`

The dictionary approach feels like it might be pretty heavy to use.  Could we maybe have a `Field<T>` class with in implicit cast to `T` so users would define something like:

```C#
public class Invoice
{
    [DataMember(Name = "InvoiceVatId")]
    public Field<string> VatId { get; set; }

    // ...
}
```

and then use it via

```C#
Analysis<Invoice> result = await client.AnalyzeAsync<Invoice>(photo);
string id = result.VatId;
double confidence = result.VatId.Confidence;
Console.WriteLine($"{id}: {confidence}");
```

**Comment by JeffreyRichter** [comment]
I’m afraid my vote it to have GetInt32(“key”) and GetDateTimeOffset(“key”) instead of the generic because this gives compile time type-safety instead of runtime-type-safety which will throw if the customer doesn’t fully understand the tiny set of valid data types supported.


  *   Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://azure.microsoft.com/training/distributed-cloud-apps/>)
